### ISSUE TITLE
Create possibility to expand/collapse all pages at once

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1004]
### Motivation

For lists with tree nodes, it might be a tedious task to expand or collapse all items in the tree.

### Proposed Solution

Add a button to expand/collapse all items at once.
Use a generic implementation for all trees, so it can be used in the page tree and the language tree.

**Comment by ulliholtgrave** [comment]
Is this really necessary for the Version 1.0? At the moment you can use the search for finding a page rather quickly. I would suggest to put it into Version 2.0 with a prio:high label.
