### ISSUE TITLE
Format datetime fields in API as `ISO8601`

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1011]
### Motivation

When implementing the API, we replicated the WordPress API as similar as possible, including some weird date formats which are not ideal for processing them in the apps.

### Proposed Solution

- For every datetime field, add a new field to represent the same date in [ISO_8601](https://de.wikipedia.org/wiki/ISO_8601) format. This affects e.g.:
    - The `start_date`, `start_time`/ `end_date`, `end_time` fields of events - combine them into `start`/`end`
    - The `sent_date` field of push notifications
    - The `modified_gmt` field of all other objects (maybe also rename this to `last_updated` or `last_modified`)

**Comment by steffenkleinle** [comment]
Could we move this a little bit up please? We still have to live with moment :/

**Comment by svenseeberg** [comment]
Should be possible, yes :)

**Comment by JanErikHuehne** [comment]
Is it correct, that the sent_date and modified_gmt have already been modified beforehand?

**Comment by timoludwig** [comment]
> Is it correct, that the sent_date and modified_gmt have already been modified beforehand?

The `modified_gmt` field of pages & imprint is already correct, but e.g. the `modified_gmt` field of the event and location API reponse and the `timestamp` field of the  push notification API are in the `Y-m-d H:i:s` format, but the desired format is `YYYY-MM-DDTHH:MM:SS.fff` - the representation of [datetime.isoformat()](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat) (which is also the default string representation of a [DateTimeField](https://docs.djangoproject.com/en/4.1/ref/models/fields/#datetimefield) in Django, so just use the unformatted - but timezone aware - model field in the API response and Django will automatically format it correctly).
