### ISSUE TITLE
Enable setting POI position via drag & drop on map

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1035]
### Motivation
We need good way for content creators to enter location coordinates in POIs. We cannot content creators to know the difference between longitude and latitude and are capable of retrieving the numbers from a map.

WordPress currently uses Google Maps to resolve the location of an address and then display a marker on a map.

### Proposed Solution
Allow dragging and dropping a marker on a map.

We have our own tile server: maps.tuerantuer.org. The style can be edited as well: https://github.com/Integreat/integreat-maplibre-style#edit-the-style

We should make use of our new UX & design expert to define a clean process for users.

**Comment by timoludwig** [comment]
This kind of depends on #1170
