### ISSUE TITLE
API: Make use of `location_not_on_map` attribute

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1038]
We have POIs for several use cases in Integreat. We only want the most important POIs to be shown on the map by default (at least in the prototype / demo version).

1. Invert the `location_not_on_map` attribute of the POI model - so rename it to `location_on_map` and set it to `True` per default
2. Make use of the attribute. We could provide 2 API endpoints for the app:
   - One endpoint delivers all POIs with this attribute.
   - The other endpoint filters POIs by `location_on_map = True`

**Comment by timoludwig** [comment]
This is already implemented:
![Screenshot 2021-11-24 at 14-24-08 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/143246553-e7cde7da-d484-4c8d-bd0d-0a208ee36965.png)

**Comment by svenseeberg** [comment]
Is this attribute delivered via the API or is the API content filtered by this attribute?

**Comment by timoludwig** [comment]
Oh funny, it's completely unused at the moment.

**Comment by svenseeberg** [comment]
We could have 2 endpoints:
- One endpoint delivers all POIs with this attribute.
- The other endpoint filters POIs by `location_not_on_map = True`
