### ISSUE TITLE
XLIFF: Only export public versions

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1047]
### Motivation

Usually, only finished texts should be translated into other languages.

### Proposed Solution

When exporting pages as XLIFF, only export the most recent public revision of a translation. Translations which only exist as draft and which don't have an outdated public version shouldn't be exported at all.
This is already the case for PDF files, so we just need to adapt the same behaviour for the XLIFF export.
Also, indicate this in the bulk action text with e.g. "Export published pages as XLIFF for translation to English" (or come up with a more concise label).

**Comment by svenseeberg** [comment]
We need to discuss if we only want to export published pages or also want to support exporting draft versions. It should be no problem to have 2 different bulk actions (export current versions & export published versions).
