### ISSUE TITLE
Rename "location" to "place"

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#1051]
### Motivation

The map feature in the app will use "place" as name for POIs whereas we currently use "location", which is inconsistent and could cause confusion for content creators.

### Proposed Solution

I suggest to change all occurrences of "location" with "place" where it is used as synonym of "POI", especially in the templates.
We can't use "location" as global term because the app already uses this to identify cities/municipalities/regions.

### Additional Context

- This only affects the english term, the German translation "Ort" should remain the same.
- We could also think about renaming the `POI` model to `Place` to keep our code base consistent with the official naming.

**Comment by timoludwig** [comment]
@Carlosbogo Awesome, thanks! :tada:
No, nobody is doing this yet. Since this is your first contribution, feel free to ask whether specific occurrences should be replaced or not. Unfortunately there are also quite a lot of occurrences of the string "location" which should not be replaced, only where it's used in the context of the `POI` model.

**Comment by Carlosbogo** [comment]
I'm trying to work on it but I'm not sure about how far should the changes go:

Should I look for every instance of the `POI` class everywhere in the project and if its name is "location", change it to "place"?
Should I also change it even if it's not the name of a variable, like in the following case?

https://github.com/Integreat/integreat-cms/blob/3dd68af14b8d9334821789504c7f5af81a1195d6/integreat_cms/api/v3/locations.py#L59

**Comment by ulliholtgrave** [comment]
Hey @Carlosbogo , We realized that we have to clarify some definitions with our other developer teams before we can continue to work on that issue. @svenseeberg will take care of it and inform you on any changes (if you are still willing to contribute :) ).

**Comment by Carlosbogo** [comment]
Yeah, that's perfectly fine by me, just let me know when I should start working on it.

**Comment by svenseeberg** [comment]
For reference: https://chat.tuerantuer.org/digitalfabrik/pl/j4tcdangytd48qrru5w9148jsa

**Comment by svenseeberg** [comment]
We decided to not rename it on T31K.
