### ISSUE TITLE
Select all subpages when checking parent page

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1052]
### Motivation

In the page tree, typically a parent page should include all its subpages for all bulk actions.

### Proposed Solution

When selecting a parent page in the page tree, all its sub-pages should be selected as well. This also applies to de-selecting a page. After that, it should be possible to (de-)select individual subpages without changing the selection status of the parent page.

**Comment by svenseeberg** [comment]
Very much related: the "select all" checkbox only selects parent pages now. I think it should also apply to children once they're expanded.

**Comment by svenseeberg** [comment]
Basic concept: when executing a bulk action (XLIFF & PDF export), the view needs to check which checkboxes/pages are in the HTTP Post variables and which pages actually exist. All existing pages that are not in the HTTP POST inherit the "checked" status from the parent that is in the post.
