### ISSUE TITLE
Provide bulk-action for archiving/restoring

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1055]
### Motivation
Right now, users can only archive pages by using the per-item option. For a better workflow, we want to do this also via a bulk action.

### Proposed Solution
Provide another bulk action that puts the status of all selected page items to "archived".

**Comment by timoludwig** [comment]
It should also be possible to bulk-restore all selected archived pages. This requires to add a new column for bulk-actions to the archived page list.

**Comment by timoludwig** [comment]
Also, we need this feature for events and POIs as well.
