### ISSUE TITLE
Statistics: distinguish between single page and full content endpoints

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1092]
### Motivation
Users can download single pages and the full content of one language at once. We already display this information in our diagrams sent via e-mail. Therefore we should not deny this info in Django. We can then stop sending mails.

### Proposed Solution
Add a filter button(?) to split the shown lines into single page and full content downloads. It should be possible to easily switch the view between 4 modes: all data points, only sums, only full content, only single page.

### Alternatives
Keep sending mails forever.

**Comment by ulliholtgrave** [comment]
Duplicate of #1571
