### ISSUE TITLE
Use AJAX for the page tree view

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1101]
### Motivation
Loading all pages in the back end at once consumes lots of CPU and also creates a very huge DOM tree which is slow in some browsers.

### Proposed Solution
We only load the first level and load further pages if the tree is expanded. When doing bulk actions we assume that everything applies to children, unless the children are expanded.

### Alternatives
Non really.

**Comment by melegiul** [comment]
When I understand this right, the preferred approach is to start with a DOM tree only containing root pages and creating new DOM nodes on every click on collapse.
As the django template [integreat_cms/cms/templates/pages/page_tree_node.html](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/templates/pages/page_tree_node.html) contains 160 lines, creating this rows with typescript will get very tedious and after expanding some pages the DOM tree is getting huge, too
Also we would need an extended children endpoint, to get currently missing information like page_translation states (outdated, up-to-date, etc)

So I want to suggest a different approach: the django admin site also uses pagination in combination with drag and drop operation, which are limited to the current selected page
To overcome this limitation, we could introduce a new bulk action "Move", to shift content between different pages
The advantage in this case is, that we can keep our current template loop for populating the table rows (=> less effort), while pagination should also reduce CPU load and DOM tree size at the page tree 

What you think about this?

![image](https://user-images.githubusercontent.com/47010475/152573381-e0809da2-c0bd-472f-96d4-a9ca178792fe.png)

**Comment by timoludwig** [comment]
> As the django template [integreat_cms/cms/templates/pages/page_tree_node.html](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/templates/pages/page_tree_node.html) contains 160 lines, creating this rows with typescript will get very tedious and after expanding some pages, the DOM tree is getting huge, too Also we would need an extended children endpoint, to get currently missing information like page_translation states (outdated, up-to-date, etc)

I think we should not build the complete tree with typescript, but have an ajax endpoint that already returns the rendered html of the partial tree including all translation states etc... so the ajax view takes a parent page id as parameter and returns the rendered html tree of all direct children of that parent. I believe this could work without too much work, in typescript we then only have to insert this html code at the correct position...

**Comment by timoludwig** [comment]
We use a similar approach for the page order table in the page form:
https://github.com/digitalfabrik/integreat-cms/blob/7d1875be3ea2359f896918da895fdcc615684b4d/integreat_cms/cms/views/pages/page_actions.py#L806-L849
When a new parent is selected, the rendered table is requested via ajax and inserted into the correct div...

**Comment by melegiul** [comment]
I like this approach, it should be very applicable. I guess the DOM tree could grow huge nonetheless, but lets start with your suggested API

**Comment by timoludwig** [comment]
I think a huge DOM tree is not a problem in itself, only if it is rendered all at once.... so if it's built gradually, it shouldn't be a problem.
