### ISSUE TITLE
Add ability for cache clearing

### ISSUE THREAD

**Issue by melegiul** [digitalfabrik/integreat-cms#1107]
### Motivation

With increasing cached data, its getting hard to track development processes, so a cli tool for cache clearing would be helpful

### Proposed Solution

https://github.com/timonweb/django-clearcache
This django app brings a manage.py command for instant cache clearing

### Alternatives

Setting caches timeouts to 0 when in dev mode https://docs.djangoproject.com/en/3.2/topics/cache/#cache-arguments, which might affect performance measuring

**Comment by timoludwig** [comment]
Can you elaborate on a use case where this can be helpful? At the moment, we only use two types of caching:
- Caching with [django-cacheops](https://github.com/Suor/django-cacheops) which has its own invalidation command `integreat-cms-cli invalidate all`
- Caching PDF documents which can be cleared by deleting the files

At the moment, I'm not sure if we really benefit from adding a new dependency for cache invalidation.

**Comment by melegiul** [comment]
`integreat-cms-cli invalidate all` Thank you for this one, this is good to know.
My use case was intended for PDF cache clearing, but you are right, deleting the content of the folder cache/pdf is enough for this

**Comment by timoludwig** [comment]
We already clear the PDF cache via a cronjob to periodically delete the generated files.
