### ISSUE TITLE
API: missing page content & excerpt

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1117]
### Describe the Bug
When fetching a page from the API, the `content` and `excerpt` properties only contain empty strings.

See https://cms-django-dev.integreat-app.de/lkaugsburg/de/wp-json/extensions/v3/parents?&url=/lkaugsburg/de/willkommen-lkaugsburg/landkreis

### Expected Behavior
Some content instead of empty strings.

**Comment by ulliholtgrave** [comment]
I couldn't reproduce it locally and it seems like our live system has some problem with migrating the content.

**Comment by svenseeberg** [comment]
True. It seems the content was lost during the migration to treebeard. A new import solved the issue.
