### ISSUE TITLE
API: do not serve proto + domain in thumbnail path

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1119]
### Describe the Bug
The page objects served in the API contain a `thumbnail` property with a URL to an image. The web app expects only a path and cannot handle a full URL that includes the protocol and domain.

### Steps to Reproduce

1. Open webnext.integreat.app
1. In the JS Concole set the back end: `window.localStorage.setItem('api-url', 'https://malte-test.tuerantuer.org');`
1. Open https://webnext.integreat.app/bergen/de
1. Use the inspector to look into the image paths.

### Expected Behavior
Only serve the image path.

**Comment by ulliholtgrave** [comment]
Fixed in commit f9b7c8dd85f721598f635fb2d0b57a18df8f17ca :)
