### ISSUE TITLE
Close button in media library window overlaps scroll bar

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1126]
### Describe the Bug

When the media library is opened in windowed mode (e.g. when selecting a file for insertion into the content of a page), the close button overlaps the scroll bar if there are more media elements than fit into the window

### Steps to Reproduce

1. Go to a page form
2. Insert image
4. See media library window

### Expected Behavior

The button should respect the scroll bar and be aligned a little bit to the left if scrolling is enabled

### Additional Information

![Screenshot (357)](https://user-images.githubusercontent.com/16021269/150817718-179f3fd2-d84b-40ba-a53b-ce1883ac57ee.png)

**Comment by timoludwig** [comment]
Probably, this can be solved together with #1181.
When the layout of the media library is fixed and only the directory content is scrolled, there is no scrollbar anymore which can overlap with the closing button.

**Comment by timoludwig** [comment]
But wait, this already has been resolved in  #1203:

https://github.com/digitalfabrik/integreat-cms/commit/d3a773fda46881d12dda4d3a262e9b9044987345\#diff-797d8d48569285f8ed8c8463fad15b15e09ea5eea95fbff4a298bfba1d5267a6

![Screenshot 2022-03-17 at 16-20-53 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/158833887-959c6c2c-d578-491f-814a-8351cc40fce6.png)

**Comment by ulliholtgrave** [comment]
Well, It is no longer overlapping the scrollbar, but the sidebar, if the screen is to small :see_no_evil: However, this will be fixed in my next PR :)
