### ISSUE TITLE
Prefetch subpages in advance

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1158]
### Motivation

In PR #1149, we introduced the dynamic fetching of subpages in the page tree. Everytime the child pages of a parent page are expanded, an ajax request is performed to retrieve the result from the server, which causes the expansion to take a small loading time:

![Peek 2022-02-10 13-11](https://user-images.githubusercontent.com/16021269/153406471-9dbdf081-ce78-4b49-abab-9cce3240e6b2.gif)

### Proposed Solution

It would be cool if this delay could be reduced, e.g. by automatically loading the subpages before the expansion button is clicked (but after the rest of the root pages are rendered completely, it shouldn't slow down the loading time of the initial page tree). We could recursively walk the tree completely or only load n+1 levels depending on which pages are currently expanded.
The subpages should then expand instantly after the button is clicked:

![Peek 2022-02-10 13-11-2](https://user-images.githubusercontent.com/16021269/153406503-60415b62-60c6-4021-a3fb-c27cb265d7f4.gif)

### Additional Context

There are two tickets that depend on this issue:
- #1175
- #1244

**Comment by david-venhoff** [comment]
When implementing this, #1175 can probably implemented, too.
Right now this is only partially implemented: The empty label only gets shown if a page has no subpages at all, but it should also be shown, if e.g. all its subpages are archived
