### ISSUE TITLE
Update file paths in content when media file is replaced

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#1168]
### Describe the Bug

At the moment, we keep the file path identical when we're replacing media files.
This has the disadvantage that the app needs to download the files again to check whether it has changed. It would be more efficient if we treat filenames more like unique ids of files and change them in the content when they are replaced.

### Steps to Reproduce

1. Insert media file into content of page
2. Replace file in media library
3. Refresh preview of page
4. Even though the timestamp in the media library itself is updated, the content remains the same.

### Expected Behavior

When a media file is replaced in the media library, the new image should also be shown in the apps.

We can use the `Link` model of the linkcheck app to get the mapping between media files and page translations which contain the file. Then, we can update the url in the content.

### Actual Behavior

Since the file path doesn't change, it is cached at the moment

### Additional Information

Related issues:
- #1851

**Comment by osmers** [comment]
Referring here to issue 1742 - it would still be helpful to have an updated and an original date, so that I know that the file has been updated - it if is not too much hassle

**Comment by steffenkleinle** [comment]
Could you notify the app team in [this issue](https://issues.tuerantuer.org/browse/IGAPP-1193) once this is done please? Thanks :)

**Comment by sarahsporck** [comment]
I'm wondering what makes most sense here. Currently files are stored like this: `{subdirectory}/{strftime('%Y/%m')}/{filename}` and the new (replacing) file only modifies certain attributes of the `media_file`.

- upload the new file at e.g. `{subdirectory}/{int(time())}/{filename}`
- delete the old file at the other path

Am I missing something? :)

**Comment by timobrembeck** [comment]
Hmm, I guess I would stick with the year/month naming scheme instead of `int(time())`, so maybe it would already suffice to just remove the following lines?
https://github.com/digitalfabrik/integreat-cms/blob/cd9508fd7700b663ebb76a78a04d9c9c1d55e83f/integreat_cms/cms/models/media/media_file.py#L46-L55

And I think Django does not automatically delete the old file, yes so we'd have to do that manually.
And after that, we need to to a search & replace the paths in the whole content to make sure we don't get a bunch of 404 errors on the old file path.

**Comment by sarahsporck** [comment]
Thank you for the hint. Was a little bit stuck here.
