### ISSUE TITLE
Page tree broken after searching and going back

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1179]
### Describe the Bug
When using the back button of the browser after searching, the page tree is expanded. After that, the collapsing function is broken.

Can we tell the browser to reload the full page after using the back button? However, it would be the best solution to actually keep the status of the tree after using the back button.

~~This could be related to #1131~~

**Comment by timoludwig** [comment]
This is probably browser-specific cache, see e.g. https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers

**Comment by svenseeberg** [comment]
I think we should use the meta tag approach and add the following tags to the page tree DOM tree.

```
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
```

**Comment by timoludwig** [comment]
Just tested this locally and unfortunately, the meta tags do not have an effect on the in-memory cache of the DOM tree.
Instead, we need the HTTP headers, I think this SO answer explains it very well: https://stackoverflow.com/a/5493543
