### ISSUE TITLE
Save location on map without coordinates

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1180]
### Describe the Bug
Not all users are able to search for coordinates. If the location is not set to be shown on the map (checkbox), it should be allowed to have empty coordinates.

Related: #1170

**Comment by timoludwig** [comment]
I think the coordinates are required to render the POIs correctly on the app's map.
So we can't really make this optional, maybe only if the option to not show the location on the map is enabled?
Anyway, the ideal solution would be to request the coordinates via an API and auto-fill them (see also #1000)

**Comment by svenseeberg** [comment]
Yes, the automatic solution would be best. However, we need some sort of validation function at some point anyways. Therefore 0, 0 should be okayish enough and could be the default values.
