### ISSUE TITLE
Fix code scanning alert - Information exposure through an exception

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1202]
This was raised in #1201. I'm pretty sure its a false positive. It catches 404s from decorated functions. That should do no harm (in any case I can think of).

Tracking issue for:
- [ ] https://github.com/digitalfabrik/integreat-cms/security/code-scanning/74

**Comment by timoludwig** [comment]
Yes, I also think this is a false positive. On the contrary, I would even say that we want to give out the information which element was not found.
