### ISSUE TITLE
XLIFF export bulk action not selectable

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1211]
### Describe the Bug
The bulk action "Export XLIFF to translate to LANG" is not selectable for non experienced users.

### Steps to Reproduce

1. Go to Pages
2. Select a language that is not the source language
3. Select pages (check box)
4. Try to export the XLIFF file

### Expected Behavior
The bulk action should be completely hidden for non-experienced users.

### Actual Behavior
The bulk action is visible but not clickable.

**Comment by melegiul** [comment]
Testing it locally, the bulk action is available
Has the user the right permission?
![image](https://user-images.githubusercontent.com/47010475/154981269-f330204e-c9f5-4098-9eca-175fd36616c3.png)
