### ISSUE TITLE
Clone Region buggy

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1217]
### Describe the Bug
Only the first page was cloned.

### Expected Behavior
All pages should be cloned.

### Additional Information
Also the Media Library was empty, but that may be intentional?!

**Comment by membralala** [comment]
I tried to reproduce this issue, but for me it works as expected (well, the Media Library is empty indeed, but the page tree seems to be fine).

**Comment by svenseeberg** [comment]
It seems that this is due to duplicate page slugs.
