### ISSUE TITLE
Imprint broken

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1227]
### Describe the Bug
The app cannot display the data from our imprint endpoint.

### Steps to Reproduce

1. Open any imprint on malteapp.de

**Comment by ulliholtgrave** [comment]
Fixed in the last release :)

**Comment by svenseeberg** [comment]
Sadly there is still another problem.

**Comment by svenseeberg** [comment]
https://cms.malteapp.de/barth/de/wp-json/extensions/v3/disclaimer is missing the path
https://malteser.tuerantuer.org/barth/de/wp-json/extensions/v3/disclaimer is missing the path
