### ISSUE TITLE
Saving of Somali translation in Karlsruhe (Malte) does not work due to "relativ zu: ... 1522 ist keine gültige Auswahl" 

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-cms#1236]
### Describe the Bug

Saving of a translation in Somali is not possible. 

### Steps to Reproduce

1. Go to ['...'] https://cms.malteapp.de/leakarlsruhefelsstrasse/pages/so/1523/edit/
2. Click on '....' Aktualisieren
3. 

![image](https://user-images.githubusercontent.com/16462172/155142139-3380d096-f76e-411e-8594-f5135bf1b393.png)

### Additional Information

Experienced before during "migration night" but not exactly sure, where.

**Comment by timoludwig** [comment]
This is probably related to #1131 - changing the language tree has weird consequences for pages.
