### ISSUE TITLE
Provide possibility to confirm the up-to-dateness of a page 

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1258]
### Motivation

If our content has not been changed for too long, it can mean a loss of credibility. We should therefore provide the possibility for editors to confirm the timeliness.

### Proposed Solution

The page form should have a function under "Actions" that allows an editor to confirm that all translations are up to date. Then all current translations of the page should be updated and the last_modified field should be set to the current time.

**Comment by svenseeberg** [comment]
IMHO this should be a post migration issue.

**Comment by timoludwig** [comment]
> IMHO this should be a post migration issue.

No, this is a feature request. If the content of a page hasn't changed in two years, but the content is still valid, the content managers want to have the possibility to refresh the date to make it obvious that the information is not outdated. At the moment, this takes `2n` clicks for `n` languages, so for cities with many languages, this soon becomes a time-consuming task if performed for multiple pages.

**Comment by svenseeberg** [comment]
Yes, but this is not a function of WP either.

**Comment by timoludwig** [comment]
Oh sorry, I misunderstood your objection. Yes, I agree, should be fine for the 1.2 milestone. If somebody wants to implement it earlier, fine, but this is not a hard requirement.

**Comment by dkehne** [comment]
Also we could work within the analytics-page to show up the last x pages which are the oldest ones OR we show pages there which haven't been updated for x years.
