### ISSUE TITLE
Allow login with email address

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1293]
### Motivation

In WordPress, users are used to enter their email address when logging in instead of their username.

### Proposed Solution

- Make email address field unique in database
- Allow the login with email address

### Additional Context
- Think about what happens if two users with the same email  address already exist in the database. Can we fix this in migrations?

**Comment by ulliholtgrave** [comment]
Sven checked it and the email addresses in our current system are unique :)
