### ISSUE TITLE
Add organization name & logo to the page API response

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1322]
### Motivation

To make use of our organizations we want to mark content that is maintained by one.

### Proposed Solution

For the App it would be the easiest if we add some HTML label directly in our content. The proposed solution from our UI/UX team can be seen in the following screenshot:
![image](https://user-images.githubusercontent.com/15608678/167953090-a62f29cf-6160-4825-bcd6-39c809e8b011.png)

**Comment by svenseeberg** [comment]
The app already has a footer with the last changed date. In the team sync we decided that it is probably nicer to simply add the path to the image as an API attribute which the app can use.

**Comment by steffenkleinle** [comment]
Where can we test this/how can we add this to a page/the api?
