### ISSUE TITLE
PDF documents not downloadable

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1349]
### Describe the Bug

When a PDF is exported from the page tree, the PDF is correctly generated but cannot be downloaded on all browsers.
Probably this has to do with the fact that the PDF is generated with a POST-view, but if the same url is requested via GET, the export does not work.

One solution could be to store PDFs in a directory that is served by the Apache server and just redirect to the PDF url after generating it instead of directly serving it.

### Steps to Reproduce

1. Go to page tree
2. Export pages as PDF
3. Try do download exported PDF

### Expected Behavior

In firefox, everything works as expected: The desired location ca be selected and the file is downlaoded

### Actual Behavior

In Chrome and Opera, a "Network Error" occurs

### Additional Information

Opera:

![Image Pasted at 2022-4-11 15-15](https://user-images.githubusercontent.com/16021269/162755647-4989c051-71e0-4cbb-823c-246f02095d12.png)

Chromium:

![pdf-chrome](https://user-images.githubusercontent.com/16021269/162755632-eafff75f-9f74-43d3-8646-f03a04b9601c.png)

**Comment by svenseeberg** [comment]
I'm trying to find out if this can be considered a bug in Chromium or not. According to https://datatracker.ietf.org/doc/html/rfc2616#section-9.5 

The RFC states the following:

> If a resource has been created on the origin server, the response SHOULD be 201 (Created) and contain an entity which describes the status of the request and refers to the new resource, and a Location header (see [section 14.30] https://datatracker.ietf.org/doc/html/rfc2616#section-14.30)).
