### ISSUE TITLE
Imprint deletion breaks feedback list

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1359]
### Describe the Bug

If a feedback for an imprint exist and the imprint is deleted, the corresponding feedback breaks the feedback list.

**Comment by timoludwig** [comment]
This appears to be a duplicate of #1282, which should have been fixed by now :thinking: 
I cannot reproduce this on the current develop branch, could you maybe clear your redis cache and try again?
