### ISSUE TITLE
Migrate from `setup.cfg` to `pyproject.toml`

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1362]
### Motivation

There seem to be some development in the setup tools project and this issue is a reminder to keep track of it. Especially https://github.com/pypa/setuptools/milestone/7 and https://github.com/pypa/setuptools/issues/3214 are important for us, as this might deprecate our current solution.

**Comment by timoludwig** [comment]
> Warning:
> Support for declaring [project metadata](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/) or configuring setuptools via pyproject.toml files is still experimental and might change (or be removed) in future releases.

— https://setuptools.pypa.io/en/stable/userguide/pyproject_config.html

I think we should at least wait until the new format is not experimental anymore before jumping on the bandwagon.
Also, I don't think it's a real danger that `setup.py`/`setup.cfg` will really be deprecated - I'm pretty sure they will continue to work for a few decades. But I like the idea of adapting new, better formats and support the migration to the new format once it's finalized. I don't think this is going to happen in the near future though, so I moved this from version 1.3 to the backlog...

**Comment by timoludwig** [comment]
I can't find the quote from my previous comment in the docs anymore, so I assume it's now safe to migrate as soon as we want. It's still very low prio since I'm not sure whether the old format will be deprecated before the end of life of this project :sweat_smile:
