### ISSUE TITLE
Error when viewing a non-existing page translation

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#1387]
### Describe the Bug

The page tree can show page rows which exist in a root language, but not the current language. These rows have a view preview action. Clicking on the button to preview such a translation causes an error:
![grafik](https://user-images.githubusercontent.com/78504586/166944975-ea86ffe1-e5ba-4f10-9d73-53ebf177012b.png)

### Steps to Reproduce

1. Go to the page tree
2. Switch to another language, which does not have all pages of the root language
3. Click on the "view page as preview" button

### Expected Behavior

No crash:
Empty preview / no option to show preview at all

### Actual Behavior

Crash

**Comment by timoludwig** [comment]
I guess this will be solved by #1348
