### ISSUE TITLE
Translate all texts & captions

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1431]
### Motivation
In some cases (examples?) English terms are used that are difficult to understand for German language natives.

### Proposed Solution
Replace English words with German translations. We should reevaluate if we can/should translate words like "broken links" or "Dashboard".

### Alternatives
If we deem that there are no good translations, we could add and or validate tool tip messages.

**Comment by svenseeberg** [comment]
Blocked by #1429

**Comment by timoludwig** [comment]
I vote for closing this ticket. If UI/UX testing detects issues with our current wording, we can reopen this issue with specific examples, but until then I don't see a reason to increase our issue count with problems we don't yet know about.

Regarding the two examples mentioned in the description:
- "Broken links" was translated in the meantime
- "Dashboard" is a well-recognized term from WordPress and does not have many good alternatives
