### ISSUE TITLE
Add cross-region statistics to admin dashboard

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1433]
### Motivation
We have a some activities and actions which are measured by quantitative numbers, e.g. 
1. active contributors in Integreat and active contributors per region
2. ~API usage statistics for all regions~ will be done with a different tool, see [INFRA-281](https://issues.tuerantuer.org/browse/INFRA-281)
3. which language is used how often
4. how many instances are online/hidden
5. whats the average amount of words?
6. whats the average translation status (how many pages are up to date, how many are not up to date

### Proposed Solution
We could develop a analytics dashboard to show up this figures. does not need to be too graphical, because it is just for us to see if things develop the right way.

**Comment by timoludwig** [comment]
For reference: 2. is not relevant anymore since this will be solved in [INFRA-281](https://issues.tuerantuer.org/browse/INFRA-281)

**Comment by JoeyStk** [comment]
Should be transfered to Jira

**Comment by timoludwig** [comment]
However, I wouldn't put too much Python code on our production servers without the normal reviewing process of our cms repo. So instead, I suggest to wait for https://github.com/digitalfabrik/integreat-cms/pull/2071 to get merged and implement all the stats methods as management commands, which can then be called on the prod server to write the stats to grafana.

**Comment by osmers** [comment]
@timoludwig yes, that's exactly what we discussed - we want to have all those statistics in grafana which is why Sven will transfer it to Jira Infra Board for himself

**Comment by timoludwig** [comment]
Yes, but I wouldn't recommend to implement these functions as scripts running only on the production server - instead, we should develop them as part of this repository (which also means we can properly test them), so the infra part can be reduced to "execute one command and send the result to grafana"...

**Comment by svenseeberg** [comment]
I think it depends on what we need the data for and how often we need it. If this is some kind of frequent and permanent process that uses the information, then yes. If we only need this once or a few times, I'd reduce the effort as much as possible.

**Comment by svenseeberg** [comment]
> AFAICT this list would mainly serve one purpose: find regions where the content is not up to date.

@dkehne @osmers could you please provide some user stories or use cases?

**Comment by dkehne** [comment]
We will convert this issue into some tasks for Grafana.
