### ISSUE TITLE
Show broken links in network management

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1443]
### Motivation
We want a centralized overview of broken links.

### Proposed Solution
Show the broken link checker in the network management. Add a column that shows how many regions are affected by the broken link. The table should be sortable by occurrences and region.

**Comment by MizukiTemma** [comment]
This feature helps OKR key resul tracking and finding links that affect multiple regions negatively. Therefore moved out of backlog.

**Comment by MizukiTemma** [comment]
Probably better to implement after #2539 and #2516

**Comment by MizukiTemma** [comment]
Not blocked anymore as #2539 was merged.
