### ISSUE TITLE
Use short URLs for internal content links

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#1448]
### Motivation

When pages are moved in the page tree, internal links do not work anymore

### Proposed Solution

When inserting links to internal pages in the content and short urls are enabled, use them as link targets instead of the normal slug-links.

### Alternatives

When moving a page, replace all links in the content to reflect the new structure

### Additional Context

One caveat: When short links are used, this makes replacing them very hard, which contradicts:
- #1383

**Comment by MizukiTemma** [comment]
See also: https://chat.tuerantuer.org/digitalfabrik/pl/qjnrbg5jwbrpuxrgbfk4gunarh

**Comment by svenseeberg** [comment]
But don't we just need the slug of the page that is the last part of the URL/path?

**Comment by david-venhoff** [comment]
Pr #2403 replaces short urls with slug urls, so using short urls internally does not make sense anymore.
