### ISSUE TITLE
Link to single POIs in the same way as (internal) pages

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1455]
Possibly a topic to disucss between app and cms team: POIs should be selectable (and converted into the right url) in the same way as internal pages.

**Comment by timoludwig** [comment]
This already works and the CMS links to `https://integreat.app/<region>/<language>/locations/<slug>/`.
@f1sh1918 do you think you could change the link scheme of the app accordingly? At the moment it seems to be `https://integreat.app/<region>/<language>/locations?name=<slug>` which does no follow the URL naming scheme for pages and events.

**Comment by timoludwig** [comment]
This will be solved by a redirect on the webapp server, see https://issues.tuerantuer.org/browse/INFRA-225
