### ISSUE TITLE
Simplify the DeepL translation process for events & locations

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1459]
### Motivation

The procedure right now is as follows:
Publish an event. go to another language, choose the option, translate using deepL for available languages.
It would be easier to have the possibility to do it immediately after creating an event.

### Proposed Solution

Copy the solution for pages from #1875 for Event and POIs

### Additional Context

Depends on:
- [x] #1875

**Comment by osmers** [comment]
Could we just use the same process as for pages? Like you can add a check mark if you wanna translate the event into all available languages? Or the pop-up idea to be able to choose the languages. Though I heard pop-ups are not that popular...

**Comment by timoludwig** [comment]
@osmers I agree, I would put this on hold until #1875 is implemented and then copy the solution from there.

**Comment by osmers** [comment]
@timoludwig just not sure if that works, bcs what if I do not want all languages? The check box works for the pages, bcs we are only translating Aktualisierungsübersetzungen. For events it would almost always be an Initialübersetzung. And then we'd have no  way of choosing the languages, right?

**Comment by timoludwig** [comment]
@osmers what do you think of just creating initial translations for all missing translations which are supported by DeepL?
So in order to "exclude" one language from the initial translation, one would have to
1. Create the event without ticking the checkbox
2. Create all translations which should be done manually and not via DeepL
3. Save the default translation again with the checkbox checked to create all missing translations automatically?

**Comment by osmers** [comment]
Assuming that for some languages they might not want a translation at all, neither machine nor human, is there any way to do that?

**Comment by osmers** [comment]
Bcs I think that if there are languages that they'd want translated by a human, they can also add that (replace the machine translation) afterwards. It is more the case where they do not want any translations for specific languages. Not sure, how relevant it is...the case I could imagine is that it is an event directed at a specific group of people, thus only their language should be translated (plus maybe English?!)
