### ISSUE TITLE
Hide Status in the Broken Link checker

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1460]
### Motivation

The Status under the broken link checker is confusing. Sometimes it just says "Fehler", sometimes it says "Forbidden". It is probably better to hide the status in the broken link checker.

### Proposed Solution

Hide the Status in the broken link checker

**Comment by dkehne** [comment]
Only the "Status" coloumn should be moved into expert mode. If this is not possible, just remove the Status for all users.
It is not understable without technical knowledge.

**Comment by dkehne** [comment]
@maxammann had some ideas which status we might ignore - e.g. if anchor is wrong.
currently the broken link checker might be to sensitive of W3C-conform-problems

**Comment by dkehne** [comment]
we just want to have broken links that lead to the fact that users are not able to access to content behind the link. all other technical problems are no real broken links for users.

**Comment by maxammann** [comment]
I think should differentiate between:

* Temporary Error (Gateway Timeout, Service Unavailable)
* Permanent Error (404)
* Warnings (someone reported that there are "broken links" which are not really broken
