### ISSUE TITLE
Change flags of Farsi and Arabic

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1470]
After we had the discussion of using non-political flags (which cannot be assigned to one state) already in 2016 i would recommend to use the same flags for FA and AR as in WordPress.

Media files are downloadable there.

**Comment by timoludwig** [comment]
You mean this one, right?
![ar](https://user-images.githubusercontent.com/16021269/169854377-8a68684b-1d0e-4a0a-ab4d-9d6a17b1d1ec.png)
Do you know where we would find it as svg?
