### ISSUE TITLE
Add a role without page editing permissions

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1494]
### Describe the Bug
The page-pased feature is sth. we were already used to in WordPress. Users can be granted access to only single pages within the system. The feature worked as a restriction, so that only pages are allowed to be seen and edited, which are granted by the page-based-permission.

E.g. Mr. X from the Jobcenter only wants to see and edit the Jobcenter and Agentur für Arbeit-pages. So his user role will be Redaktion or Autor (depending on if he can directly publish) and then he will be granted to the two pages. Then he only sees these two pages and can edit them.

Currently the page-based feature is not combinable with the user roles and only use-ful in combination with Terminplaner, because the feature grants access to pages, where not access exists yet.

**Comment by svenseeberg** [comment]
In order to use the per page editing permissions, we need a user role that has no page editing permissions in general. This role can then be assigned to users that should only be able to edit a few pages.

**Comment by MizukiTemma** [comment]
Should the page-based permission be achived by organisation ferture or literally per-page independet of organisation?

For the example of Mr. X from the jobcenter, if he is added to organisation "Jobcenter" he gains permission to the pages which belongs to the organisation "Jobcenter".

**Comment by timoludwig** [comment]
> Should the page-based permission be achived by organisation ferture or literally per-page independent of organisation?

Both should be possible - via the orga and via page-based-permissions. Both features are already implemented, but not really useful if all users already have the editing permissions. Thus, we want to add another role which is not allowed to edit pages which makes them automatically eligible to be used with the individual permissions levels.

**Comment by MizukiTemma** [comment]
Ok. And I've found the per-page permission grant system 🙂
