### ISSUE TITLE
Remove formatting when content is pasted into tinymce editor

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1501]
### Motivation

At the moment, formatting is preserved when texts are copied from e.g. word or websites into the tinymce text area.
Only `Strg + Shift + V` removes the formatting, but not all users know about this.

### Proposed Solution

Also remove the formatting when `Strg + V` is used

### Alternatives

Add the possibility to modify the font and size in the editor

### Additional Context

If possible, preserve links in the content.

**Comment by osmers** [comment]
The alternative is not very preferable since it would destroy uniformity in the Integreat App
