### ISSUE TITLE
Hide links on archived pages in broken link checker

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1502]
### Motivation

When broken links are on archived pages, they are less meaningful and can be ignored.

### Proposed Solution

Remove links on archived pages from the broken link checker. We have to evaluate which of the following is more reasonable and efficient:
1. Leave the link objects in the database but filter them in the database query and do not show them in the list
2. Whenever a page is archived, delete all corresponding link objects. On restoring, we have to call save() on the page translations as well to make sure the links are being created again.

**Comment by osmers** [comment]
If the effort is low, then I would consider this high priority bcs we have explicitly told the Kommunen that they should have very few broken links. As long as broken links on archived pages are shown, they have no overview of how many links really are in need of fixing!

**Comment by osmers** [comment]
Not sure, but I think we need to open this up again. In Dachau for example I found some links on archived pages that show up: https://admin.integreat-app.de/stadtdachau/analytics/linkcheck/invalid/
See Quelle interpreter/translator

**Comment by timoludwig** [comment]
That's unfortunate :cry:
We have to do further research to tell whether this is actually a problem of the code or some kind of follow-up problem caused by our inconsistent production database.

**Comment by timoludwig** [comment]
I could verify that this is directly happening when scanning the links.
I ran the link scanning on the production system again and afterwards, many links were found in archived pages:
```
In [1]: from linkcheck.models import *

In [2]: Link.objects.filter(page_translation__page__explicitly_archived=True).count()
Out[3]: 25554
```
So something with this filter seems to be wrong:
https://github.com/digitalfabrik/integreat-cms/blob/a0b389f3d28f8c66ba152ec52246cd244bf93433/integreat_cms/cms/linklists.py#L50-L53

**Comment by timoludwig** [comment]
Ok, I found out the problem during the findlinks command on the prod system: We use a [wrapper around the cli](https://git.tuerantuer.org/DF/salt/src/commit/3c454b47af43c656789bf69346b2326252f2fe97/states/integreat-cms/files/integreat-cms-cli) which did not pass the environment variable `LINKCHECK_EXCLUDE_ARCHIVED_PAGES` to the actual management command.
So the rest of this task remains an infrastructure ticket.

**Comment by osmers** [comment]
@timoludwig somehow broken links in archived pages and past events are showing up again: https://admin.integreat-app.de/kreishoexter/analytics/linkcheck/ignored/
We put them on ignore, but can you have a look nonetheless?

**Comment by timoludwig** [comment]
@osmers I think I found the potential problem: #2303
I'm going to close this issue for now and hope there is really nothing else going on.
