### ISSUE TITLE
Sometimes no broken links found after cloning region

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1513]
### Motivation
After a region has been cloned, sometimes the analytics section does not show broken links.

### Proposed Solution
Find out why they are not automatically created

### Alternatives
manually starting the process

### Additional Context
If #1383 is being implemented as well, the search should be triggered after the links have been updated.

**Comment by timoludwig** [comment]
If I create enough translations with many links, I can reproduce this behavior (not that there are no links at all, but that there are links from outdated versions - and if these do not contain links at all, I might also reproduce the behavior described in the issue).
It is indeed some kind of race condition between the post save signals and the creation of new translation elements.
