### ISSUE TITLE
Incorrrect format of region aliases in API

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1514]
### Describe the Bug

The region aliases should be returned as JSON objects, not as JSON string.

### Steps to Reproduce

Go to https://admin.integreat-app.de/api/regions/

### Expected Behavior

The region aliases should be objects

### Actual Behavior

The region aliases are a JSON string

**Comment by steffenkleinle** [comment]
Thanks :tada:
