### ISSUE TITLE
Set all pages to draft when duplicating region

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1517]
### Motivation

When a region is cloned, the content needs to be reviewed before it is usable

### Proposed Solution

When a region is cloned, all pages of the new region should be set to draft.

**Comment by dkehne** [comment]
@timoludwig we have discussed internally and we do not need the bulk action BUT we would like to have the behaviour that after a duplication (of an instance) all pages are on "draft"-status.

**Comment by dkehne** [comment]
prio medium-high if not much effort.
