### ISSUE TITLE
Update button text incorrect in side by side view

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1520]
### Describe the Bug

When a page/event/location is already published, the publish-button should be called "Update" instead of "Publish".

### Steps to Reproduce

1. Go to the side by side view
2. See incorrect button text

### Expected Behavior

Update

### Actual Behavior

Publish

**Comment by lucky-chap** [comment]
Will do that @timoludwig

**Comment by timoludwig** [comment]
@lucky-chap could you give a bit more information? Which OS are you using, what's the output of `command -v python3.9` and `python3.9 --version`?

**Comment by timoludwig** [comment]
Ok, and which OS? I guess you can remove this check temporarily:
https://github.com/digitalfabrik/integreat-cms/blob/25f64a41e03c819d812bd4bfe2e8209043055084/dev-tools/install.sh#L14-L16
And hopefully no other problems arise.

**Comment by lucky-chap** [comment]
Gonna try that. And I'm on Windows 11

**Comment by lucky-chap** [comment]
Now it's telling me to install pipenv for python3. version 2018.10.9 or later. I have done that but still not working. Dunno what's wrong.

**Comment by timoludwig** [comment]
Sorry, the dev-tools are more or less targeted at unix-based systems. Are you using the windows subsystem for linux?
If not, you can try to install the dependencies manually without pipenv and the dev-tools, but we don't have documentation for this unfortunately.
