### ISSUE TITLE
Specify error message for double slugs

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1521]
### Motivation

It is not possible to manually change the page-slug to a slug that is already existing. Right now, we are only showing some a successful message and just revert the slug, which results in confusion.

### Proposed Solution

Add an error/warning message to signal that this slug is already used and a new slug was taken.

### Additional Context

![grafik](https://user-images.githubusercontent.com/15608678/171428633-e354f75c-56a0-43cb-b90f-c015a323187c.png)

**Comment by timoludwig** [comment]
> If I understand correctly, we must showing an error message if the slug already exists.

An error is maybe a bit much (since the page was successfully saved), but a warning would be good, yes.

> And propose a new slug to the user.

No, the new slug is automatically set during the clean method, so no need to change this. Just tell the user that the slug was taken and to which value it was automatically changed.

**Comment by timoludwig** [comment]
For more context information about this issue, see #1646
