### ISSUE TITLE
Push news translations in main language not sent

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1526]
### Describe the Bug
When a push notification is sent with the mode "Use main language if no translation is available", no translations beside the main language get sent.

### Steps to Reproduce

1. Go to New
2. Enter a notification text and title in the main language
3. Select the "Use main language if no translation is available" mode and send the notification
4. Look into the log file and observe that only one notifications (main language) has been sent, but no other translations

### Expected Behavior
Notifications in all translations should be sent.

### Actual Behavior
Because the form for all other translations is empty, no translation object is being created. However, during the sending process, the [`load_secondary_pnts` method](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/views/push_notifications/push_notification_sender.py#L59) iterates over all existing translations. Therefore, no additional notification besides the main translation is being sent.

### Solution
Iterate over all language tree nodes of the region, then check for an existing translation. If no translation exists, create a new PN translation and save the text to the database as well.

**Comment by timoludwig** [comment]
> Solution
>
> Iterate over all language tree nodes of the region, then check for an existing translation. If no translation exists, create a new PN translation and save the text to the database as well.

Instead of saving the German text to all languages and create dummy translation objects in the database, we could also change the sending function to send the German translation for other languages as well without saving the content to the database.
We just have to think about whether we want the dummy translations in the API response as well - in this case, we'd need to create temporary translation objects in the api similar to what we do for fallback translations for events and POIs:
https://github.com/digitalfabrik/integreat-cms/blob/a5787fd1df20e1e3f19a7bc5f075f5ad5653f837/integreat_cms/cms/models/abstract_content_model.py#L213-L227

**Comment by svenseeberg** [comment]
> We just have to think about whether we want the dummy translations in the API response as well - in this case, we'd need to create temporary translation objects in the api similar to what we do for fallback translations for events and POIs:

I guess we want that. Would you still dynamically create the content instead of just saving the source language for all other languages?

**Comment by timoludwig** [comment]
> I guess we want that. Would you still dynamically create the content instead of just saving the source language for all other languages? I think there is a bigger chance of problems in the future with that approach. Having the translations in the database feels sort of safe to me.

I'm unsure, creating the objects dynamically would have the advantage that only the German version needs to be fixed when there is e.g. a typo, and also it's more consistent with our other models, where we also create the fallback translations dynamically. Maybe we can reuse this code or generalize our models in a way that this works for push notifications in the same way it does for events and POIs...

**Comment by svenseeberg** [comment]
Generalizing is a little difficult. The generalization would have to branch into 2 options immediately. We probably don't want to push messages with a text that hints towards other languages :D

**Comment by svenseeberg** [comment]
The root cause for the original issue is that we're not saving translations without a title and text. But the sender later iterates over the saved translations to send messages.

I think we should do the following:
1. If no messages should be sent in other translations, then we should not save empty messages to the database.
2. If the source language should be used for translations, then empty objects should be saved to the database.

We can then use the fallback translation functionality in the second case and not show any messages in the first case. I also think it is a good idea to actually store empty objects in the database. The cost is extremely low. On the other hand we can reference IDs and know which translations were actually sent (without looking into logs).
