### ISSUE TITLE
Improve error messages when duplicate translation imported via XLIFF import

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1530]
### Describe the Bug

When a zip file is uploaded which contains multiple XLIFF files for the same page, all these files will be imported with the same version number, which breaks database consistency.

### Steps to Reproduce

1. Export page as XLIFF
2. Copy file and create zip archive
3. Upload file
4. Open page revision view
5. Infinite redirection loop
6. See error on next "normal" page

### Expected Behavior

The import should fail with an error message

### Actual Behavior

The import succeeds with duplicated translation versions

**Comment by MizukiTemma** [comment]
Is this solved by #1993 ?
