### ISSUE TITLE
Cyrillic PDF export breaks table of content

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1532]
### Describe the Bug
When exporting a PDF with multiple pages in Ukrainian or Russian, the table of contents is missing text:

![image](https://user-images.githubusercontent.com/15197000/172596483-961d8484-01dd-48f7-8293-430582a0d0fd.png)

### Steps to Reproduce

1. Go to a region that contains Cyrillic content
2. Select more than 1 page and hit the PDF export
3. See the problem in the screenshot above

### Expected Behavior
Cyrillic letters should be displayed in the ToC as well.

### Actual Behavior
Cyrillic letters are not displayed in the ToC.

**Comment by timoludwig** [comment]
@MizukiTemma I noticed that you're working on this - however, there is PR #1661 open at the moment that replaces the PDF library, maybe this issue isn't relevant afterwards.
So I suggest to keep this issue on hold - if you want to work on the PDF export, maybe you can assist @jonbulz with the remaining problems of that PR?

**Comment by MizukiTemma** [comment]
@timoludwig thank you for the message, I haven't noticed that 😅 
I'll then leave this issue once.
