### ISSUE TITLE
Inline Icons in PDF export broken

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1537]
### Describe the Bug
When using icons within a line of text, the PDF export creates a white bar across the icon/image with the height of the text line. If the icon itself has about the height of the text, then the icon is mostly invisible. See https://integreat.app/testumgebung/de/alltag/information as an example.

### Steps to Reproduce

1. Create a page with an icon at the beginning and another in the middle of a line of text.
2. Save the page and export a PDF
3. See that the icon at the beginning of the line is fully visible, while the icon in the middle is partially hidden:
  ![image](https://user-images.githubusercontent.com/15197000/172789546-d0350844-5b54-435b-bc8f-8634c1891a6d.png)
### Expected Behavior
Icons/images should be visible regardless of their position in text.

### Actual Behavior
Only images at the beginning or outside of text work as expected.

### Additional Information
I guess that this is a bug in https://github.com/xhtml2pdf/xhtml2pdf/

**Comment by charludo** [comment]
I've found the issue: in [this xhtml2pdf file](https://github.com/xhtml2pdf/xhtml2pdf/blob/master/xhtml2pdf/default.py) on line 403, setting the background color (any background color, doesn't matter the value - color, transparent, none,...) makes inline-icons disappear.

There's certainly some deeper underlying issue, the question is, is it worth looking into? We could simply use a version of this default css without that line.
