### ISSUE TITLE
Mirrored page preview shows "undefined" as content

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1541]
### Describe the Bug

I don't really know if this is a problem of our live system and it's hard to reproduce, but from time to time our preview shows just an "undefined" as a text if we mirror a page form another region.

### Additional Information

I am guessing that this might be a special case where we can select pages that have no public PageTranslation or the page is archived. We should probably go through the whole process and see where this undefined is coming from...

**Comment by JoeyStk** [comment]
Bug couldn't be reproduced anymore
