### ISSUE TITLE
Add banner for test systems

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1547]
### Motivation

Sometimes, it can be dangerous to mix up the test and prod systems.

### Proposed Solution

- Add new `TEST` setting independently from `DEBUG` mode
- Also support reading this setting from environment variables
- When this setting is `True`, add a test banner at the top of the screen

### Additional Context

Just for reference, e.g. PyPI does it the following way:

https://pypi.org/
![Screenshot 2022-06-14 at 10-42-58 PyPI · The Python Package Index](https://user-images.githubusercontent.com/16021269/173534875-d68e4533-ea2d-47cd-8c57-1a413ea8906a.png)

https://test.pypi.org/
![Screenshot 2022-06-14 at 10-43-15 TestPyPI · The Python Package Index](https://user-images.githubusercontent.com/16021269/173534871-4e50b2e2-9949-4ec5-b08d-8e78cf5c25b2.png)

**Comment by steffenkleinle** [comment]
@timoludwig the text of the banner is not 100% accurate, the content of test cms is not visible in our beta versions. It is only visible in webnext/dev releases of the native apps.

**Comment by timoludwig** [comment]
@steffenkleinle ah ok, that's unfortunate. The banner should reduce confusion, not add to it. Do you want to open an issue and suggest a different wording?

**Comment by steffenkleinle** [comment]
@timoludwig done
