### ISSUE TITLE
Select region icons from region media library instead of global media library

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-cms#1578]
### Motivation

We have the option in the settings of a region to add an icon which is then included on a pdf-download from the web-app. If I add this now it is part of the global media library and is shown in all municipalities. Doing that for all 80 municipalities would be really annoying to the municipalities. 

### Proposed Solution

Add the icon in the option settings without it being saved to the global media library but stored seperately. 

### Alternatives

I think, you will find a good solution for that. 

### Additional Context

I do not know how urgent that is as I have not heard any complaints about it so far and I just noticed it when I tried to do it for hallo aschaffenburg.

**Comment by svenseeberg** [comment]
I think it would be better to have the logos in the global media library and allow hiding directories from region users.
