### ISSUE TITLE
Old content was migrated to Django CMS

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1586]
We have just discovered published content in the Germany template that should no longer be there.

It's about this page of the DE template: https://integreat.app/deutschlandvorlage/de/arbeit/studium-2
The content of the page was (just looked again in cms.tuerantuer.org/wp-admin) completely deleted by Clara on May 13, 2019. 

However, since the migration, the previous revision by Anne  dated April 25, 2019 is present. The version of Clara no longer exists in the Django CMS. I'll be happy to create an issue for you. It would be important to find out the cause and to check if this affects other pages.

**Comment by dkehne** [comment]
I found a similar problem in the imprint of LK Karlsruhe, which was published only with an arabic title in german (by a deleted user changed in january 2020).

**Comment by svenseeberg** [comment]
As this is a content problem, this ticket is moved to https://issues.tuerantuer.org/browse/INFRA-246

**Comment by dkehne** [comment]
the page kept existing but the whole content was removed. so "completly deleted" is not the best description. i meant "content was removed, without deleting the page"
