### ISSUE TITLE
Duplicating "LK Karlsruhe" to a new instance leads to Gateway timeout

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1594]
### Describe the Bug
After using LK Karlsruhe as template the duplication process causes a gateway timeout (see attached screenshot)

![Unbenannt](https://user-images.githubusercontent.com/4182469/178478896-29a4e253-e946-4149-b72e-6f3702adea60.PNG)

**Comment by dkehne** [comment]
@svenseeberg can we increase the timeout-time?

**Comment by svenseeberg** [comment]
Done.
