### ISSUE TITLE
Page Form Action Tabs Collapse

### ISSUE THREAD

**Issue by membralala** [digitalfabrik/integreat-cms#1595]
### Describe the Bug

On a smaller screen the action tabs in the page form collapse. 

### Steps to Reproduce

1. Go to any page form.
2. Watch on a smaller screen/browser window or zoom in.

### Expected Behavior

The action tabs should scale with the screen size (see the correct behaviour e.g. in the event form).

### Actual Behavior

The action tabs do not scale but collapse and overlap. 

### Additional Information

<img width="1278" alt="Bildschirmfoto 2022-07-14 um 11 31 33" src="https://user-images.githubusercontent.com/66683622/178951438-b8674e22-8740-4731-8625-d910b893be5a.png">

**Comment by DaRuOrg** [comment]
Seems already been fixed. Tested with Chrome and Firefox:
![grafik](https://user-images.githubusercontent.com/84681164/184510647-5f33d1a1-d795-4b22-802e-4e405f32e524.png)
