### ISSUE TITLE
Ignore missing default translations in translation coverage

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1596]
### Motivation

When the translations in the default language are either "in review" or "draft", the translation status is considered "missing".
This is confusing in the translation coverage view, since we only want to know how many translations need to be translated by professional translators, not how many pages need content revisions.

### Proposed Solution

Ignore missing translations in the default language in the translation coverage view.
These translations should also be ignored in all other languages and not counted as missing/outdated words.

**Comment by dkehne** [comment]
Please speak to UI/UX to solve it useful. I like the idea more of Timo, than dropping of the source language or put in any more text. 
it should be self-explaining...

**Comment by svenseeberg** [comment]
> it should be self-explaining...

It always should be. It never is, and we need to discuss how to get there.
