### ISSUE TITLE
Minor edits are published when saved as draft

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1622]
### Describe the Bug

When a page is
- marked as minor edit and
- saved as draft

the current and all past versions are made public

### Steps to Reproduce

1. Go to the page form of a page
2. mark as minor edit
3. Save page as draft

### Expected Behavior

When a page is saved as draft, it should actually be saved as draft

### Actual Behavior

The page is made public

**Comment by svenseeberg** [comment]
I did not notice this edge case while testing :-/ This needs to be fixed before we can deploy #1620. I'll look into this issue.

**Comment by svenseeberg** [comment]
So before I start fixing this, I want to document the different states and their transitions:

- If a version is the first version, it can (obviously) never be minor.
- If a change is a minor edit, the translation status should not be changed. That basically means that it keeps being outdated, if it was outdated before. If it acts as a source for another language, then the other language should stay up to date.
- A minor change has no influence on the translation status.
- The translation status is calculated based on major versions. If the major version of a translation is newer than the source, it is up to date. If it is older, it is outdated.
- The fact whether a translation version is draft or public has no influence on the translation status.
- The history should not change (??).
-
