### ISSUE TITLE
Push Notifications get sent even if the form validation fails

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1631]
### Describe the Bug

If a user tries to send a push notification with a wrong form (e.g. too long text) the form throws an error, but the pn gets send anyway.

**Comment by JanErikHuehne** [comment]
I am not able to reproduce this behavior. When the text is too long the form indeed throws an error. But in this case a push notification sender is never created. This is the case with the PN given in #1641. What seems like a bug is, that the length of the html text box does only display 249 characters while the form throws an error with 253 characters. I´m guessing that this results from the 3 special German characters inside the text. If the counting / encoding of the form and the sending message differs, it might occur that an invalid message is send. Do you have an example where the message is invalid but it is still send?

**Comment by svenseeberg** [comment]
I agree. This sound rather unlikely. The code is pretty clear here: https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/views/push_notifications/push_notification_form_view.py#L214 (especially the if and elif before the else).
