### ISSUE TITLE
Statistics numbers don't add up

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#1635]
### Describe the Bug
When downloading the statistics numbers from the cms, the numbers in all columns don't add up to the total shown in the total column.

### Steps to Reproduce

1. Go to 'Kreis Bergstraße'
2. Click on 'Analyse.'
3. Select a timeframe of a few months
4. Set 'Auswertung' to 'monatlich'
5. Download as csv
6. Add up the rows minus the total column
8. See error

### Expected Behavior
Total column and added up individual cells show the same value

### Actual Behavior
They show a different value

### Additional Information
![image](https://user-images.githubusercontent.com/64901227/184635082-41e52c8c-6cdf-449a-b6f6-9df20fbe87c3.png)

**Comment by svenseeberg** [comment]
I think the problem here is that the numbers per language are filtered by the `/pages/` subpath, while the total number is not filtered by that. That means that the total amount probably also includes events etc.

**Comment by svenseeberg** [comment]
Okay I think I found the issue, which is probably hard to solve and always existed: The problem comes from the method of Matomo to count unique visitors. In some cases the requests from multiple users are combined into one unique visitor, for example when by chance the random IP is the same.
