### ISSUE TITLE
Enable dynamic linking to fallback translations

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1639]
### Motivation

As duplicated content objects are only existing in the default language (e.g. german), our user are only able to link the default translation. This should be updated dynamically to link to their other "fake" translations.

Also the links don't get suggested when you try to use the linking mechanism in the TinyMCE. This should be changed.

Note: This is only required for "real" fallback translations where the content is really copied (so for events and locations). For pages, the fallback mechanism is only a placeholder to list the available languages, so it would not make sense to link to them I guess. But maybe it should be possible to link to the default translation of those?

**Comment by seluianova** [comment]
@ulliholtgrave hey Ulli, could you please describe the use case (reproduction steps) and expected result to better understand the problem?
What do you mean with "duplicated content objects" ?

**Comment by ulliholtgrave** [comment]
This refers to the fallback translations that are for example used for events or [POIs](https://github.com/digitalfabrik/integreat-cms/blob/8236701962221b2fe437b04b9af5985eff7b2a75/integreat_cms/cms/models/pois/poi.py#L130). These objects aren't translated for most of the time, but we still want them to appear in the app. Therefore, we kinda "fake" them and return the default translation if there is no translation for a specific language.
However, this behavior isn't covered by our linking functionality in the TinyMCE. That means that you can only create links to existing translations but our fallback translations are skipped. 
In reality this means that our user are editing a page in e.g. french but always have to link to the german POI if there are no french translations available. 
As a solution we should add this fallback translation for our link suggestion to stick with the same language.
