### ISSUE TITLE
Moving page to first level from "detailed page view" does not work. 

### ISSUE THREAD

**Issue by FritjofK** [digitalfabrik/integreat-cms#1660]
### Describe the Bug
In the CMS of VernetztesObdach I tried to move a page from a lower "level" (a children page) to the first level while being on the detailed page view. 

Drag and Drop from lower level to first level on the Page Tree View does(!) work. 

### Steps to Reproduce

1. Go to any childre page to "Reihenfolge" 
2. Click on "Übergeordnete Seite"
3. Select "---------------------" and click on "Aktualisieren"
4. No error message, but confirmation is shown, but the page stays at its previous spot. 

### Expected Behavior
Move the page to first level and once selecting it also show all pages on the first level to order it in the desired place. 

### Actual Behavior
No error message, but confirmation is shown indicating that it worked, but the page stays at its previous spot. 

### Additional Information

CMS of VernetztesObdach which sometimes is behind in releases. I did not test it in Malte nor Integreat. 

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by timoludwig** [comment]
This was closed in #1662
