### ISSUE TITLE
Set filesize limit for uploads to 3MB

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#1684]
After we have discussed in the service team, please set the filesize limit for uploads again to 3MB.

**Comment by devbazregari** [comment]
may I contribute to this repo?
in which folder you've set your upload code?

**Comment by timoludwig** [comment]
@devbazregari Sure, thanks a lot! :rocket: 

These are the relevant files:

Model: [MediaFile](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/models/media/media_file.py)
Form: [UploadMediaFileForm](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/forms/media/upload_media_file_form.py)
View: [upload_file_ajax()](https://github.com/digitalfabrik/integreat-cms/blob/8343fcd7ccbb6547f732c0d639c38826047fcc64/integreat_cms/cms/views/media/media_actions.py#L129-L176)

And the URL to test everything out in the end is http://localhost:8000/media-library/

Let me know if you have any further questions!

**Comment by devbazregari** [comment]
sure. I give it my best to try solve this issue.

**Comment by devbazregari** [comment]
bro why i get this error " /usr/bin/env: ‘bash\r’: No such file or directory "   when i write this command ./dev-tools/install.sh ?

**Comment by timoludwig** [comment]
Don't you have bash installed? Our dev setup is mostly targeted at Linux users, so if you're developing under Windows, we suggest the Windows subsystem for Linux.
If you're already using Linux, I would need a bit more information to try to debug the problem.

**Comment by devbazregari** [comment]
I'm using wsl2 ( ubuntu) and installed all the dependencies. 
and I'm in bash when writing this command " /usr/bin/env: ‘bash\r "

**Comment by devbazregari** [comment]
bro let's skip running the application in my OS. if your logic of uploading files works. I've written a limit-size file function that could implement what you want. do you want me to add it  to your project ( I've tested it on my app and it worked )

**Comment by timoludwig** [comment]
> I've written a limit-size file function that could implement what you want. do you want me to add it  to your project ( I've tested it on my app and it worked )

Sure, you can open a PR and I will test the functionality on my machine.

**Comment by timoludwig** [comment]
> bro why i get this error " /usr/bin/env: ‘bash\r’: No such file or directory "   when i write this command ./dev-tools/install.sh ?

A [quick Google search](https://stackoverflow.com/questions/18172405/getting-error-usr-bin-env-sh-no-such-file-or-directory-when-running-command-p) indicates that this might be a problem of the line endings in Windows vs Unix...

**Comment by devbazregari** [comment]
thank you bro . so I'll do it. 
thank for the advice.
