### ISSUE TITLE
Add CircleCI check for changelog format

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1689]
### Motivation

The changelog is parsed by the following dark magic bash command:
https://github.com/digitalfabrik/integreat-cms/blob/9bc0251e90f312e80ed39226924b7993678d3790/.circleci/config.yml#L366
which requires exactly one line after the version heading and two new lines after the bullet points.

### Proposed Solution

Add a script which checks the format in CircleCI

### Alternatives

Improve the bash command to handle more changelog formats

**Comment by timoludwig** [comment]
It's quite a common problem that the changelog entry does not end up in the unreleased section after rebasing, so we should definitely add a check for this as well.

**Comment by david-venhoff** [comment]
Not sure if it is worth the effort in our case, but I found this solution interesting where every changelog entry got its own file: https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/

**Comment by timoludwig** [comment]
Yes, this is exactly the idea I had in mind when creating #1763.
Also not sure, but if we count all the developer hours which are spent with conflict resolution, maybe it will pay off in the long term :smile:
