### ISSUE TITLE
Add API usage documentation

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1690]
### Motivation

At the moment, we only have the [API developer documentation](https://digitalfabrik.github.io/integreat-cms/ref/integreat_cms.api.html) and the [outdated API usage documentation from Wordpress](https://github.com/digitalfabrik/cms/wiki/REST-APIv3-Documentation).

### Proposed Solution

Add an updated version of the API usage documentation with all new fields etc.

### Additional Context

Also think about whether it is possible to use some kind of automated tool for this, so we don't have to update the documentation manually every time a field changes.

**Comment by PeterNerlich** [comment]
Potentially interesting literature: https://www.django-rest-framework.org/topics/documenting-your-api/

**Comment by timoludwig** [comment]
@PeterNerlich We'd have to rewrite our API using the django rest framework in order to be able to use its automatic documentation feature.
But yes, this could be less work than writing an automated generator for our custom API ourselves :sweat_smile:

**Comment by david-venhoff** [comment]
I have experimented a bit with the django rest framework and I think that our current api cannot be converted to it well.
I uploaded a branch with some wip changes in case we decide to revisit it again at some point: [feature/django_rest_framework_api](https://github.com/digitalfabrik/integreat-cms/tree/feature/django_rest_framework_api)
