### ISSUE TITLE
Fallback translations with a single language tree node

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1711]
### Describe the Bug
It seems that fallback translations create weird results if a region only has a single language tree node. In one example the german language listed the german language as a fall back translation:

![image](https://user-images.githubusercontent.com/15197000/191770268-191d740a-a0fb-4eac-a818-7188faf071b0.png)

### Steps to Reproduce

1. Create a region with a single language
2. Create two empty pages and use one as live content for the other
3. Open page that contains live content and see the message in the screenshot

### Expected Behavior
The page should (probably??) be empty without fallback translations.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by osmers** [comment]
Not sure what the question here is but yes, the page should be empty if there are no languages available that are not also the same language, the user is using in that moment

**Comment by osmers** [comment]
@JoeyStk what is the question here? Or can the question label be removed?

**Comment by JoeyStk** [comment]
@osmers I remember that there was a question that came up during our grooming on the first conference this year. I think the question was more general on how this actually is supposed to look like, but I don't remember exactly anymore. My suggestion would be to remove the label and see at a later point if maybe there is more requirement engineering needed :)

**Comment by david-venhoff** [comment]
Since we don't show fallback translations for empty mirrored pages anymore I think we can close this issue.

**Comment by MizukiTemma** [comment]
I agree with @david-venhoff
