### ISSUE TITLE
Region form locked if SUMM.AI incorrectly enabled 

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#1725]
### Describe the Bug

There seems to be a small issue with the summ.ai and hix fields in the region form, because if one of these fields is enabled and then the summ.ai api or the textlab api get disabled, it becomes impossible to change any value in the region form. 
This is because the values are required to be set to `False` if the apis are not enabled, however it is impossible to change these values to False.

### Steps to Reproduce
1. Enabled Textlab api 
2. Enable Hix for a region
3. Disable Textlab api
4. Try to change any value in the region form for this region

### Expected Behavior

No error message shows up

### Actual Behavior

An error message shows up and the changes in the form don't get applied

**Comment by timoludwig** [comment]
Is this really a bug on the develop branch? Otherwise I would suggest that we just fix this on the hix branch...

**Comment by david-venhoff** [comment]
I was not sure whether to open an issue or to just fix it on the hix branch. I decided to open an issue since this also affects the summ ai option, which is already on develop. Of course I could just fix it on the hix branch if you think that is better

**Comment by timoludwig** [comment]
I would argue it depends on whether this bug exists on develop or not.
If you're able to reproduce this with only the summ ai option, then it's a valid ticket.
If this problem only exists in the combination of the two fields on the unmerged branch, I think we should just fix this before merging it (so that the problem never reaches the develop branch).

**Comment by david-venhoff** [comment]
Okay. To clarify, this problem exists on develop right now, with the summ ai option.
