### ISSUE TITLE
Build page tree for new section "Translations"

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1727]
### Motivation
Since HIX is more or less implemented now, we should extend the MT via DeepL to pages. So far it's only implemented for events and POIs.

### Proposed Solution

- [x] Build page tree template which is the base for the new translation interface
- [x] Add menu item but make it hidden (only visible in DEBUG mode) until the follow-up issues are finished and the view is completed

### Additional Context
This is part of the issue family to enable automated translations

![base-page-tree](https://user-images.githubusercontent.com/16021269/204845635-b7b4da5c-0331-453e-842b-b73affdc77bd.png)
— [Source](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=166%3A1980)

The following issues are blocked by this issue and are follow-up issues:
- [x] #1923
- [x] #1924
- [x] #1925

**Comment by svenseeberg** [comment]
We discussed this yesterday: there are not many use cases for this additional view. We may not need it. Cities will probably need a "bulk translate everything" once. After that, pages will simply be auto translated when being edited/updated in the source language.
