### ISSUE TITLE
Feedback can only be sent for translated Events

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-cms#1743]
### Describe the Bug
When creating a event which only has a German translation, I cannot send feedback to the e.g. Spanish event page, that duplicates the content in the German language.
Instead the request fails.
In the frontend we are not able to determine the default language of an event therefore we should be able to send feedback for the non-default languages.

### Steps to Reproduce

`curl -X "POST" "https://cms-test.integreat-app.de/testumgebung/es/wp-json/extensions/v3/feedback/event" -d 'slug=sprach-cafe-im-fußball-stadion&comment=asdf'`

### Expected Behavior
Should successfully create feedback.
`curl -X "POST" "https://cms-test.integreat-app.de/testumgebung/de/wp-json/extensions/v3/feedback/event" -d 'slug=sprach-cafe-im-fußball-stadion&comment=asdf'`

### Actual Behavior
Request to default language is successful:
`curl -X "POST" "https://cms-test.integreat-app.de/testumgebung/de/wp-json/extensions/v3/feedback/event" -d 'slug=sprach-cafe-im-fußball-stadion&comment=asdf'`

404 NotFound for spanish:
`curl -X "POST" "https://cms-test.integreat-app.de/testumgebung/de/wp-json/extensions/v3/feedback/event" -d 'slug=sprach-cafe-im-fußball-stadion&comment=asdf'`

**Comment by sarahsporck** [comment]
The same also goes for POIs.

**Comment by timoludwig** [comment]
Thanks a lot for the report! :+1:
Is this essentially the same problem as #1718?

**Comment by sarahsporck** [comment]
Yep. Didn't see this one. 👍🏼
