### ISSUE TITLE
Show chapter for internal link suggestions

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1752]
### Motivation

When adding an internal link via tinymce and use the suggestion feature to link to existing content, sometimes the titles are ambiguous.

### Proposed Solution

Indicate the whole chapter path of the suggestion here:
![Screenshot 2022-10-12 at 11-11-50 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/195302907-168e58dd-9e69-48e0-8449-ef77036175d0.png)

e.g. similar how we do it for embedding live content:

![Screenshot 2022-10-12 at 11-15-20 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/195303328-0a769667-ecd9-4d44-9a08-a9b987ccd23a.png)

### Additional Context

Maybe the popup needs to be resized to fit longer nested chapter structures

**Comment by osmers** [comment]
Could this be a good first issue? Got a call today from a Kommune who's struggeling with internal links bcs of not having unique names for pages. 
Any way that we could maybe tackle this in the not too distant future?
