### ISSUE TITLE
Disable texblock option in editor

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1786]
### Motivation

The textblock option creates various problems within the PDF generation process due to additional div elements. Therefore, It should be deactivated in the editor.

**Comment by seluianova** [comment]
Could you please clarify what exactly you mean by "textblock option" ? 
Is it this menu item?
![image](https://user-images.githubusercontent.com/115008338/200934606-0a38e94e-162a-4bba-9020-0eb0bd15689c.png)

**Comment by ulliholtgrave** [comment]
Exact. We would like to remove this "Blocks" section entirely.
