### ISSUE TITLE
Mark POI category as no visible in app

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1806]
### Motivation

As the app is not using our POI categories right now, we should inform our users about it.

### Proposed Solution

Just use the same solution we had for our contact Form (see https://github.com/digitalfabrik/integreat-cms/pull/1565)

**Comment by seluianova** [comment]
Didn't you mean different link in the description?

**Comment by timoludwig** [comment]
> Didn't you mean different link in the description?

Maybe he meant: https://github.com/digitalfabrik/integreat-cms/pull/1565 or #1608?
