### ISSUE TITLE
Remove short description field from POI model

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1807]
### Motivation

The service team requested to remove the short description field from the POI model as the app doesn't use it.

### Proposed Solution

Remove the "short description" field from:

- POIForm
- POI model
- POI-API

**Comment by timoludwig** [comment]
Can we use the information which is already entered in this field as meta-information?
In other words, instead of removing the field, can we also rename it to `meta_description` and solve issue #522 partially with it?

**Comment by timoludwig** [comment]
> However, I would then move the field within the form. Right now it's pretty present next to the title and maybe we could think of some kind of "SEO section" beneath the whole content section.

Sounds good! And make the field optional, of course.
