### ISSUE TITLE
Rename client APIs to allocate them

### ISSUE THREAD

**Issue by Gaston69** [digitalfabrik/integreat-cms#1826]
### Motivation
The Client APIs (e.g. deepl_api, gvz_api ...) should be renamed to api_client_name (api_client_deepl, ...) to allocate them together in the file-tree. 

### Proposed Solution
To avoid deep nesting of files, it is not wanted to move all client api to a separate folder. Having a equal naming at the beginning will help us get a clearer structure w/o nesting.

**Comment by timoludwig** [comment]
Our [internal channel vote](https://chat.tuerantuer.org/digitalfabrik/pl/6xuwe9bwqpfwpnq9urxpdkxxjw) has shown that there is a preference for the current naming scheme `<service>_api`, so we're not going to change anything.
