### ISSUE TITLE
Move translation report to new menu section

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1830]
### Motivation
Redesign the translation area

### Proposed Solution
- [ ] Create new section "Translations"
- [ ] Move translation report to "Translations" Section

### Additional Context
This is part of the issue family to enable machine translations
![Screenshot 2022-11-30 at 17-57-44 Figma](https://user-images.githubusercontent.com/16021269/204860313-bb686147-73e3-4794-89c5-721cb396323c.png)

**Comment by timoludwig** [comment]
@nikolahoff Was it intended that the translation budget is embedded on both the management section and the translation report? In my opinion, this makes it a bit harder to grasp the information of the translation coverage view and thematically better fit into the management section?

![199998483-7540200e-a349-4df5-b7fb-29d5fc201a17](https://user-images.githubusercontent.com/16021269/204851928-c6fc7ecb-c2e2-47a2-bf3d-866ba69e1df1.png)
![usage-dashboard](https://user-images.githubusercontent.com/16021269/204851943-e6ad94f8-0f7e-4571-a956-4837ed1683f5.png)

**Comment by timoludwig** [comment]
@digitalfabrik/ui-ux-team Also, one thing I didn't understand: Should this be a new translation report just for machine translations, or should the existing translation report be moved to the new section?

**Comment by osmers** [comment]
> so I'd vote for keeping the current state and close this issue.

Just don't forget to add the extra translation status we are creating (robot) to the translation report

**Comment by timoludwig** [comment]
> Just don't forget to add the extra translation status we are creating (robot) to the translation report

Ok, I'll mention this in  the corresponding issue for the icon itself: #1883
