### ISSUE TITLE
Migrate firebase API from legacy to v1

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#1853]
### Motivation

At the moment, we use the [legacy fcm endpoint](https://firebase.google.com/docs/cloud-messaging/http-server-ref), but [v1](https://firebase.google.com/docs/reference/fcm/rest) was released quite a while ago and seems more future proof.

### Proposed Solution

- Follow [this guide](https://firebase.google.com/docs/cloud-messaging/migrate-v1) to migrate the api client

### Alternatives

Even though the API is called "legacy", I'm pretty sure it's still very commonly used and won't just suddenly disappear. I wouldn't be surprised if the legacy endpoint lives longer than our CMS.

**Comment by sarahsporck** [comment]
I'd be open to do this, but I don't have the necessary permissions, to get the new 1) projectId and 2) the new authentication token.

**Comment by timobrembeck** [comment]
maybe @svenseeberg can help?

**Comment by dkehne** [comment]
@svenseeberg what is the status here?

**Comment by svenseeberg** [comment]
The Firebase project is mainly managed by the app developers.
