### ISSUE TITLE
Cannot submit feedback for fallback translation of recurring event

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-cms#1858]
### Describe the Bug
The pathname of a recurrent event contains the date of an explicit event (in the frontend). 
E.g. https://webnext.integreat.app/testumgebung/de/events/spieleabend$2022-11-16
This pathname is provided by the backend.
However, the actual slug should not contain the date of the event. In the example above the slug is `spieleabend`. 
It is possible to remove the date from the slug in the rontend but in fact this should probably be done in the backend. Either supply the event slug in the api, or make sending feedback with the slug containing the date work.

### Steps to Reproduce

```bash
curl --location --request POST 'https://cms-test.integreat-app.de/testumgebung/ar/wp-json/extensions/v3/feedback/event' \
--form 'comment="asdf"' \
--form 'slug="spieleabend$2022-11-16"'
```

### Expected Behavior
̀Submitting feedback works:
`{"success": "Feedback successfully submitted"}`

### Actual Behavior
Submitting feedback fails with: 
`{"error": "No matching location found for slug."}`

</details>

**Comment by timoludwig** [comment]
Thanks for the report! This is essentially a combination of #1718 and #1793, so probably some conflicts between #1810 and #1811 were not correctly resolved...
