### ISSUE TITLE
Make items in the sidebar of content forms expandable and save the setting as a cookie

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1876]
### Motivation

Right now our content forms (e.g. page form) are pretty stuffed with elements and the design team is working on it. However, as a quick fix and considering the additonal SEO, HIX and AT section we want to reduce the elements ASAP.

### Proposed Solution

Make the sidebar and SEO section expandable and save the last setting in a cookie to load it if the user returns to that view.
- [x] Page form
- [x] Event form
- [x] POI form

This blocks:
- [ ] #1769

**Comment by svenseeberg** [comment]
Is this about collapsing the full sidebar (to the right) or single boxes within the side bar?

**Comment by ulliholtgrave** [comment]
I guess as we are not even showing all items to non-expert users I wouldn't really go with a role-based view.

In my opinion we should add an expandable option to all 5 boxes on the right side as some of them (e.g. Settings of the page) aren't really used that often. I wouldn't mind providing expanding on a more granular level, but as a quick fix I would start with the big boxes.

**Comment by svenseeberg** [comment]
Okay, I guess we agree that this is about collapsing single boxes.

**Comment by ulliholtgrave** [comment]
Ahh yeah, right. I misunderstood your last statement. I will adjust the title of issue.

**Comment by timoludwig** [comment]
This was fixed in #1972
