### ISSUE TITLE
API: parents endpoint

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#19]
Endpoint to get parents of a page up to the root. This must be compatible to Integreat API v3.

https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#parents-of-a-post

@maxammann @Simple-codinger is this used by any app? Otherwise we could move this to another milestone.

**Comment by maxammann** [comment]
See: https://github.com/Integreat/cms-django/issues/17

**Comment by svenseeberg** [comment]
So we decided that this is not immediately necessary as there are no plans to change the API in the foreseeable future.

**Comment by ulliholtgrave** [comment]
@klinzo Is this endpoint in any way relevant for the app anymore?

**Comment by klinzo** [comment]
@ulliholtgrave Yes, it is used in the web app and therefore absolutely crucial. Without it, the webapp won't work.
https://webnext.integreat.app/augsburg/en/work-and-education
E.g. this site https://webnext.integreat.app/augsburg/en/work-and-education uses this request https://cms-test.integreat-app.de/augsburg/en/wp-json/extensions/v3/parents?&url=/augsburg/en/work-and-education

**Comment by ulliholtgrave** [comment]
Good to know :see_no_evil:

**Comment by klinzo** [comment]
There is also a sentry report for this: https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/416/?_allp=1&query=is%3Aunresolved
