### ISSUE TITLE
Add MFA Backup codes

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1902]
### Motivation

Right now the users are able to add TOTP authentication but would require superadmins to reset their settings if they are locked out.

### Proposed Solution

We should add some kind of recovery process for our TOTP setup. For example some codes that can be downloaded by user after they setup TOTP.

### Alternatives

I guess that there are multiple alternatives and maybe some investigation is required.

**Comment by svenseeberg** [comment]
This would undermine the purpose of MFA. The only way should be another MFA method or contacting support.

**Comment by ulliholtgrave** [comment]
No longer wanted as #2257 introduces the possibility to set up an use a secondary method
