### ISSUE TITLE
Long Links in PDFs are not wrapped around

### ISSUE THREAD

**Issue by nassabay** [digitalfabrik/integreat-cms#1904]
### Describe the Bug
if a Link is longer than 1 line, it just runs over the line break

### Steps to Reproduce

1. Go to '[Kreis Soest](https://integreat.app/kreis-soest/de/corona-virus/corona-test)'
2. Click on 'PDF erstellen'
3. In the PDF Links run over the line end.

### Expected Behavior
Line break in Link

### Actual Behavior
No Link break in Link

![Screenshot (804)](https://user-images.githubusercontent.com/65529262/204301279-c11b4097-57e5-4a8b-acb6-575fbe358afc.png)

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by mael-fosso** [comment]
wo in backend kann ich zugreifen?

**Comment by svenseeberg** [comment]
https://www.w3schools.com/cssref/css3_pr_overflow-wrap.php sadly is only available with CSS 3. The module only supports CSS 2. I was wondering if we can solve this by allowing `&#x200B;` (zero width space characters) in long links as a workaround. I tried to insert them but they get stripped from the HTML code.

**Comment by seluianova** [comment]
There is a discussion on this issue:
https://github.com/xhtml2pdf/xhtml2pdf/issues/339

But the proposed property '-pdf-word-wrap: CJK;' only works for 'div' and 'p' elements.
I couldn't get it to apply to links.

**Comment by charludo** [comment]
I know this is far from ideal, but until a fix (eventually) lands in `xhtml2pdf`, could we not simply truncate links over a certain length?

E.g. turn [https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/so/forth/etc/etc/etc/etc/enough.html](https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/so/forth/etc/etc/etc/etc/enough.html) 

into either

[https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and[...]](https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/so/forth/etc/etc/etc/etc/enough.html)

or

[https://thisisaverylonglink.com/[...]](https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/so/forth/etc/etc/etc/etc/enough.html)

or even just

[https://thisisaverylonglink.com/](https://thisisaverylonglink.com/it/just/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/so/forth/etc/etc/etc/etc/enough.html)

?
