### ISSUE TITLE
Fix link escape in message in imprint form

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#1906]
### Describe the Bug

A message will be shown in the imprint form if the standard language is currently duplicated for the given language and it contains a link to the version which is shown in the app. Thogh the link is not well escaped and the tag is directly shown.

### Steps to Reproduce

1. Go to Imprint in the menu.
2. Click on the tab of a translation for which the default language is duplicated.
3. See the message on the top of the form.

### Expected Behavior

A link is shown.

### Actual Behavior

A tag is shown.

### Additional Information

![not_well_escaped_link](https://user-images.githubusercontent.com/82345046/204389202-d3e95ff6-7d71-4c38-8a36-a386df4a2089.png)

The link target is probably also incorrect. It doesn't make sense that revision 1 is shown while there is no version yet for the language. (See the screen shot. No version has been yet created (and therefore the default language is duplicated) for Easy German but the message says version 1 of Easy German is shown in the app.)

**Comment by seluianova** [comment]
> It doesn't make sense that revision 1 is shown while there is no version yet for the language

So, if there is no version yet, I would guess we don't need this message at all. Do we?

Also, there is no such message for other entities (pages, pois, events).
Why do we have it for imprint only?

**Comment by seluianova** [comment]
> Also, there is no such message for other entities (pages, pois, events).

I just did some digging into the code and found that we have a similar message for pages:

`                    message = _(
                        "Currently, <a>version {}</a> of this page is displayed in the app."
                    ).format(public_translation.version)`

However if I understand it correctly, it is not reachable. Because when the last page translation is DRAFT, all previous are also set to DRAFT.
If this is correct, we should probably also remove this block of code from page view to avoid confusion

**Comment by timoludwig** [comment]
> However if I understand it correctly, it is not reachable. Because when the last page translation is DRAFT, all previous are also set to DRAFT. If this is correct, we should probably also remove this block of code from page view to avoid confusion

There are two exceptions to this rule:
1. When there are autosaves or in-review pages, not the newest version is shown the app, but only the newest public version.
2. When old revisions are restored as draft from the revision slider, only the restored version is a draft and the previous version will be still published.

We still have it on our plate to create a better UI for these kind of workflows, so in theory it should be a bit easier to work on a new state while still delivering the old state in the apps, but I'm not sure whether there is even an open ticket for it.

**Comment by seluianova** [comment]
@timoludwig now I could reproduce it, thank you!
