### ISSUE TITLE
Minor Edit checkbox should be unchecked for new versions

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#1914]
### Describe the Bug
When saving a page as minor version, the checkbox will be set (true) for the next version. I need to actively unset the minor version checkbox. However, it should be an active choice for each version to make it a minor version. The default should always be a major version.

### Steps to Reproduce

1. Open any page and save a new minor version.
2. Reopen the page and see that the checkbox is still set to true.
3. Save again and the next version will also be a minor version. Without user interaction it should be major.

### Expected Behavior
The minor version checkbox should not be set when opening the page form.

### Actual Behavior
The minor version checkbox **is set** when the previous version is a minor edit.

### Additional Information
https://chat.tuerantuer.org/digitalfabrik/pl/3mw9t79df7gw9kydp4qnke7hya

**Comment by svenseeberg** [comment]
There is another issue that could have the same cause as this one: when importing an XLIFF file and the previous version of the target page is a minor edit, the new version created during import will be a minor version as well.

**Comment by timoludwig** [comment]
@svenseeberg I'm very sorry, I accidentally pushed to develop :see_no_evil: 
Could you review my solution retrospectively? :sweat_smile: 
1de4c06d07f80141c587a9290ea8e69c78417e7d

**Comment by svenseeberg** [comment]
Yeah, this will definitely prevent the checkbox from being checked - unless the setting is overwritten in a later stage again ^^
