### ISSUE TITLE
Add new design to automatically translate a page into selected target languages

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1923]
### Motivation
We want to enable automatic translations for pages, combined with a new design. With this issue the [translation page tree](https://github.com/digitalfabrik/integreat-cms/issues/1727) should be extended and the option to automatically translate a page into one target language should be introduced.

### Proposed Solution
Add option to translate a page into one or more target language following the new design.
On clicking into the selection field, a multi-select dropdown should open with checkboxes (?) for each language.

### Alternatives
None

### Additional Context
This issue depends on #1727

![language](https://user-images.githubusercontent.com/16021269/204845945-9c70cb96-57ae-4911-99a7-cdc447d22bd1.png)
— [Source](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=166%3A1980)

| Selection | Translation | Confirmation |
| --- | --- | --- |
|  ![Screenshot 2022-12-01 at 16-11-27 Figma](https://user-images.githubusercontent.com/16021269/205088909-b5427b03-61d0-47af-bec2-65e997599615.png) | ![Screenshot 2022-12-01 at 16-12-00 Figma](https://user-images.githubusercontent.com/16021269/205089027-6de913fb-6683-4551-9798-f9b6fb5421e2.png) | ![Screenshot 2022-12-01 at 16-12-14 Figma](https://user-images.githubusercontent.com/16021269/205089073-65311f23-125e-4c25-8da8-d5190cef2e58.png) |

**Comment by timoludwig** [comment]
Alright. I update the issue description. Nevertheless, since this feature is very complex, I suggest we wait until the requirements are settled between the service team and the UI/UX team before implementing this.

**Comment by osmers** [comment]
I have a meeting with Nikola today - maybe afterwards things are clearer.

**Comment by osmers** [comment]
@nikolahoff has already designed the new page tree for the translation section with the drop down for language selection - is there other information that you'd need @timoludwig ?

**Comment by osmers** [comment]
Checked with @dkehne and Nikola's design is ok - could you maybe update it in the description of the issue?

**Comment by timoludwig** [comment]
Ok, I updated the issue... But I still have a few concerns with this new design, e.g.:

- Why are there no checkboxes for each line? Is there only the possibility to translate each chapter at once, without the ability to translate two chapters or only sub-chapters/specific pages?
- Why is there exactly one language selection widget per page? I think in most cases, I want to translate multiple pages into the same set of languages, right? Isn't it quite cumbersome to select e.g. 4 specific languages for 20 different pages (so at least 100 clicks for this task)? Why not selecting one language-combination for all pages which are currently selected for translation? Am I missing something, or is this really the desired workflow?

I mean we can surely implement this approach and improve on it later on, but please be aware that these are complex changes and we will waste a lot of time if we implement something that isn't usable in the end.

**Comment by osmers** [comment]
As far as I understood the design, it's exactly the same page tree as under pages and for each page you can choose the languages - you are right that if I want to translate multiple pages into the same languages, it is really cumbersome. I discussed the same with Daniel and basically we'd need a bulk action for that (which I thought already exists/is planned?). Also, if we add a new language, there should be a bulk action somewhere to translate all pages/selected pages to the new language. 

The use I see for this translation section is that I can quickly check the translation status of all pages and then select for each page, which languages need to be updated. Sometimes the status is quite messy. 

E.g. here: 
![image](https://user-images.githubusercontent.com/64901227/217268700-00fa132c-85c7-4e79-b9cc-2722cfddd635.png)

It's not always all the same languages for all pages.

I think the cases we will have are (in the order of occurence):
- the update of already existing translations (via the page form)
- translation of new page into all/selected languages (translation section)
- translation of all pages into a newly added language (bulk action)

**Comment by osmers** [comment]
@timoludwig just talked to @JoeyStk and I think now I know what you mean with the check boxes - you are right, I think those need to be added
