### ISSUE TITLE
Add functionality to automatically translate a page to all available languages 

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#1924]
### Motivation
We want to introduce the option to translate a selected page in all available languages via DeepL. For that we need both a checkbox and the functionality.

This is blocked by:
- #1727

### Proposed Solution
- [ ] Add checkbox
- [ ] Add functionality to translate via DeepL to more than just one language

### Alternatives
None

### Additional Context
![multilanguage](https://user-images.githubusercontent.com/16021269/204846248-37b40b7f-335d-4ae5-b3ac-c476b2d85208.png)
— [Source](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=166%3A1980)

| Before accept | After accept |
| --- | --- |
| ![Screenshot 2022-11-30 at 17-52-54 Figma](https://user-images.githubusercontent.com/16021269/204859464-2770357b-852f-4f91-9789-20ad8f06da33.png) | ![Screenshot 2022-11-30 at 17-53-10 Figma](https://user-images.githubusercontent.com/16021269/204859474-59a50b76-256a-40c5-9857-617c7b741e4b.png) |

**Comment by osmers** [comment]
I think this issue is not needed anymore if we consider that the drop down includes the selection "all languages"

**Comment by timoludwig** [comment]
> I think this issue is not needed anymore if we consider that the drop down includes the selection "all languages"

Good point! :+1:
