### ISSUE TITLE
Add HIX column to new translation section

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#1925]
### Motivation

After #1727 is finished, we should add a HIX column to the new design and disable automatic translation for all pages with a HIX value below the threshold.

### Proposed Solution

- Add new column which shows the HIX value of the page
- Disable automatic translation and show button to improve HIX value when HIX value is below threshold

### Additional Context

![199999309-3f7982c8-5056-4382-b381-11a5fd7bab42](https://user-images.githubusercontent.com/16021269/204845037-88dcf9bf-e3d2-4b6a-b10b-f9195a0691b3.png)
— [Source](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=166%3A1980)

**Comment by svenseeberg** [comment]
I'm wondering if we actually want to show the HIX values in the page tree. I think we do not need that. Let's focus on a list of pages with the worst HIX value on the dashboards.

**Comment by svenseeberg** [comment]
We decided that we only need a new bulk action in the current tree view and a list of pages with bad HIX values in the Dashboard.
