### ISSUE TITLE
Words with Umlaute are not translated by DeepL

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#1932]
### Describe the Bug

Words with Umlaute are not translated by DeepL.

### Steps to Reproduce

1. create an event, and in its description use a word with an Umlaut
2. translate the event with DeepL
3. everything is correctly translated, except for the word containing the Umlaut

### Expected Behavior

Everything is translated correctly

### Actual Behavior

Words with Umlaute are not translated at all

### Additional Information

We are not actually sending the Umlaute, but HTML-escpaped characters. Unescaping these before sending to DeepL should fix the issue.

**Comment by timoludwig** [comment]
Fixed in #1909
