### ISSUE TITLE
Categories for Events

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1937]
### Motivation
At the dialogue forum, the suggestion was made to categorise events or to be able to categorise them. 

### Proposed Solution
Which event categories make sense? We suggest the following categories:
Ausstellungen
Bildung
Bürgerangebote & Soziales
Exkursionen & Fahrten
Festivals & Feste
Film, Kino & Theater
Konferenzen & Messen
Konzerte & Shows
Märkte
Party & Nachtleben
Religion & Spiritualität
Seminare, Kurse & Workshop
Shopping
Spielen, Quizzen & Gaming
Sport & Bewegung
Vorträge & Diskussionsrunden
Sonstiges

**Comment by timoludwig** [comment]
This is literally the exact same title as #273 - please enter the issue you're about to create at least once in the search bar to prevent multiple issues for the same topic, thanks!
