### ISSUE TITLE
Highlight pages that have not been updated for a long time 

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#1939]
### Motivation
Especially with many pages in the app, it's easy to lose track of where you have to look everywhere - especially with pages that are (supposed to be) managed by organisations - with the label, it's easier to see. Maybe you could also add a counter or something that shows how many outdated pages there are.

### Proposed Solution
The idea is to have a label for pages that have not been updated for a long time (time frame will be defined soon). UI/UX should consider how best to display this. Red flag, red background, etc - many possibilities

**Comment by dkehne** [comment]
We have decided internally that the time frame is 365 days. So after that the pages should be highlighted/marked somehow. How could the next steps (design process) look like @ulliholtgrave ?

**Comment by osmers** [comment]
We decided in the Service Team Call today that we can close this issue as it will basically be done in the new dashboard and we don't need two ways of showing these outdated pages.
