### ISSUE TITLE
Add editor shortcuts for our custom icons

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1957]
### Motivation

I noticed that it seems to be pretty easy to define shortcuts (e.g. Alt+I+1) for own functions inside the TinyMCE and I also received some feature requests by municipalities for this. As this isn't a big change and probably benefits some municipalities a lot, I would think of it as a "quick win" that we should implement rather sooner then later.

### Proposed Solution

Add the TinyMCE in-built shortcuts to our addIcon functionality. See. https://www.tiny.cloud/blog/creating-keyboard-shortcuts-tinymce/

**Comment by muddi900** [comment]
So does this mean the app should look for any un-listed icons in the svg folded and add them? Or you give users a popup to upload an svg file?
