### ISSUE TITLE
Combine recurrent events

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-cms#1965]
### Motivation
Currently the events endpoint and the apps UIs are clustered with multiple occurrences of recurring events because every occurrence is delivered as "own" event. This makes the API slow and the UI unclear and confusing for users. Additionally, this prevents the apps from connecting multiple events, for example to show the next occurrences.

### Proposed Solution
Instead of delivering every occurrence of recurring events as separate event, we could just add a new property `dates` or a similar name that can have an array with the next x (1..n) occurrences of the event as follows:
```javascript
[{
  ...
  "path": "/testumgebung/de/events/recurring-event",
  "dates": [
    { // 1st occurrence
      "start": string, // ISO 8601 date string
      "end": string, // ISO 8601 date string
      "all_day": boolean
    },
    { // 2nd occurrence
      "start": string, // ISO 8601 date string
      "end": string, // ISO 8601 date string
      "all_day": boolean
    },
    ...
  ],
  ...
}]
```

Probably a bump of the api to v4 is necessary to ensure backward compatibility of the whole api. The version of all endpoints should be bumped to make it easier for the frontends. Together with this version bump we could get rid of legacy properties/endpoints that are not used by the frontends anymore (e.g. `start_date`, `end_time`, `timezone`, `event`, `modified_gmt`, `url`...). We should probably discuss this in another call though.

### Alternatives
Deliver only the first occurrence and some kind of frequency, e.g. `weekly`, `daily`, ... While this would be possible, it would probably quite error prone and we would have to implement the logic twice (backend + frontend).  Depends on the possible frequencies event creators can set in the CMS.

### Additional Context

The following App-issue depends on this: https://issues.tuerantuer.org/browse/IGAPP-1177

### Design Requirements
None.

**Comment by timoludwig** [comment]
> ### Alternatives
> 
> Deliver only the first occurrence and some kind of frequency, e.g. `weekly`, `daily`, ... While this would be possible, it would probably quite error prone and we would have to implement the logic twice (backend + frontend). Depends on the possible frequencies event creators can set in the CMS.

I would actually prefer this solution - this would give the app a lot more freedom how to display the recurrence information, how many occurrences to show, etc.
This also doesn't mean we have to implement this logic twice - we only calculate the recurrences for the API, so if we can just pass our internal database fields to the API, we can remove our calculation code which also makes the API faster.
The model we use in the backend is [RecurrenceRule](https://github.com/digitalfabrik/integreat-cms/blob/1e7e04e6ac81be0f8542e02276919560be9a4247/integreat_cms/cms/models/events/recurrence_rule.py#L12) - the possible frequencies being:
https://github.com/digitalfabrik/integreat-cms/blob/1e7e04e6ac81be0f8542e02276919560be9a4247/integreat_cms/cms/constants/frequency.py#L18-L23
For weekly, we additionally store the week day:
https://github.com/digitalfabrik/integreat-cms/blob/1e7e04e6ac81be0f8542e02276919560be9a4247/integreat_cms/cms/constants/weekdays.py#L23-L31
And for monthly, we store the week of the month:
https://github.com/digitalfabrik/integreat-cms/blob/1e7e04e6ac81be0f8542e02276919560be9a4247/integreat_cms/cms/constants/weeks.py#L19-L25

And two additional fields:
- `interval`: "Repeat every ... time(s)"
- `recurrence_end_date`: The end date of the recurrence (optional)

**Comment by steffenkleinle** [comment]
@timoludwig thanks for explaining, then the logic is actually a lot simpler then I thought. This also means that it is not possible to have an event e.g. always on the 1st of each month, right? Instead, its always on the same weekday, same week? Do you perhaps have one or two examples how an api response would look like? Thanks! But sounds like that solution should work for us as well.

One more question: Do we also have a first occurrence field or something then? Or how would we know with the `interval` field which are the actual dates? E.g. we have `frequency = DAILY` and `interval = 2`, how would we know which days are the actual occurrences and which are skipped? Or am I missing something here?

**Comment by timoludwig** [comment]
> This also means that it is not possible to have an event e.g. always on the 1st of each month, right?

Yes, exactly. Ok, this raises one potential problem: If we decide to support more complex recurrence-rules in the future, we have to sync our development process or somehow have to find backward-compatible solutions for this (or increment the api version number each time which is maybe a bit overkill?)

> Instead, its always on the same weekday, same week? Do you perhaps have one or two examples how an api response would look like?

E.g. for an event which recurs every second week at Tuesday and Thursday:
```json
        "event": {
            "id": null,
            "start": "2030-01-31T13:00:00+01:00",
            "start_date": "2030-01-31",
            "start_time": "13:00:00",
            "end": "2030-01-01T15:00:00+01:00",
            "end_date": "2030-01-01",
            "end_time": "15:00:00",
            "all_day": false,
            "recurrence_rule": {
                "id": 1,
                "frequency": "WEEKLY",
                "interval": 2,
                "weekdays_for_weekly": [
                    1,
                    3
                ],
                "weekday_for_monthly": null,
                "week_for_monthly": null,
                "recurrence_end_date": "2031-01-01"
            },
            "timezone": "Europe/Berlin"
```
Or an event which recurs once a month on Monday of the third week:
```json
        "event": {
            "id": null,
            "start": "2030-01-21T13:00:00+01:00",
            "start_date": "2030-01-21",
            "start_time": "13:00:00",
            "end": "2030-01-01T15:00:00+01:00",
            "end_date": "2030-01-01",
            "end_time": "15:00:00",
            "all_day": false,
            "recurrence_rule": {
                "id": 1,
                "frequency": "MONTHLY",
                "interval": 1,
                "weekdays_for_weekly": null,
                "weekday_for_monthly": 0,
                "week_for_monthly": 3,
                "recurrence_end_date": null
            },
            "timezone": "Europe/Berlin"
        },
```
If it would help you with parsing, we could also come up with integer constants instead of `"WEEKLY"` etc...

> One more question: Do we also have a first occurrence field or something then? Or how would we know with the `interval` field which are the actual dates? E.g. we have `frequency = DAILY` and `interval = 2`, how would we know which days are the actual occurrences and which are skipped? Or am I missing something here?

At the moment, we store the recurrence independently from our event model, so we would always give the normal event fields for the first occurrence... (this is also what people enter in the event form - the start/end fields do not change when the event becomes recurring)

So at the moment, we also don't have any validation whether the first occurrence even matches the recurrence rule... probably we should add that :sweat_smile:

**Comment by steffenkleinle** [comment]
> > This also means that it is not possible to have an event e.g. always on the 1st of each month, right?
> 
> Yes, exactly. Ok, this raises one potential problem: If we decide to support more complex recurrence-rules in the future, we have to sync our development process or somehow have to find backward-compatible solutions for this (or increment the api version number each time which is maybe a bit overkill?)

That was one of the reason why I tended to next occurrences in the first place, otherwise this logic always has to be handled twice (or rather: the different values have to be understood by both frontend and backend). Not sure now what is the best option, I don't have experience with that kind of stuff.

>                 "weekdays_for_weekly": null,
>                 "weekday_for_monthly": 0,

Why do we need both? Can't we just do one weekdays field for both weekly and monthly with 1..x days?

> If it would help you with parsing, we could also come up with integer constants instead of `"WEEKLY"` etc...

Not needed I'd say. Weekday names should not change any time soon :D
 
> So at the moment, we also don't have any validation whether the first occurrence even matches the recurrence rule... probably we should add that sweat_smile

Definitely, yes please :pray:

**Comment by timoludwig** [comment]
> That was one of the reason why I tended to next occurrences in the first place (except less work for us smile ), otherwise this logic always has to be handled twice (or rather: the different values have to be understood by both frontend and backend). Not sure now what is the best option, I don't have experience with that kind of stuff.

Hmm. Maybe we could also agree on a fixed standard rather than implementing our own, e.g. the one from [iCalendar RFC](https://www.rfc-editor.org/rfc/rfc5545#section-3.3.10)?
There is a [python](https://dateutil.readthedocs.io/en/stable/rrule.html) and a [javascript](https://www.npmjs.com/package/rrule) implementation... Definitely more complex than what we need, but at least we avoid any misunderstandings between cms and app...

> > ```
> >             "weekdays_for_weekly": null,
> >             "weekday_for_monthly": 0,
> > ```
> 
> Why do we need both? Can't we just do one weekdays field for both weekly and monthly with 1..x days?

Yes, I'm not sure anymore why we only allowed a single weekday for the monthly recurrence... Yes, should be fine to use the same field for both.

> > So at the moment, we also don't have any validation whether the first occurrence even matches the recurrence rule... probably we should add that sweat_smile
> 
> Definitely, yes please :pray:

Done, see #1967

**Comment by svenseeberg** [comment]
Maybe we should use the iCal format, potentially "phrased in JSON"? That is an established way of communicating repeating events.

**Comment by steffenkleinle** [comment]
> Maybe we should use (or stick close to) the iCal format (https://en.wikipedia.org/wiki/ICalendar), potentially "phrased in JSON"? That is an established way of communicating repeating events.

Sounds good, we probably could parse it using [rrule](https://www.npmjs.com/package/rrule) for example. Seems like it is not necessary to phrase as JSON. Using iCal as format would perhaps also be beneficial since we don't have to generate it later in the apps but can just put the different events together for the export (or use an cms endpoint for that).

**Comment by steffenkleinle** [comment]
We decided to use iCal format for the recurrence rule now limited to the subset of rules and the part of the spec that is relevant for us. The rest of the iCal for the export will be created in the frontends.
