### ISSUE TITLE
Enable charmap plugin for unicode symbols in tinymce

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#1973]
### Motivation

Some municipalities are using special characters like ← but have to copy them from word to get them as valid unicode characters. We should encourage our user to use this symbols and provide a better integration for them.

### Proposed Solution

Activate the inbuilt charmap plugin for tinymce which includes some common unicode symbols.

### Additional Context

https://www.tiny.cloud/docs/plugins/opensource/charmap/

**Comment by mael-fosso** [comment]
the issue has already been processed
