### ISSUE TITLE
Slow loading of map endpoint

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/integreat-cms#1989]
### Describe the Bug
Loading the following endpoint takes 5-6s:

https://cms.integreat-app.de/muenchen/de/wp-json/extensions/v3/locations/?on_map=1

### Steps to Reproduce

1. Click on the above link

### Expected Behavior
Should be lower than 500ms.

### Actual Behavior
Takes 5-6s

### Additional Information
None

**Comment by timoludwig** [comment]
Short term solution could be to enable caching in Apache: https://issues.tuerantuer.org/browse/INFRA-300
