### ISSUE TITLE
Upgrade Chart.js to version 4

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2005]
### Motivation

Chart.js has a few breaking changes in 4 which have to be separately addressed when upgrading this package.

### Proposed Solution

Follow this migration guide:
https://www.chartjs.org/docs/latest/migration/v4-migration.html

### Additional Context

Also see #2003

**Comment by osmers** [comment]
Could we change the graphic of the HIX to be a Balken? So that it takes up less space in the sidebar? :)
Just like the translation report.

**Comment by timoludwig** [comment]
@osmers Yes, that's possible. If you already discussed this in the service team, please open a separate issue for this.

**Comment by timobrembeck** [comment]
Apparently, chart.js was already upgraded to version 4 in #2346, without further noticeable problems.
