### ISSUE TITLE
Links found in archived pages after cloning region

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2012]
### Describe the Bug

When a region is cloned, the link checker of the new region contains links in archived pages, even if these links were not present in the source region.

### Steps to Reproduce

1. Create region with archived pages that contain links
2. See link checker of that region which does not contain the links in archived pages
3. Clone that region to a new region
4. See link checker of the new region which now contains the links in archived pages

### Expected Behavior

The cloned region should also exclude links in archived pages

### Actual Behavior

The cloned region has links in archived pages

**Comment by JoeyStk** [comment]
Workaround: Archived pages are not supposed to be cloned
