### ISSUE TITLE
Unexpected TS error prevents page from loading fully

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2018]
### Describe the Bug

An unexpected TS error is sometimes being thrown on various pages. This error appears to block the site from loading fully, including preventing `window.addEventListener("load", ...)` event listeners from firing.

![error](https://user-images.githubusercontent.com/47758554/214045525-ea974179-a377-416b-a6af-9a52988df53e.png)

### Steps to Reproduce

1. Go to (e.g.) http://localhost:8000/augsburg/feedback/
2. Check the browser console for errors
3. it might be necessary to refresh multiple times to trigger the error 

### Expected Behavior

No error, page loads fully

### Actual Behavior

Sometimes an unexpected error prevents the page from loading fully

**Comment by timoludwig** [comment]
Wasn't this fixed in #2009? :thinking:

**Comment by charludo** [comment]
Yes! Sorry about that. The error came up in a conversation with @JoeyStk last week, and I only checked if they had opened an issue. My bad, sorry.
