### ISSUE TITLE
Visually indicate when a checkbox is disabled

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2051]
### Motivation
As a user, I want a clear indication of when a checkbox is disabled. Currently, there is no visual distinction, which can be rather confusing.

### Proposed Solution

Add the tailwind classes `bg-gray-100 border-gray-300` to disabled checkboxes.

### Alternatives

I'm not sure how much effort it is to do this in django itself. Maybe it's simpler to write a small JS script that toggles these classes?

### Additional Context

![image](https://user-images.githubusercontent.com/47758554/217029586-17c3b428-f5f8-4901-89bd-08a5c2cd17a6.png)
Current situation - one of these checkboxes is disabled, can you tell which one? 😉 

!![image](https://user-images.githubusercontent.com/47758554/217029488-3fde5dba-3b8d-473d-87e7-fb76d0f7a12f.png)
With the added classes. Much clearer IMO.

### Design Requirements

The classes are just a suggestion (copied from the tailwind docs), others might be more suitable for the Integreat color scheme.

**Comment by membralala** [comment]
> I'm not sure how much effort it is to do this in django itself. Maybe it's simpler to write a small JS script that toggles these classes?

As we are using tailwindcss, I think it would be also possible to do it with the [disabled state](https://tailwindcss.com/docs/hover-focus-and-other-states#disabled), if there are no objections?

**Comment by timoludwig** [comment]
> As we are using tailwindcss, it would be also possible to do it with the [disabled state](https://tailwindcss.com/docs/hover-focus-and-other-states#disabled), if there are no objections?

Cool idea! Then we can also add this to our [style sheet](https://github.com/digitalfabrik/integreat-cms/blob/7393f06527f0e5f6538ea8eeb2d97ac90aa0c6e0/integreat_cms/static/src/css/style.scss#L228) and don't need to change anything in the templates or JS code.

**Comment by charludo** [comment]
> As we are using tailwindcss, it would be also possible to do it with the [disabled state](https://tailwindcss.com/docs/hover-focus-and-other-states#disabled), if there are no objections?

Oh yes, that sounds like a great solution!

**Comment by JoeyStk** [comment]
Is this supposed to be for all input fields, for radio and checkboxes or is it exclusively for checkboxes?

**Comment by timoludwig** [comment]
> Is this supposed to be for all input fields, for radio and checkboxes or is it exclusively for checkboxes?

I think for radio inputs is makes sense as well, although I'm not sure whether we're even using them.
