### ISSUE TITLE
Only allow staff members to use SUMM.AI bulk action

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2065]
### Motivation

We only use the SUMM.AI bulk action in the page tree for initial translations by our team.
Thus, it should also be limited to staff members.
Region managers are supposed to translate pages in SUMM.AI via the new machine translation interface (#1727).

### Proposed Solution

- Either check `is_staff` in the bulk action view or create a new permission and assign it to the service- and cms team
- Hide bulk action for users who are not allowed to use it

**Comment by JoeyStk** [comment]
As a work-around the function was disabled, therefore this issue isn't prio high anymore

**Comment by timoludwig** [comment]
Doesn't this issue contradict our decision to cancel the automatic translation page tree (see #1727)? If we don't have the other automatic translation interface, then normal users should be able to use the bulk action, otherwise they don't have the possibility to translate at all...
