### ISSUE TITLE
Incorrect timezone for events

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-cms#2066]
### Describe the Bug
As i user i want to get the correct timezone from an event and not just "Etc/GMT+12"

### Steps to Reproduce

1. [Go to Event](http://localhost:9000/testumgebung/de/events/test-veranstaltung-f%C3%BCr-export)
2. Open network tab and check event response
3. Check timezone
4. `event.timezone: "Etc/GMT+12"`

### Expected Behavior
Timezone should be "Berlin/Europe" or "GMT+1" 

### Explanation
So we could either display add the timezone information for events for people checking events in a different timezone and for adding the timezone information for iCal export.

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by timoludwig** [comment]
We use the [IANA timezone database](https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones), is there a different standard you'd like to use?

**Comment by timoludwig** [comment]
Quoting the [iCal RFC 5545](https://www.rfc-editor.org/rfc/rfc5545#section-3.2.19):

> Note: This document does not define a naming convention for
> time zone identifiers.  Implementers may want to use the naming
> conventions defined in existing time zone specifications such
> as the public-domain TZ database.  The specification of
> globally unique time zone identifiers is not addressed by this
> document and is left for future study.

So `Etc/GMT+12` indeed seems to be a valid value for this field.
