### ISSUE TITLE
Add new section where you can add contact information

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2073]
### Motivation
We want to introduce a centralized contact database which allows maintaining contact information in one place. The contact addresses can then be embedded in pages or attached to locations.

### User Stories
- As a CMS user I want to be able to centrally manage contact information in order to minimize work when information changes
- As a CMS user I want adresses to be non-translateable without having to mark each address as "do not translate" in order to have consistency and minimal work
- As a CMS user I want the same layout incl. icons for all addresses in order not to worry about consistency
- As a user I want all addresses to be in the same format so that I can always find all necessary information in the same space

### Proposed Solution

- Add a new menu item "Contacts" next to pages and locations.
- The new view allows maintaining existing and adding new contacts.
- The contact information should be typed. The following types should be available: phone, e-mail, city, zip, street, house number, name, website
- The contact information could be merged with the existing data from POIs.
- The TinyMCE editor needs a new button to insert a contact address. It should be up to the editor to decide which kind of information should be inserted into the content.
- When a contact is being updated, pages with embedded content should be updated as well.
- Contacts should be related to POIs and events.

### Additional Context
This needs further specification

**Comment by osmers** [comment]
What kind of further information is needed? Anything we can help with?
This issue would probably solve the translations' problem we have with automatic translations translating addresses as well.

**Comment by svenseeberg** [comment]
@osmers could you please provide some user stories? :-)

**Comment by osmers** [comment]
As a CMS user I want to be able to centrally manage contact information in order to minimize work when information changes
As a CMS user I want adresses to be non-translateable without having to mark each address as "do not translate" in order to have consistency and minimal work
As a CMS user I want the same layout incl. icons for all addresses in order not to worry about consistency
As a user I want all addresses to be in the same format so that I can always find all necessary information in the same space
@karthik-integreat @nassabay @dkehne can you see if you have any other user stories for this?

**Comment by dkehne** [comment]
I would add:
- as a CMS user i want to be able to place the contact information flexibel in the content area
- as a CMS user it should be intuitive to me how i can add/remove the contact information section
- as a CMS user i want to be able to control the design (e.g. sorting of contact information [centrally configured for the region])
- as an APP user i just want to see the contact information in the text that are maintained with content / filled

**Comment by osmers** [comment]
Are there any questions remaining - should we ask Toni for UI/UX input?
With more and more languages a central contact management would make changing information easier (yes, they can simply translate a page again, but I get that for just one phone number or name it's a bit sad to use translation budget, plus the central management eliminates mistakes and makes the layout consistent) - so I would like to move the issue to a milestone within 2024. Maybe @svenseeberg @timobrembeck @JoeyStk can write any other questions they have here.

**Comment by JoeyStk** [comment]
I don't know why this issue is blocked. To me it looks like it could be worked on. Maybe we can discuss in the next grooming if we can maybe split this is up, but for now AFAIK it's good to go?

**Comment by osmers** [comment]
@JoeyStk yes, let's discuss this in the next grooming, plus maybe this issue: https://github.com/digitalfabrik/integreat-cms/issues/1878 since we can maybe combine them in some way?

**Comment by osmers** [comment]
Is this still blocked and are there still questions? Let's discuss in issue grooming today.

**Comment by JoeyStk** [comment]
![grafik](https://github.com/digitalfabrik/integreat-cms/assets/72705147/eaeeda3b-6451-48e0-ae89-79fe1aa46480)

For next issue grooming: Provide a to list with everything that needs to be done and discuss how this could be separated into multiple issues

**Comment by JoeyStk** [comment]
Blocked by the corresponding [design ticket](https://github.com/digitalfabrik/integreat-cms/issues/2863)

**Comment by MizukiTemma** [comment]
Closed as succeeded by #2955

**Comment by nikolahoff** [comment]
I have a little remark for the input of the website in the "Kontaktdaten verwalten" section. Atm it is mandatory that the user writes "http://www...." otherwise an error message occurs. Can we change it, so that it is sufficient to write the website without "http://". Thanks!

**Comment by MizukiTemma** [comment]
> I have a little remark for the input of the website in the "Kontaktdaten verwalten" section. Atm it is mandatory that the user writes "http://www...." otherwise an error message occurs. Can we change it, so that it is sufficient to write the website without "http://". Thanks! @MizukiTemma


That's a nice idea 😸 
We can probably show "https://www." like "https://integreat.app/" here and automatically prefix it at saving.
![image](https://github.com/user-attachments/assets/89cdfd9e-295c-4f41-83d6-b23280a624bf)
