### ISSUE TITLE
Expert mode: Ability to mark/umark "Ignore Textverständlichkeitsindex" on a content page

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2075]
### Motivation
Some pages deliberately have a bad HIX value, e.g. bulleted lists or pages that only contain addresses. Expert users should have the possibility to switch off the HIX calculation for a page. These pages should then not be included in the overall HIX calculation (across pages), and at the same time the page should not be translatable via DeepL.

### Proposed Solution
Checkbox on the page-detail page to mark/umark, only visible in expert mode

**Comment by seluianova** [comment]
Ability to ignore calculation of HIX value for certain pages was implemented.

> At the same time the page should not be translatable via DeepL.

Can't do this part because we don't currently use DeepL for pages.
I added this requirement into #2102
