### ISSUE TITLE
Add list of worst pages based on HIX to dashboard

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2088]
### Motivation
When a content editor logs in into the CMS even w/o a clear agenda, we immediately want users to see actionable data to improve content. Bad HIX scores are one way.

### Proposed Solution
Show a list of pages ordered by ascending HIX score on the dashboard. If the HIX value is too low for automatic translation, the page should be "highlighted" in some way, for example red font or with an additional icon. The headline of the list should also include a percentage of pages that are ready/not ready for automatic translation.

Pages marked with "ignore HIX" should be excluded from this list.

### Additional Context
* https://github.com/digitalfabrik/integreat-cms/issues/2075

**Comment by osmers** [comment]
We were thinking about a To-Do Dashboard and I think that would incorporate the HIX-value. 
Here are our ideas for this dashboard contentwise, though nothing completely set in stone yet, just wanted to share so we are all on the same page: 

Folgende Aktivitäten könnten angezeigt und von den Kommunen erledigt werden:

- ungelesenes Feedback
- Fehlerhafte Links
- Veraltete Seiten (ab 365 Tage, geht aber auch schon früher)
- Seiten liegen zur Revision liegt vor (immer als erstes anzeigen)
- Zu große Bilder bzw. Seiten mit zu großem Inhalt
- Bilder ohne Alternativtexte --> texte pflegen
- POIs ohne Kategorien
- Seiten mit HIX-Wert unter 10
- Inaktive Benutzer, die sich seit 1 Jahr nicht eingeloggt werden.
- Fehlende Icons auf der nicht-untersten Ebene

optional irgendwann erweiterbar:

- Mögliche Duplikate bei POIs
- Veraltetet Übersetzungen, die auch DeepL gemacht werden könnten wenn Budget vorhanden ist

Was nicht rein soll:

- Live-Inhalte, die sich irgendwann geändert haben

**Comment by osmers** [comment]
@svenseeberg should we create separate issues for all and then ask UI/UX to design something for the meta issue that incorporates everything?
