### ISSUE TITLE
Implement the new dashboard 

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2107]
### Motivation
We want to include a dashboard that gives an overview over todos for the municipalities. 

### Proposed Solution

Implement the design you can find following the link to Figma (or in the screenshot). 

- The link for "Seiten, die zum Review vorliegen" should be [this](cms.integreat-app.de/%region%/pages/%language%/?query=&status=REVIEW&date_from=&date_to=&translation_status=UP_TO_DATE&translation_status=IN_TRANSLATION&translation_status=OUTDATED&translation_status=MISSING&translation_status=MACHINE_TRANSLATED) (pages filtered by status)
- The link for "Unglesenes Feedback" should be [this](https://admin.integreat-app.de/testumgebung/feedback/?query=&category=&language=&date_from=&date_to=&read_status=UNREAD&rating=True&rating=False&rating=&filter=)(feedback filtered by read_status)
- The link for "Fehlerhafte Links" should be a link to the broken link section
- "Seiten mit niedrigem HIX-Wert" needs one extra step:
  - Create a new box in the analysis > translation report section. Move the HIX section (s. screenshot) from the current dashboard there. 
![grafik](https://github.com/digitalfabrik/integreat-cms/assets/72705147/703e2f9c-b62f-4555-96ba-2646f6abfa53)
  - Link to analysis > translation report
-  The link for "Veraltete Seiten" should be to pages pre-filtered for pages that are older than 365 days

### Alternatives

None

### Additional Context
(For the implementation this can be ignored for now. Implementing the five tasks as seen in the screenshot is enough for the first iteration)
The following activities could be displayed and completed by the municipalities:

- unread feedback
- Faulty links
- Outdated pages (from 365 days, but can also be done earlier)
-  Pages awaiting revision (always display first)
-  Too large images or pages with too much content
-  Pictures without alternative texts --> maintain texts
- POIs without categories
-  Pages with HIX value below 10
-  Inactive users who have not logged in for 1 year
-  Missing icons on the non-bottom level

optionally expandable at some point:

- Possible duplicates for POIs
- Outdated translations that could also be made DeepL if budget is available

What should not go in:
- Live content that has changed at some point

### Design Requirements

@hauf-toni

Link to Figma: https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=518%3A3671 - please check for the project board with the according issue id.

![grafik](https://github.com/digitalfabrik/integreat-cms/assets/72705147/1358c100-615b-4574-ba22-4f2d31dbf51f)

**Comment by osmers** [comment]
Dashboard should be divided into two columns, on the left To-Do-Dashboard and on the right Communications-Dashboard (Chat and Blog).
Translations coverage and Statistics should be included in To-Do-Dashboard - how many pages are out of date and pages which are least accessed.

**Comment by hauf-toni** [comment]
@osmers @JoeyStk the updated design is available as V2 on figma, the to-do dashboard is finished 💯 

please provide me with a screenshot of the views "pages available for review" and "pages with low HIX value", which should be accessible for users from the dashboard, so that they can also be included in the design. a better understanding for this task can be provided by viewing the design and the respective flows, thank you.

**Comment by osmers** [comment]
@JoeyStk would these be a suitable screenshot for "pages avaible for review"? 
![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/e402e68e-5a4e-4999-be2d-441b21f5e000)
Do you have one for the pages with low HIX-value? Are we making a filter available for those or what is our plan?

**Comment by JoeyStk** [comment]
@osmers yes, I think that is a suitable screenshot for "pages available for review"

> Do you have one for the pages with low HIX-value? Are we making a filter available for those or what is our plan?

Good question. I think one option would be to add a filter. One the other hand, it would be a shame to delete the overview on the HIX values that we have on our current dashboard. So I would suggest that on click on "HIX Werte mit zu niedrigem HIX Wert" the table we have on the current dashboard shows. I know this is not a great solution, but maybe it gives us at least sometime and we don't have to erase a feature which has been introduced only a few months ago :thinking:

**Comment by osmers** [comment]
> So I would suggest that on click on "HIX Werte mit zu niedrigem HIX Wert" the table we have on the current dashboard shows

But aren't we removing that dashboard? Should we maybe move it to the analysis section?

**Comment by JoeyStk** [comment]
@osmers Do you mean move the section from the dashboard to the analysis section and then link from the new dashboard to that section?

**Comment by osmers** [comment]
Yes, I think that makes the most sense, bcs we did agree that the current HIX dashboard is only temporary, till we have the full dashboard, right?

**Comment by JoeyStk** [comment]
Sounds good to me

**Comment by hauf-toni** [comment]
Link to source file: https://nextcloud.tuerantuer.org/index.php/f/4338814

**Comment by JoeyStk** [comment]
Since the design process is completed we can work on this issue now
