### ISSUE TITLE
`DeepLException` during MT for languages with faulty bcp tag 

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2116]
### Describe the Bug
If you try to use the MT for languages with a faulty bcp tag Django errors occur. This issue is quite relevant, because in our live system quite a few bcp codes are filled out "incorrectly", and therefore we would run into a lot of issues when releasing our implementation in April.

### Steps to Reproduce

1. Go to ''languages" and create a language that a. instead of the bcp tag uses a slug and b. create another language that has an incorrect bcp tag
2. Then click on 'event' or 'locations', ǵo to either one of the newly created languages
3. Select pages and use the bulk action for machine translation
4. In both cases, see the error 
![grafik](https://user-images.githubusercontent.com/72705147/224963832-05dd6e2e-8df1-40c1-8a60-1240969928e5.png)

### Expected Behavior

Even in cases where instead of the bcp code the slug is filled in the translation should work. And for cases in which the bcp code is filled in incorrectly (e.g. pt_PT instead of pt-PT) there should be an informative error message.

### Actual Behavior

In both cases that I described above a django error message appears (see screenshot)

### Additional Information

The underlying problem is probably that we check the language slugs when testing for DeepL availability, but when we're actually translating we're sending the bcp tag. This error also appears while using the translation box in our page form, introduced by #2062

**Comment by timoludwig** [comment]
I could only reproduce this bug for English and Portuguese:
https://github.com/digitalfabrik/integreat-cms/blob/c6a29e4ef0c73ec29641f468b0aabb7b60825ad2/integreat_cms/deepl_api/utils.py#L150-L154

For all other languages, the bcp tag is not used during DeepL translation, right?
