### ISSUE TITLE
Add integration test for DeepL feature

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2136]
### Motivation

In order to provide a stable machine translation feature, we should add tests for DeepL, similar to [like we did for SUMM.AI](https://github.com/digitalfabrik/integreat-cms/blob/develop/tests/summ_ai_api/summ_ai_test.py).

### Proposed Solution

1. Make the DeepL API URL configurable
2. Pass the settings url to the DeepL client (see [docs](https://github.com/DeepLcom/deepl-python#server-url-configuration))
3. Add a mocked server which returns the same response format like DeepL
4. Change the config in tests to use the mocked server and test all DeepL features:
    - Checkbox in page form
    - Bulk actions in event & location list

### Alternatives

Fingers crossed :crossed_fingers:

**Comment by seluianova** [comment]
I faced 2 issues:

1. Supported source and target languages for DeepL are not loaded in tests because of this condition, which is not met:
`if "runserver" in sys.argv or "APACHE_PID_FILE" in os.environ`

2. CMS loads supported languages at start-up. This means that the mocked server must be running before it.

**Comment by timoludwig** [comment]
> I faced 2 issues:
> 
>     1. Supported source and target languages for DeepL are not loaded in tests because of this condition, which is not met:
>        `if "runserver" in sys.argv or "APACHE_PID_FILE" in os.environ`
> 
>     2. CMS loads supported languages at start-up. This means that the mocked server must be running before it.

What do you think about patch the `ready()` function of the deepl app in tests similar to e.g. [here](https://github.com/digitalfabrik/integreat-cms/blob/ee43b2a357ce74fb29b7232d6590bb5a84a8fdb0/tests/core/management/commands/test_reset_deepl_budget.py#L30)?
I think we can set the supported target languages to a fixed list in tests - we don't want to interact with the real DeepL API...

**Comment by seluianova** [comment]
> we don't want to interact with the real DeepL API

I assumed we want to do it through the mocked DeepL API. But to implement it in such way, the mocked server should be started before the CMS.

> What do you think about patch the ready() function of the deepl app

In this case we won't cover the load of supported languages.
I guess I can just set them directly then:
`apps.get_app_config("deepl_api").supported_source_languages = ["de"]`

**Comment by timoludwig** [comment]
@seluianova very strange indeed :thinking: 
Unfortunately, I don't have an idea what could cause this... :unamused: 

I also don't know where the date is coming from, in theory the bulk action should only modify the translation objects and not the content objects. I don't see a place where `Event.end` could be reset to a naive local datetime during DeepL translation...
Maybe, if events are the only problem, we can start with tests for pages and POIs and think about events later?

**Comment by seluianova** [comment]
> could be reset to a naive local datetime during DeepL translation...

It actually works that way even before the DeepL translation

> Maybe, if events are the only problem, we can start with tests for pages and POIs and think about events later?

I believe we can :)
