### ISSUE TITLE
Improve load time of children endpoint

### ISSUE THREAD

**Issue by SteffiStuffel** [digitalfabrik/integreat-cms#2169]
### Describe the Bug
https://cms.integreat-app.de/augsburg/en/wp-json/extensions/v3/children/?depth=1
needs more than 2 seconds to load

### Steps to Reproduce

request https://cms.integreat-app.de/augsburg/en/wp-json/extensions/v3/children/?depth=1
with postman or with the browser

### Expected Behavior
should need less than 500ms

### Actual Behavior
needs 3s

**Comment by timoludwig** [comment]
@SteffiStuffel Do you have other ideas for optimizations? Otherwise, I would just open a PR with this change, should be a pretty significant improvement already.

**Comment by SteffiStuffel** [comment]
> @SteffiStuffel Do you have other ideas for optimizations? Otherwise, I would just open a PR with this change, should be a pretty significant improvement already.

Thanks for taking care of this. I would have checked the insights, why this request needs a lot of time and fix it depending on the result. So fine for me how you suggested.
