### ISSUE TITLE
Secondary buttons look exactly like disabled buttons

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2170]
### Describe the Bug

The "preview" and "save as draft" buttons are grey to separate them from the "publish/update" buttons.
However, this has the disadvantage that they look exactly like disabled buttons.

### Expected Behavior

It's ok to separate them from the "main" button by a separate color, but grey is a bad choice

### Actual Behavior

They look disabled

### Additional Information

![Screenshot 2023-03-27 at 14-06-20 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/227937065-59dbd78d-a472-42b1-8719-1c1d047b8e81.png)

For the "preview" button I think it  could make sense to use the same color as for filters (since the meaning of the light blue could be described as "something that has no immediate influence on the state of the system"):
![Screenshot 2023-03-27 at 14-07-07 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/227937194-11fa55cf-5f3e-4c09-b5fa-ff2b03e191ae.png)

For "draft" this isn't ideal however, since it changes the database and the click itself cannot be reversed.

**Comment by seluianova** [comment]
As an option - make the disabled button lighter + gray text?
![image](https://user-images.githubusercontent.com/115008338/227980757-95cb818e-e61f-4e22-8fca-22b3bb9496b6.png)

**Comment by timoludwig** [comment]
@digitalfabrik/ui-ux-team do you have input on this?

**Comment by JoeyStk** [comment]
I know my opinion isn't really asked here, but I like outline and ghost-buttons as secondary buttons
![grafik](https://user-images.githubusercontent.com/72705147/232540155-8eca4c23-ebe5-4426-9c84-b73082484773.png). I think if we only have two levels of hierarchy I would go for outline buttons, if we have more than two I would go for ghost buttons

**Comment by hauf-toni** [comment]
> @JoeyStk Cool idea! If we don't get a response by the UI/UX team, I think we can go ahead and implement this guideline:
> 
> ```
>         &.btn-ghost {
>             @apply bg-blue-100 text-blue-500;
>             &:hover {
>                 @apply bg-blue-200;
>             }
>         }
>         &.btn-outline {
>             @apply border-2 border-blue-500 text-blue-500 bg-white;
>             &:hover {
>                 @apply bg-blue-100;
>             }
>         }
> ```
> 
> ![Screenshot 2023-04-17 at 20-11-46 Integreat Editorial System](https://user-images.githubusercontent.com/16021269/232573632-550d0c05-b14f-453b-aa2b-24034306c2f1.png)

@JoeyStk @timoludwig from an ui/ux perspective the outlined button is the best choice here, as it complies with best practice standards, see [Google Material components](https://m3.material.io/components/all-buttons) ("Use an outlined button for actions that need attention but aren’t the primary action[ ...]" 
If you tag @digitalfabrik/ui-ux-team , you can also tag @hauf-toni , this will also point me to the thread via mail. I appreciate that, thank you :)

**Comment by timoludwig** [comment]
@hauf-toni ah sorry, I thought mentioning the team had the same effect, but ok I will use the individual username in the future.
Would be cool though if we could somehow fix the notification settings, since the team name is easier to remember...

**Comment by JoeyStk** [comment]
We discussed this issue in our bi-weekly-meeting between service team, UI/UX team and our team. We came up with the following solution: 

- Secondary buttons should become outline buttons (as seen in the screenshot above)
- Buttons that fulfill a different purpose than the rest of the buttons on the page should become ghost buttons (as seen for draft in the screenshot above)
- Disabled buttons should remain grey, but if possible a less saturated grey tone (for example #A1A1AA) 
- Add styleguide / documentation for this so future developers have a guidance when making the choice

With this information the issue should be ready for implementation

**Comment by timoludwig** [comment]
@JoeyStk Sounds good, thanks for clarification!

> Disabled buttons should remain grey, but if possible a less saturated grey tone (for example #A1A1AA)

I would suggest to stick with our existing color palette, so ideally we could choose a lighter grey from https://tailwindcss.com/docs/customizing-colors
(At the moment, it is `gray-500`/`#6b7280`, so we could move to `gray-400`/`#9ca3af`)

**Comment by JoeyStk** [comment]
Yes, sounds reasonable. @hauf-toni was referring to the Integreat color scheme, but also said we were free in making the final decision of what works best for us. So let's try gray-400 then :+1:
