### ISSUE TITLE
Add global push notifications

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#2187]
### Motivation

Some users are registered for multiple regions and if they want to send a push notification for all regions, they have to click through each municipality and manually enter and send the notification. This should be made easier with a way to send a notification for multiple regions at once.

### Proposed Solution

One option would be to specify in a regional push notification form that this notification should also be created for other regions assigned to me.

### Alternatives

We could create a separate area at the network level where a notification can be created and then selected to which regions it will be sent.

### User Story

As a CMS-User, I would like to have the ability to send a push notification to multiple regions assigned to me so I don't have to click through all of them individually.

**Comment by hauf-toni** [comment]
Design proposal for this issue can be found [here](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=534%3A3488&t=uQrQNiBvokP0rtOT-1), tbd with @ulliholtgrave

**Comment by PeterNerlich** [comment]
In the model I would just modify the `PushNotification.region` to a many to many relationship for now, but how should this be handled later on in #2186 or follow up issues, when they will have to be editable at some point? E.g. if a user with permissions for only one region wants to edit a scheduled notification for also two other regions? Should he just be denied? Allowed to edit, but it actually splits it into a separate one and removes the region reference from the other one? The former sounds weird and confusing, but the latter might just result in absolute chaos, where it ever to happen.

**Comment by david-venhoff** [comment]
Another option might be to not change the push notification model and just create multiple push notifications when creating a push notification for multiple regions. That should avoid this problem
