### ISSUE TITLE
Update Django to version 4.2 LTS

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2220]
### Motivation

Django 4.2 LTS provides a few improvements, e.g.:

- Database optimizations (psycopg3 instead of psycopg2)
- Mitigation for the BREACH attack, so we can enable gzip in entire CMS without the workaround

for the full list, see [releases notes](https://docs.djangoproject.com/en/4.2/releases/4.2/)

### Proposed Solution

- Check whether we're affected by any [backward incompatible changes](https://docs.djangoproject.com/en/4.2/releases/4.2/#backwards-incompatible-changes-in-4-2)
- Check whether all our dependencies support Django 4.2

### Alternatives

The current version 3.2 LTS will be supported until April 2024, so we can delay updating for about a year.

**Comment by svenseeberg** [comment]
End of Life for 3.2 is end of Q1/2024.
