### ISSUE TITLE
Broken HIX loading animation when DeepL is enabled

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2222]
### Describe the Bug
When I open a page and the HIX widget is not loaded yet, it shows the message, that supposedly there was no content on my pages, which is not true. Usually this issue resolves itself as soon as the HIX widget is loaded, however when ever the HIX service is not available, this message stays for a while (ca. 30 seconds, before showing the error message, that HIX isn't available). This is not a huge probem, but it might cause some confusion.

### Steps to Reproduce

0. Enable DeepL by setting a key in the config file and enable HIX in the region settings
1. Go to pages
2. Select a page
3. See error in HIX box (error resolves itself as soon as the widget is loaded)

### Expected Behavior
Show an error message like "HIX widget is loading..." or something similar

### Actual Behavior

Shows untrue error message "No content on page"

### Additional Information
![Bildschirmfoto von 2023-04-11 17-08-10](https://user-images.githubusercontent.com/72705147/231209824-a72f4699-a368-4821-83de-7795e677c0d4.png)

**Comment by timoludwig** [comment]
I think this only happens when DeepL is enabled, but I did not yet have a closer look to why that is...
