### ISSUE TITLE
Make HIX page table expandable

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2229]
### Motivation

A table of pages with worst HIX values was introduced in #2088 / #2218. We show currently worst 10 pages, but the table should be now expandable.

### Proposed Solution

Add an option button (or something similar) which expands the table to show all pages ranked by HIX value when clicked by users.

### Alternatives

Leave it as it is.

**Comment by osmers** [comment]
It could be something like two "buttons" or linked texts that allow you to either show all pages ranked by HIX or show 10 more pages - not sure if the latter makes sense though

**Comment by osmers** [comment]
Perfect :)
