### ISSUE TITLE
[Obdach] POI category icons

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-cms#2270]
### Motivation
For vernetztes Obdach the we need new poi category icons.

### Proposed Solution
 Please make the new icons available via dropdown and deliver it to the fronted via api:
- advice
- daily_routine
- finance
- medical_aid
- other_help
- structure

[integreat_categories_iconset cms.zip](https://github.com/digitalfabrik/integreat-cms/files/11443922/integreat_categories_iconset.cms.zip)

### Note
Probably there is no separate implementation for icons for vernetztes Obdach, so all integreat category icons should also be available there.

**Comment by JoeyStk** [comment]
@f1sh1918 I have two questions:
1. question: 
> other_help

In our integreat categories we already have "other". Am I correct in assuming, that we don't need the separate category "other_help" anymore if you use the one from Integreat?

2. question:
What would be the best translation for both finance and structure? Would you prefer "Finanzielles" or "Finanzen", and the same for structure. Is "Strukturelles" or "Struktur" better?

Thank you in advance :)

**Comment by f1sh1918** [comment]
@JoeyStk 

1. if you check the images in the zip file you can see the differences. so one is just like "Sonstiges" and the other "Sonstige Hilfen" as the images may describe. So we should have both. I mean some may not be useful for integreat but here i'm just talking about icons and not about categories we may have in integreat. I'm even a bit confused why we have to translate icon names. I think thats not needed but looks more consistent in the ui. Afaik only administrators like us can create categories :)


2.  I really don't mind since no user will see that names. In my opinion the dropdown should just consist the icons and not names so the user would know at instant how the icon looks like

3. the existing colors are fine

thx for taking the issue :)
