### ISSUE TITLE
UTF-8 encoded ULRs in Broken Link checker

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2274]
### Describe the Bug
When entering a URL in the broken link checker, the domain part is being URL-encoded. However, domains need to be encoded with puny code. This also affects links that are encoded with punycode in a page.

### Steps to Reproduce

1. Enter a punycoded domain in a page, for example https://www.xn--bafg-7qa.de/bafoeg/de/home/home_node.html
2. Run the broken link checker
3. Look into the invalid links list and find `https://www.baf%C3%B6g.de/bafoeg/de...`
4. Replace the link with the correct punycoded URL
5. Look into the list again
6. The link is still shown with an UTF-8 encoded domain

### Expected Behavior
Use punyencoded domains in URLs in the broken link checker

### Actual Behavior
Punycoded domains are replaced with URL encoded domain parts.

### Additional Information

<details>
  <summary>Traceback</summary>

![image](https://github.com/digitalfabrik/integreat-cms/assets/15197000/9e1cd483-83a6-4f11-8e4c-2fdb3eb0eecc)

  ```
Connection Error: NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f577a06c2b0>: Failed to resolve 'www.baf%c3%b6g.de' ([Errno -2] Name or service not known)")
  ```

</details>

**Comment by sarahsporck** [comment]
Since the corresponding ticket has been fixed & released upstream updating `django-linkcheck` should fix this.

**Comment by timobrembeck** [comment]
As far as I can remember, @david-venhoff encountered an error when installing the new linkcheck version, this is why he excluded the new version during #2613.
We still have to investigate whether this is a local problem or a problem of linkcheck's packaging.

**Comment by david-venhoff** [comment]
For reference, this is the upstream issue: https://github.com/DjangoAdminHackers/django-linkcheck/issues/200

**Comment by timobrembeck** [comment]
As mentioned in https://github.com/digitalfabrik/integreat-cms/pull/2626#issuecomment-1915674677, we have a different problem besides the fixed bug in the library: Our content form converts umlauts in domains into incorrect formats:

Enter `https://www.bafög.de` in the form and inspect the source code in tinymce:

Now the link contains html entities (wtf?) `https://www.baf&ouml;g.de`

Then, click on "save", the content clean method (aka lxml) encodes the url with urlencoding: `https://www.baf%C3%B6g.de`

Both of them are wrong, the correct representation would be `https://www.xn--bafg-7qa.de` (or at least keep the utf-8 characters in the domain name to leave the punycode conversion up to the requests library)...

**Comment by timobrembeck** [comment]
I opened an upstream issue for lxml, hopefully I correctly identified the source of the problem:

https://bugs.launchpad.net/lxml/+bug/2051597

**Comment by timobrembeck** [comment]
@david-venhoff that seems like a reasonable thing to do, even if it doesn't fix this issue. I think all browsers can display utf-8 just fine, no need for html entity encoding.

Apart from that, I also opened an issue in the underlying serializer library that lxml is using: 
https://gitlab.gnome.org/GNOME/libxml2/-/issues/674
