### ISSUE TITLE
Automatically link existing POI on an event page upon creation

### ISSUE THREAD

**Issue by karthik-integreat** [digitalfabrik/integreat-cms#2277]
### Motivation

When I post an event at a location already stored in Integreat and use the map function, the location information in the event article does not link directly to the map entry.

### Proposed Solution

Upon entering the location data for an event, the location is automatically linked to the already existing POI. The users can click on the link and view the location on the map.

### User Story

As a municipality CMS user, I want the location information in the event article to be directly linked to the map entry, when the entry already exists, so that I need not enter any additional text and links in the editor form everytime.

### Additional Context

![image003](https://github.com/digitalfabrik/integreat-cms/assets/80322785/927ab5ea-194a-41f4-adbe-913bc1ea462a)

### Design Requirements

None

**Comment by timoludwig** [comment]
If you want to change how something looks in the app, please open an app issue in https://issues.tuerantuer.org/projects/IGAPP/
