### ISSUE TITLE
`TypeError` when non-staff user tries to grant page permissions

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2284]
### Describe the Bug

At the moment, an error occurs when a non-staff member tries to grant additional page permissions

### Steps to Reproduce

1. Login as "management"
2. Go to page form
3. Try to add the observer to the authors of the page

### Expected Behavior

The observer should be able to edit the page

### Actual Behavior

An error occurs:
```
May 17 10:25:10 ERROR integreat_cms.cms.views.pages.page_actions - argument of type 'ManyRelatedManager' is not iterable
Traceback (most recent call last):
  File "/home/integreat/integreat-cms/integreat_cms/cms/views/pages/page_actions.py", line 548, in grant_page_permission_ajax
    if page.region not in request.user.regions:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'ManyRelatedManager' is not iterable
```

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
May 17 10:25:10 DEBUG integreat_cms.cms.views.pages.page_actions - [AJAX] <SimpleLazyObject: <User (id: 2, username: management, role: Manager, region: augsburg)>> wants to grant <User (id: 10, username: observer, role: Observer, region: augsburg)> the permission to edit <Page (id: 21, region: augsburg, slug: alltag)>
May 17 10:25:10 ERROR integreat_cms.cms.views.pages.page_actions - argument of type 'ManyRelatedManager' is not iterable
Traceback (most recent call last):
  File "/home/integreat/integreat-cms/integreat_cms/cms/views/pages/page_actions.py", line 548, in grant_page_permission_ajax
    if page.region not in request.user.regions:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'ManyRelatedManager' is not iterable
May 17 10:25:10 DEBUG integreat_cms.cms.views.pages.page_actions - Ein Fehler ist aufgetreten. Bitte kontaktieren Sie eine:n Administrator:in.
  ```

</details>

**Comment by svenseeberg** [comment]
Good catch :+1: I only grepped for the region name and did therefore not stumble over this error message. Can/Do we want to add the request URL to all logged errors? :D

**Comment by timoludwig** [comment]
> Can/Do we want to add the request URL to all logged errors? :D

Normally, this should already be the case, I guess the problem here is that we have a generic `try-catch` of all exceptions, which caused the less verbose error log message... I guess we should fix this instead :see_no_evil: 

https://github.com/digitalfabrik/integreat-cms/blob/a1f4719f7a823374bab8c466e1b52213917a5237/integreat_cms/cms/views/pages/page_actions.py#L606-L609
