### ISSUE TITLE
Add single region endpoint

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2289]
### Motivation

The web app currently requests all regions on each request, which adds a lot of unnecessary overhead.

### Proposed Solution

Add the possibility to get a specific region by slug.
Also include the languages of that region in the request to save the subsequent request as well.

**Comment by steffenkleinle** [comment]
Please let the app team know once this is done: https://issues.tuerantuer.org/browse/IGAPP-1267
