### ISSUE TITLE
New API URL patterns not versioned

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2290]
### Describe the Bug

At the moment, we only add the version number `v3` for the legacy API endpoint patterns from wordpress, but not for the new ones.
On order for the app to migrate to the new patterns, we need to prefix them with the current version.

### Steps to Reproduce

1. Go to http://localhost:8000/api/regions/
2. See API result
### Expected Behavior

The API result should be available under http://localhost:8000/api/v3/regions/

### Actual Behavior

There is no version parameter

**Comment by steffenkleinle** [comment]
Please notify the app team once this is done: https://issues.tuerantuer.org/browse/IGAPP-1317
