### ISSUE TITLE
Add location url to event API response

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2294]
### Motivation

In theory, event locations can already be mapped to their location object via the id, but when this information is not yet retrieved by the app, it considerably slows down the loading of an event.

### Proposed Solution

Add a new property to the `location` object of the event api response (either `slug` or `url`).
I guess the url would be not completely trivial since we don't know whether the location is available in the current language, so we have to put some thought into how to handle this case. Link to the default language?

### Alternatives

Do the mapping via the `id`

Related issue:
- https://github.com/digitalfabrik/integreat-cms/issues/2277

**Comment by sarahsporck** [comment]
I think as fallback either linking to the default language or not linking at all would make the most sense. Small remark, linking to the default language could be bad UX, though.

**Comment by timobrembeck** [comment]
True, although at the moment all of our 150 regions have the "fallback translation" feature enabled for events and pois, which means that all objects are visible in all languages, even if the content is not available in some languages:

(this can be set in the region form)

![Screenshot 2023-10-09 at 15-32-45 Integreat Redaktionssystem](https://github.com/digitalfabrik/integreat-cms/assets/16021269/6f53ce96-3f26-4ff5-9155-28ec8929a517)

But from the app's perspective, there is no difference, the translations look like normal translations even if they have content in the default language. So I guess we can just use our internal translation method [`POI.get_public_translation()`](https://github.com/digitalfabrik/integreat-cms/blob/e65275995c2a1775b54e70afe49d912d530554d8/integreat_cms/cms/models/abstract_content_model.py#L254) which automatically handles this case correctly and returns a translation if it exists (or fallback translations are enabled), and no translation otherwise.
