### ISSUE TITLE
Move "Do not Translate" function from Expert mode to the normal mode.

### ISSUE THREAD

**Issue by vthejay** [digitalfabrik/integreat-cms#2295]
We motivate more and more municipalities to use DeepL for translations. However, DeepL also translates adresses. We advice the municipalities to use the Do not translate Tag to block DeepL from translating adresses.
This is especially helpful when creating content at the beginning. 
It is therefore necessary that the "Do not translate" function be moved from the expert mode to the normal mode. Right now, we need to assign all the users (also non technical users) to the expert mode. This would make it too complicated for most of the users.

**Comment by MizukiTemma** [comment]
The word "Nicht-Übersetzen-Tag" must be removed here:

![image](https://github.com/digitalfabrik/integreat-cms/assets/82345046/b499a9a8-114a-4b79-b969-424012bb7e7e)

**Comment by JoeyStk** [comment]
I spoke to @vthejay and apparently this is already resolved, and also non-experts can set the "don't translate" tag. The only thing that is left to do in this issue seems to be that the help text needs to be adjusted. Is my assumption correct or did I miss something?

**Comment by MizukiTemma** [comment]
@JoeyStk Thank you for checking 🙂  Yes, it seems `Do not translate` is now available also for non-expert users. Only the help text needs an update.
