### ISSUE TITLE
Empty pages count as "not ready for MT" in dashboard

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#2317]
### Describe the Bug

The value of "ready for MT" in the dashboard calculates the percentage of all pages with HIX above the threshold in relation to all translations.
This is incorrect since e.g. empty pages without a HIX score are allowed for MT (but do not increase the percentage in the dashboard).

### Steps to Reproduce

1. Go to a region dashboard
2. See percentage of pages that are ready for machine translations
3. Check that the percentage gets lower for every empty page

### Expected Behavior

An empty page should be considered ready for MT by default

### Actual Behavior

An empty page is calculated as "not ready for MT" in the overall percentage counter in the dashboard

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by seluianova** [comment]
In addition to empty pages, we also have pages that are not empty but do not have HIX. For example, if TextLab API returned an error.
Should such pages be considered as ready for MT or not ready for MT?

**Comment by osmers** [comment]
Maybe it would already help if we closed this issue: https://github.com/digitalfabrik/integreat-cms/issues/2296
I just had the case today that basically all pages have a HIX above 15 but the percentage says only 85% are ready for translation: https://admin.integreat-app.de/odenwaldkreis/ check the dashboard here

Maybe we can even separate it further and say: 
XX of YY pages are ready for translation. ZZ pages have no HIX value bcs they have no content. They can be translated. ÄÄ pages have a hidden HIX value and cannot be translated. 

XX = pages with HIX above 15
YY = pages with a HIX value
ZZ = pages with only a title
ÄÄ = pages with hidden HIX value

**Comment by seluianova** [comment]
> Maybe it would already help if we closed this issue: https://github.com/digitalfabrik/integreat-cms/issues/2296

@osmers yes, that's basically what we are doing.

But we use a slightly different calculation.
The message is just:
`XX out of YY pages are ready for automatic translation.`
Where:
YY = all pages with HIX enabled (including empty pages and pages with HIX errors)
XX = YY - (pages with HIX below 15)

There was a discussion about it in PR #2320, you can take a look.
