### ISSUE TITLE
Incorrect translation status after machine translation (XLIFF-exported pages)

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2318]
### Describe the Bug

Translation status of "currently in translation" pages does not transit correctly after machine translation.

### Steps to Reproduce

1. Go to a page.
2. Export the page for translation in a language for which machine translation is allowed
3. Machine translate it by bulk action.
4. See the status remains "currently in translation" with clock icon.

### Expected Behavior

After machine translation the status changes to "machine translation" (and the robot icon).

### Actual Behavior

Aftter machne translation the status remains "currently in translation" (with the clock icon).

### Additional Information

Related issue #2319

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by MizukiTemma** [comment]
It seems the problem is more generall: when Redis is activated, the icon doesn not transit qucikly (sometimes transits after a while/some other operations, sometimes remains unchanged) although the change is actually saved in the database.

**Comment by timobrembeck** [comment]
> It seems the problem is more generall: when Redis is activated, the icon doesn not transit qucikly (sometimes transits after a while/some other operations, sometimes remains unchanged) although the change is actually saved in the database.

Thanks for investigating this issue. In this case, I'd say we re-open it and make sure to invalidate the cache correctly.
