### ISSUE TITLE
Incorrect translation status after machine translation (outdated pages)

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2319]
### Describe the Bug

Translation status of "outdated" pages does not transit correctly after machine translation.

### Steps to Reproduce
Sadly I cannot reproduce this bug so far 😿 

### Expected Behavior

After machine translation the status changes from "outdated" (alert-triangle icon) to "machine translation" (robot icon)

### Actual Behavior

After machine translation the status changes from "outdated" (alert-triangle icon) to "currently in translation" (clock icon)

### Additional Information

Similar bug is reported #2318 

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by vthejay** [comment]
For example, Stadt Regensburg reported that the status of the sides (without previous translations) are saved as "Drafts" after a machine translation bulk action. For example:
The page https://admin.integreat-app.de/regensburg/pages/de/277/edit/
the translation in English was saved as Draft after the bulk action.
