### ISSUE TITLE
Add icon url to api response for poi categories

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-cms#2332]
### Motivation

In the apps we need to show the icons of the poi categories for the filter view. In order to avoid adding all the icons and having to adjust them whenever they change in the cms, a `icon_url` should be delivered as well. At the moment only the icon name/key is delivered, e.g.: 
``` json
"category": {"id": 1, "name": "Behörde/Amt", "color": "#C38E03", "icon": "office"}
```

Additionally, we don't want to add all the icons in the frontend again.

### Proposed Solution

Complete urls of the icons are added, e.g.:
``` json
"category": {"id": 1, "name": "office", "color": "#C38E03", "icon": "office", "icon_url": "https://url.to.icon/office"}
```

### Alternatives

None

**Comment by timoludwig** [comment]
In the requirements of this feature, the poi categories were supposed to be dynamic, thus we decided to manage all translations of the poi categories via the CMS.
They can be retrieved via the api:

https://digitalfabrik.github.io/integreat-cms/api-docs.html#location-categories

If required, we could also add the translations of the categories to the poi endpoint. Otherwise, I would suggest you use the numeric if for identification, since the text itself is dynamic, also the English text.

**Comment by steffenkleinle** [comment]
> In the requirements of this feature, the poi categories were supposed to be dynamic, thus we decided to manage all translations of the poi categories via the CMS.

Ahhh, super nice! Didn't know that. Yeah then nevermind, this is enough then.

How about full urls for the icons?

**Comment by timoludwig** [comment]
The icons itself are contained in the icon sprite of the app, I think @f1sh1918 mentioned that it is hard to use svgs downloaded from the CMS as map pins? Thus it makes no sense to deliver their url I think.

**Comment by steffenkleinle** [comment]
> The icons itself are contained in the icon sprite of the app, I think @f1sh1918 mentioned that it is hard to use svgs downloaded from the CMS as map pins? Thus it makes no sense to deliver their url I think.

Not sure how to use icon sprites regularly in the app. We need the icons for the filter view additionally to the use on the map, see screenshot
![image](https://github.com/digitalfabrik/integreat-cms/assets/29095487/ce3f5655-2819-4647-b80a-74b2b0def040)

**Comment by timoludwig** [comment]
Ah ok sure, we can create an additional field for the icon URLs then :+1:
