### ISSUE TITLE
Execution of replace_links.sh command removes links from the database

### ISSUE THREAD

**Issue by seluianova** [digitalfabrik/integreat-cms#2333]
### Describe the Bug
If I try to replace some link with the replace_links.sh management command, the replaced link is removed from the database.
In addition, sometimes not only the replaced link is deleted, but some other links too (which should not be affected by the replacement at all).

### Steps to Reproduce
Try to replace 'willkommen' to 'hallo' in the link 'https://integreat.app/augsburg/de/willkommen/' via replace_links.sh:
Execute command `integreat-cms-cli replace_links willkommen hallo --commit`

### Expected Behavior
The link is replaced in the content, but remains in the database and can be found in the "Broken Links" menu.

### Actual Behavior
The link is replaced in the content, but is removed from the database, so it does not show up in the "Broken Links" menu.
In addition, a few more links that do not contain "willkommen" may also be deleted (this part is flaky).

### Additional Information
The issue is reproduced for any link types (internal/external) and seems to be independent from search/replace values.
The issue is not reproduced if the replacement is done through the UI view (as far as I've been able to test).

**Comment by timoludwig** [comment]
Hmm, I cannot reproduce this issue. Also, be aware that the starting database of the test data might not be 100% consistent regarding the link objects, so it could make sense to execute
```
INTEGREAT_CMS_LINKCHECK_COMMAND_RUNNING=1 ./tools/integreat-cms-cli findlinks && ./tools/integreat-cms-cli checklinks
```
once to get a consistent baseline for the link objects. Then, perform the replacement and test whether you can reproduce this behavior. It is completely expected that link objects are being deleted, what is strange is that they are not being created again, so it could also take a few seconds until the new, replaced links show up in the broken link list (since the linkcheck signal handler runs in the background).

**Comment by seluianova** [comment]
> Also, be aware that the starting database of the test data might not be 100% consistent regarding the link objects, so it could make sense to execute [...] once to get a consistent baseline for the link objects

The result is the same for me, if I execute this command first. Here is the output:

```tory@tory-XPS-15-9570:~/Integreat/integreat-cms$ INTEGREAT_CMS_LINKCHECK_COMMAND_RUNNING=1 ./tools/integreat-cms-cli findlinks && ./tools/integreat-cms-cli checklinks
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
The script integreat-cms-cli needs root privileges to connect to the docker daemon. It will automatically be restarted with sudo.
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
Database container is already running
Updating all links...
/home/tory/Integreat/integreat-cms/.venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1358: RuntimeWarning: DateTimeField Event.end received a naive datetime (2023-07-05 00:00:00) while time zone support is active.
  warnings.warn("DateTimeField %s.%s received a naive datetime "
Urls: 0 created, 0 deleted, 7 unchanged
Links: 0 created, 0 deleted, 12 unchanged
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
The script integreat-cms-cli needs root privileges to connect to the docker daemon. It will automatically be restarted with sudo.
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
Database container is already running
Checking all links that haven't been tested for 10080 minutes.
Jul 05 12:18:20 DEBUG integreat_cms.cms.utils.internal_link_checker - Checking <Url (id: 4, url: https://integreat.app)> (type: 'empty', internal: '')
Jul 05 12:18:20 DEBUG integreat_cms.cms.utils.internal_link_checker - Marking empty link as valid
Jul 05 12:18:20 DEBUG integreat_cms.cms.utils.internal_link_checker - Checking <Url (id: 7, url: https://integreat.app/augsburg/de/willkommen/)> (type: 'internal', internal: '/augsburg/de/willkommen/')
Jul 05 12:18:20 INFO linkcheck.models - checking external link: https://www.augsburg.de/buergerservice-rathaus/buergerservice/aemter-behoerden/staedtische-dienststellen/b/buergeramt/auslaenderbehoerde
Jul 05 12:18:20 INFO linkcheck.models - checking external link: https://www.augsburg.de/umwelt-soziales/gesundheit/selbsthilfegruppen
Jul 05 12:18:35 INFO linkcheck.models - checking external link: https://integreat-app.de/
Jul 05 12:18:37 INFO linkcheck.models - checking external link: https://invalid.integreat.app/
Jul 05 12:18:37 INFO linkcheck.models - checking external link: https://invalid2.integreat.app/
2 internal URLs and 5 external URLs have been checked.
```

> since the linkcheck signal handler runs in the background

It doesn't seem to run on my machine. Do I have to enable it explicitly? Somewhere in the configuration maybe?

**Comment by timoludwig** [comment]
> The result is the same for me, if I execute this command first. Here is the output:
> 

Hmm weird, yes the output looks normal...

> It doesn't seem to run on my machine. Do I have to enable it explicitly? Somewhere in the configuration maybe?

In theory, it is enabled by default and can only be disabled by setting `LINKCHECK_DISABLE_LISTENERS` to `True`...

**Comment by seluianova** [comment]
A bit of investigation notes:

I added logging to linkcheck.listeners, but after running the replace_links.sh command it didn't produce any log entries.
(But it did when I added/edited links via UI).

After a while, however, it just started to work. 
Issue is not reproduced right now, so I'm closing the issue, but I'm still confused as to what caused it.
