### ISSUE TITLE
Handle the first version of translation as missing if auto-saved

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2387]
### Motivation

If there is no translation yet and an user starts an first translation and it gets auto-saved, ✅ appears as translation status in the page tree. This is but not completely so correct, because the saved translation is just auto-save and still in progress. In this case ❎ should be shown. 

### Proposed Solution

Handle the first version of the translation as missing and show ❎ in the tree, if it is not a manaual save.

### Alternatives

Leave it as it is.

### Additional Context

TBD:
1. Whether this behaviour should be applied for the route lanuage too.
2. Whether ❎ should be shown until the first manual save, even if there are multiple of auto save versions. Related to #2067

**Comment by MizukiTemma** [comment]
This issue may bring a kind of contradiction to #2389 

We will not show translation status of the root language anymore because it's always up-to-date. However this issue breaks such an assumption, creating cases that translation status of the root language is "missing" with no manual save yet.

Of course we can apply this issue only for non-root languages, though the behaviour is then not consistent between the root and other languages (users recognise by icons whether there is a manually saved version for translations in non-root languages whereare there is no indication about the root language) and probably causes confusion to users.

**Comment by timobrembeck** [comment]
I'm in favor of closing this issue since it also contradicts #1889.
In my opinion, the current separation of translation status and publication status makes a lot of sense, and if we create one exception now, it will become messy and even more complicated.

**Comment by timobrembeck** [comment]
We decided to close this, see https://chat.tuerantuer.org/digitalfabrik/pl/cnopratp1pn8z8yysrj3atoj4h
