### ISSUE TITLE
Do not show translation status of the root language

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2389]
### Motivation

Translation status of the root language is always `up to date`. Therefore it is not so meaningfull to show it in the content list, so let's omit it.

### Proposed Solution

Show only status of other languages (non-root).
This can be applied not only for pages but also for POI and event.

### Alternatives

Leave it as it is.

### Additional Context

![image](https://github.com/digitalfabrik/integreat-cms/assets/82345046/e0761213-b6b5-4453-a06b-ccb94199d848)

**Comment by dkehne** [comment]
Does not really makes an effort, can be done if we are bored.

**Comment by timobrembeck** [comment]
I updated my flag package with the new flag, so this issue is no longer blocked :innocent:
