### ISSUE TITLE
Add color to `Language` model

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2390]
### Motivation

Page access statistics will bring higher understandability if each language has a certain fixed color regardless of which region it is.
Currently languages receive a color in the order, which means:

If
Color order: Red, Yellow, Green, White
Region1 has: German, English, Arabic
Region2 has: German, Arabic, Chinese

Then
Region1: German-Red, English-Yellow, Arabic-Green
Region2: German-Red, Arabic-Yellow, Chinese-Green

What we want is, for example:
German-Red, English-Yellow, Arabic-Green, Chinese-White in all regions.

### Proposed Solution

Add a color field to the language model, like color in POI category

### Additional Context

This must be implemented before #1097

### Design Requirements

Which colors should be in the choice, will come from @hauf-toni

**Comment by dkehne** [comment]
Good idea, i will move it to Q1/2024 because it can wait some more weeks.

**Comment by hauf-toni** [comment]
once you are ready to implement this, you can find my color suggestion in this [file 🔴🔵🟣](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=1044%3A5&mode=design&t=lKRkQtVR9qU6NJNd-1)

**Comment by dkehne** [comment]
moved to 24Q3 because page based statistics moved as well.

**Comment by lunars97** [comment]
can I try to work on this ticket? Would that be fine?
