### ISSUE TITLE
Add field for "only by appointment" to opening hours for POIs

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2398]
### Motivation
Some POIs are only open with prior appointment - this option is so far missing when specifying the opening hours. So we should add it.

### Proposed Solution
After clicking on "edit all opening hours" there should be another check box which allows users to specify that on that day the POI is only open with prior appointment. The link for booking the appointment can then either be in the content or we implement a text field that allows websites as an input.

### Alternatives
Leave it as it is which would mean that as soon as opening hours are edited, the days with prior appointment are either shown as open or closed but not with the necessary information for users.

### User Story
As a user of the Integreat App I want to see on which days I need an appointment to go to a POI so that I do not waste my time and have all the relevant information before going.
As a user of the CMS I want to have the possibility of including this kind of opening conditions so that our users get all the relevant information and do not just show up.

### Design Requirements
Not sure if much design is needed here - maybe a decision about whether we should have the information for appointment booking in the text or within the opening hours window and how to display it in the app, if it is part of the opening hours.

**Comment by LeandraH** [comment]
@hauf-toni Do we have a plan for how this shows up in the app yet?

**Comment by LeandraH** [comment]
@hauf-toni Sorry to have tagged you in this one, I'll tag you in the app one instead 😅

**Comment by ztefanie** [comment]
@charludo Is this done? When will it approximately be deployed?

**Comment by charludo** [comment]
> @charludo Is this done? When will it approximately be deployed?

Yep, it's already been merged and live on the test server, and I assume it's going to be included in the next release.
