### ISSUE TITLE
"Paragraph/Absatz"-option missing in tinyMCE to erase a headline

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2404]
### Motivation
I received a call from one municipality because they struggled to erase an existing headline. After reviewing i saw that it is not possible to click on "paragraph/Absatz" to transform a headline into normal text because this button does not exist.

It is possible to click on the headline-button again that is currently used and then the text is transformed back to a normal text. that was not inuitive to the user.

### Proposed Solution
If there is any chance to add a "Absatz"-Button into the editor (because it is maybe available by default but we hide it?) then do so.

### Alternatives
We could add a button to remove formatting or build the "Absatz"-Button by ourself.

### User Story
The user wants to remove a headline.

### Additional Context
see screenshot.
![absatz](https://github.com/digitalfabrik/integreat-cms/assets/4182469/6eb99395-c133-40ed-b0e6-d4cf82cf833a)

**Comment by seluianova** [comment]
"Paragraph" option was removed withing this task: https://github.com/digitalfabrik/integreat-cms/issues/1786

> We could add a button to remove formatting

We actually have it.
I will move it to the center of the editor to make it more visible:
![image](https://github.com/digitalfabrik/integreat-cms/assets/115008338/00c5b065-9311-4100-bd74-09a5b856ef76)
