### ISSUE TITLE
Deliver POI title in different languages

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-cms#2417]
### Motivation
As a user i want to have the poi title displayed in my chosen language on the map. Currently only the german/standard language is delivered as poi title.

### Proposed Solution
- Due to this pr we are ready to also display RTL languages on the map (https://github.com/digitalfabrik/integreat-app/pull/2450)
- Deliver the poi title in the different languages and only use the standard language as fallback

**Comment by svenseeberg** [comment]
AFAICT we just need to remove some code that only returns the main language.
