### ISSUE TITLE
Move analysis between content and settings in side menu in CMS

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2420]
### Motivation
Analysis is important but content is what they work on daily, so we want to move the menu sub item analysis down by one

### Proposed Solution
Move analysis between content and settings

### Alternatives
keep it as it is

### User Story
As a user of the CMS I want to have the content pages as a first menu item because it is what I access most.

### Design Requirements
None

**Comment by ulliholtgrave** [comment]
I am not sure if this is really an issue as our menu is sorted alphabetically in English. This should probably decided by the UI/UX team.

**Comment by timobrembeck** [comment]
> I am not sure if this is really an issue as our menu is sorted alphabetically in English. This should probably decided by the UI/UX team.

No, the current order was just inherited from wordpress, it's not because of the alphabet.

**Comment by ulliholtgrave** [comment]
Also people are used to the current layout and moving CTA's randomly might result in some confusion

**Comment by ulliholtgrave** [comment]
> > I am not sure if this is really an issue as our menu is sorted alphabetically in English.
> 
> No, the current order was just inherited from wordpress, it's not because of the alphabet.

I know that it wasn't intentionally, but I still like it :D

**Comment by osmers** [comment]
In the service call we decided to close this issue since, as Ulli mentioned, users are used to the current layout and there is no inherent need to change it
