### ISSUE TITLE
Add spoken languages field to POI

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2421]
### Motivation
We want app users to filter POIs by languages they speak.

### Proposed Solution
Add a new multi select field for languages to the POI object and provide the information in the API.

### Alternatives
Instead of a language select, the dropdown contains only "unknown", "German", "Multilingual".

### User Story
As an app user I want to know if the languages I speak are spoken at POIs.

### Additional Context
- https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=533%3A3499&mode=design&t=lKRkQtVR9qU6NJNd-1
- Does "other languages than Germany" reallly help anyone? Example: Japanese.
- Even if someone speaks arabic: what if that person is on vacation?

**Comment by svenseeberg** [comment]
The CMS developers have doubts about the usefulness of such a feature for end users.

**Comment by dkehne** [comment]
Not neccessary after @osmers and i discussed it once more
