### ISSUE TITLE
Bad contrast for success/info/warning/error messages

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2460]
### Describe the Bug

I'm not sure if it's just me and my eyes are getting worse over time, or if the contrast really isn't ideal for success messages

### Expected Behavior

The contrast between background and text color should be appropriate

### Actual Behavior

It's a bit hard to distinguish
![Screenshot 2023-10-11 at 22-35-35 Integreat Redaktionssystem](https://github.com/digitalfabrik/integreat-cms/assets/16021269/70a3b2e5-b3b7-4283-b10b-4b76555a6abd)

**Comment by osmers** [comment]
@hauf-toni could you have a look at the contrast of these success messages? I think the question is whether we need to adjust the colors or not :)

**Comment by hauf-toni** [comment]
well seen (jokes aside) @timobrembeck :
<img width="499" alt="no" src="https://github.com/digitalfabrik/integreat-cms/assets/123894307/e0ebb4bb-f0ae-41af-a725-7064edecf2b2">
as you can see from the two screenshots, the current design does not meet the standard of 4.5:1 (at 1.6:1 it is even much lower) 
<img width="556" alt="yes" src="https://github.com/digitalfabrik/integreat-cms/assets/123894307/74dfcca0-ef57-423f-9d91-bdfbcb8e753a">
in the second screenshot you will find a suggestion for an alternative colour for the typo (#134E4A, taken from the tailwind figma kit), which at 8.6:1 more than meets the standard
if you have any questions, please let me know

**Comment by osmers** [comment]
@hauf-toni super, thanks a lot :) 
I assume we need to adjust the contrast/colors for all the success messages then - @timobrembeck should we just make that decision? And then maybe it could be moved to this quarter (Q4) since we were looking for issues yesterday that would be good first issues - @JoeyStk

**Comment by JoeyStk** [comment]
Thank you a lot for your expertise, @hauf-toni! :smile:

**Comment by timobrembeck** [comment]
@osmers yes, makes sense. :+1:

And I just checked the other types of messages, and actually all of them are below the threshold `4.5:1` (even if not quite as bad as the success messages):
- Warnings: `2,7:1`
- Info: `3,0:1`
- Errors: `3,1:1`

![Screenshot 2023-10-25 at 12-57-32 Integreat Redaktionssystem](https://github.com/digitalfabrik/integreat-cms/assets/16021269/d665c2b9-f4a8-40e8-b23a-8613c6dbfc31)
![Screenshot 2023-10-25 at 13-00-17 Integreat Redaktionssystem](https://github.com/digitalfabrik/integreat-cms/assets/16021269/207efdca-e166-4862-8796-d27ff17f4672)

So we might have to adapt them as well.

**Comment by hauf-toni** [comment]
@timobrembeck for reference, you can have a look at [these examples on figma](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=119%3A1029&mode=design&t=axTYiep59wH6pbss-1) The examples shown all correspond to the 4.5:1 standard 🎨

**Comment by timobrembeck** [comment]
@hauf-toni great, thanks! Do you know what's the easiest way to extract the tailwind color classes from the figma file?
Right now, I would do a screenshot from the figma file, check the corresponding hex code in an image editor and then compare them to the [tailwind color list](https://tailwindcss.com/docs/customizing-colors), but this seems a bit stupid :smile: 
Is there an easier way? Or could you directly write the recommended tailwind color (e.g. `green-300` or `blue-700`) into the figma file?

**Comment by timobrembeck** [comment]
> in the second screenshot you will find a suggestion for an alternative colour for the typo (#134E4A, taken from the tailwind figma kit), which at 8.6:1 more than meets the standard

I'm on board with all recommendations except the success message, since it uses the color variant `teal` instead of `green` which is the main green tone we use in the CMS. And probably it's better to use one "flavor" of green instead of mixing them, right? So I'd suggest either `green-700`/`#15803d` (contrast: `4,6:1`) or `green-800`/`#166534` (contrast: `6,5:1`) for success messages...

**Comment by hauf-toni** [comment]
@timobrembeck Both are fine with me as long as the contrast meets the accessibility guidelines 👍🏼
