### ISSUE TITLE
Can't  log in to integreat-cms (prod) "Testumgebung"

### ISSUE THREAD

**Issue by Docmale** [digitalfabrik/integreat-cms#2464]
### Describe the Bug
Trying to log in in integreat-cms production "https://admin.integreat-app.de/testumgebung/" results in an error page 403 with button "Zurück zur Starseite". This button brings me to the e2e Testumgebung. So I have no access to "Testumgebung"

### Steps to Reproduce

1. Loigging in to https://admin.integreat-app.de/testumgebung/ with my credentials

### Expected Behavior
I need access to "Testumgebung" and "Testumgebung-e2e"

![Bild1](https://github.com/digitalfabrik/integreat-cms/assets/21236324/ce8335fa-fc9d-4437-aabb-c8bee1ec3a23)

**Comment by timobrembeck** [comment]
This is not a bug, but @dkehne deleted the testumgebung and recreated it without adding all users.
I added the user "lehmann" to the testumgebung again, can you check whether this fixes your problem?

**Comment by Docmale** [comment]
Problem solved, thank you
