### ISSUE TITLE
In total calculation of "pages waiting for review" on new dashboard incorrect

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2501]
### Describe the Bug

- The "Pages that are waiting for review" link in the new Dashboard seems to be broken. Next to it, a hint "(in total x)" is shown, however when clicking on the link, no page is found (possibly due to the selected filters?)

#### Somewhat related:
- Clicking on "Pages with low HIX scores" scrolls down to the "Overview of the text understandability of the pages" box after loading the "Translation report" page, but should also expand the box in case the user has previously collapsed it.
- (optional) the "Go to Page" button is very prominent compared to the links taking you to all affected pages, possibly leading to confusion. Maybe a second, outlined button "See all" could be shown to the left of "Go to Page"?

### Steps to Reproduce

1. Go to https://cms-test.integreat-app.de/lkaugsburg/
2. See "Pages that are waiting for review (in total 17)"  in the To-Dos
3. Click the link
4. See "No pages found with this filter."

Same goes for example for [Lk Emmendingen](https://cms-test.integreat-app.de/lk-emmendingen/pages/de/?status=REVIEW) which shows 22 pages on the dashboard, but actually only has 2

### Expected Behavior

Number of pages found when clicking the link matches number of pages shown as "x in total"

### Actual Behavior

Mismatch

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by JoeyStk** [comment]
> The "Pages that are waiting for review" link in the new Dashboard seems to be broken. Next to it, a hint "(in total x)" is shown, however when clicking on the link, no page is found (possibly due to the selected filters?)

I think it's actually the other way around. The link (incl. the according filters) should be right. Instead the (in total x) is probably the source of the issue

**Comment by charludo** [comment]
> > The "Pages that are waiting for review" link in the new Dashboard seems to be broken. Next to it, a hint "(in total x)" is shown, however when clicking on the link, no page is found (possibly due to the selected filters?)
> 
> I think it's actually the other way around. The link (incl. the according filters) should be right. Instead the (in total x) is probably the source of the issue

Alright, that would make sense as well! 😄
