### ISSUE TITLE
"In total" calculation of pages with low hix value is incorrect

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2507]
### Describe the Bug

The section "pages with low hix value" also shows an incorrect "in total" calculation. For example for [LK Emmendingen](https://cms-test.integreat-app.de/lk-emmendingen/) it says, that there are 160 pages with insufficient HIX value. However if you follow the link, you'll see that indeed there are no pages with a HIX value under the threshold of 15. Similar picture for [Kreis Segeberg](https://cms-test.integreat-app.de/kreissegeberg/) and [Munich](https://cms-test.integreat-app.de/muenchen/)

### Steps to Reproduce

1. Go to [LK Emmendingen in our test system](https://cms-test.integreat-app.de/lk-emmendingen/)
2. See on dashboard there are 160 pages with insufficient HIX value
3. Click on link
4. See there are no pages with insufficient HIX value

### Expected Behavior

The both numbers should be the same

### Actual Behavior

They are not

### Additional Information
This issue is related to #2505 and #2501

**Comment by MizukiTemma** [comment]
One possibe cause is probably that the `pages_under_hix_threshold` will not be updated after a page (and therefore its HIX value) was changed.
