### ISSUE TITLE
Widen "overview of text understandibilty" box in translation report to size of "translation status" box

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2523]
### Describe the Bug
The box "Overview of the text understandability of the pages" in our translation report is quite narrow and makes some title expand two rows. This is (probably) not ideal.

### Steps to Reproduce

1. Go to translation report in either the test system or locally
2. See narrow box (or in the screenshot below)

### Expected Behavior

titles are legible

### Actual Behavior

Some difficulties to read the titles

### Additional Information

This issue was wished in this chat: https://chat.tuerantuer.org/digitalfabrik/pl/efj554x6tfyyzqo55o7hoae7th

**Comment by JoeyStk** [comment]
First step in this issue is probably for @hauf-toni to decide, if there are actually some UI or UX concerns about this box. If we find out, that it doesn't improve the user experience we can close it again as not planned :) 

![Screenshot from 2023-11-03 12-42-22](https://github.com/digitalfabrik/integreat-cms/assets/72705147/9c791d6f-6fe8-47a0-8687-5d4d687d4c3f)

![Screenshot from 2023-11-03 12-42-46](https://github.com/digitalfabrik/integreat-cms/assets/72705147/dcf41700-3e79-4d05-93e1-93cf75b914a0)

![Screenshot from 2023-11-03 12-42-50](https://github.com/digitalfabrik/integreat-cms/assets/72705147/da156048-743d-4dc5-a67a-d60903c7fcd9)

**Comment by hauf-toni** [comment]
Would it be possible to extend this field so that it is the same size as the field above it ("Aktueller Übersetzungsstatus")?
