### ISSUE TITLE
Machine translations do not publish when translation always was draft

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#2549]
### Describe the Bug
When a page translation in a translated language never was published before and the machine translation is used for the source language, the newly created version has the status draft.

### Steps to Reproduce

1. Create a new page and publish the page in the main language.
2. Create a target translation and save as draft.
3. Use the machine translation of the main language.
4. The target translation status is still draft after the machine translation.

### Expected Behavior
When a machine translation is used, the status of the translated page should always be the same as in the source language.

### Actual Behavior
The status of a translation that was draft is not changed to public.

### Additional Information
- https://chat.tuerantuer.org/digitalfabrik/pl/q8mf9h9bkjyadd84afit9aic5e
- #1883: "Automatic translation with trustful automatic services within our CMS (e.g. DeepL) -> Import should result in status "automatic translation" and should be directly visible in our app (publication status: PUBLIC)"
- https://chat.tuerantuer.org/digitalfabrik/threads/q8mf9h9bkjyadd84afit9aic5e

**Comment by PeterNerlich** [comment]
Why exactly is the expected behaviour that machine translation should always be public? What advantage does it have over the assumption that machine translations should inherit the status of the page they were translated from?

**Comment by JoeyStk** [comment]
@svenseeberg Do you maybe have some more insights?

**Comment by svenseeberg** [comment]
> @svenseeberg Do you maybe have some more insights?

I added a link with reports from users.

**Comment by svenseeberg** [comment]
> What advantage does it have over the assumption that machine translations should inherit the status of the page they were translated from?

I guess that is not what is happening right now. But maybe this needs to be re-validated.

**Comment by osmers** [comment]
I want to add that I tested this today and apparently, as soon as a page is saved as draft, all previous versions become draft versions even if they were published at some point. I can see that in the version history. 
I think @PeterNerlich is on the right track that translations should behave as the parent page does. So when I save a German page as draft with MT enabled, the translations should be translated and saved as draft. If I then publish the German page with MT enabled, the translations should be translated and published. Same goes for MT enabled and updating the German page. But I think that is not the problem right now.
If I save a German page as draft/or update it with MT disabled, the translations should maintain their publication status and change their translation status to outdated.

Does that make sense?

**Comment by JoeyStk** [comment]
Discussed in the grooming and questions could be resolved and were added to the issue description

**Comment by vthejay** [comment]
A new example reported by Stadt Augsburg:
https://admin.integreat-app.de/augsburg/pages/de/27100/edit/

The machione translations were all automaticcaly put under draft. Only Today, the person in the city of Augsburg had to publish the translations one after the other.
May it gives more insight.....

**Comment by osmers** [comment]
@JoeyStk @PeterNerlich how are you progressing with this milestone? @nassabay had the same problem with Regensburg where machine translations done from the editor did not publish and she wants to know what to tell the guy in Regensburg :)

**Comment by PeterNerlich** [comment]
@osmers We were still busy on another PR and haven't started on this yet.

@JoeyStk @svenseeberg Sanity check please: Under the recent changes adding Google Cloud Translate as a MT provider this behaviour is likely [this here](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/deepl_api/deepl_api_client.py#L136-L140):

```python
                existing_target_translation = content_object.get_translation(
                    target_language.slug
                )
                # […]
                data = {
                    "status": (
                        existing_target_translation.status
                        if existing_target_translation
                        else source_translation.status
                    ),
                    "machine_translated": True,
                    "currently_in_translation": False,
                }
```

so we should just need to change the status to always be `source_translation.status`, right?
