### ISSUE TITLE
Change wording of "review" to "approval"

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2554]
### Motivation

In the Dialogforum it was concluded that "Review" does not match the workflow of the cities using it. In German, "Freigabe" is the word of choice, which could translated with "approval".

### Proposed Solution

Instead of requiring a "review", use "approval"

- In page form & page tree:
  "Pending Review" / "Review ausstehend" -> "Pending approval" / "Freigabe ausstehend"
- In ToDo Dashboard:
  "Pages that are waiting for review" / "Seiten, die zum Review vorliegen" -> "Pages pending approval" / "Seiten, die zur Freigabe vorliegen"

**Comment by abastola0** [comment]
Hi @timobrembeck. Can I take this issue?

**Comment by timobrembeck** [comment]
@abastola0 Sure, thanks! Feel free to ask when you have questions or have a look at our [developer documentation](https://digitalfabrik.github.io/integreat-cms/).

**Comment by abastola0** [comment]
Sure. Thanks @timobrembeck.
