### ISSUE TITLE
Bring test coverage to 82,5 %

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2582]
### Motivation

As a part of our "Zero bug policy" let us increase the test coverage continueing from #2492 

### Proposed Solution

Goal for the end of March 2024: 82,5% 
Current coverage:  [![](https://img.shields.io/codeclimate/coverage/digitalfabrik/integreat-cms)](https://codeclimate.com/github/digitalfabrik/integreat-cms/code?sort=-loc)

### Additional Context

For more information see #2492 
The goal percentage can be adjusted after all the test related PRs are closed that are currently open.

**Comment by MizukiTemma** [comment]
Please leave comments here which part will be worked on, when you start, to avoid multiple people working on the same parts.

**Comment by JoeyStk** [comment]
Peter and I decided to write tests for [page_form_view.py](integreat_cms/cms/views/pages/page_form_view.py) :).

**Comment by seluianova** [comment]
@MariaKabanova and I will take hix.py

**Comment by MizukiTemma** [comment]
Sorry, I've closed it accidentally by the latest PR. Still 0,5% to go 😅

**Comment by seluianova** [comment]
0,4% to go :)

**Comment by JoeyStk** [comment]
And we're back to 81,7% :sweat_smile:

**Comment by timobrembeck** [comment]
> And we're back to 81,7% 😅

Well, that's on me :innocent: 
And will be fixed with #2772 hopefully.

**Comment by MizukiTemma** [comment]
I hope #2696 will bring it up again 👀

**Comment by MizukiTemma** [comment]
We've reached 82,5% 🎉 

Let's keep this good coverage 😸

**Comment by MizukiTemma** [comment]
We've reached 82,5% 🎉

Let's keep this good coverage 😸
