### ISSUE TITLE
Improve Language Selection of Maschine Translation  

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2586]
### Motivation

In future more automatic translation providers will be connected to our CMS system. It's time to improve and/or re-design "Language Selection" box in the machine translation settings, to make it clear for users which language is to be translated by which provider etc.

### Proposed Solution

TBD with UI/UX team

Leave comments here if you have any opinion, idea, question or concern 😉  

### Alternatives

N/A

### User Story

N/A

### Additional Context

Introduction of new automatic translation providers #1436 

The affected zone:
![image](https://github.com/digitalfabrik/integreat-cms/assets/82345046/f4c753b4-dc96-46f9-9336-849beb5f58c1)

### Design Requirements

Following points are subject to discussion and attention:
- Whether the current listing style of languages pro provider is good enough, possibly how to improve it
- How to handle languages that are supported by more than one provider (Should each language have only one provider assigned or make it possible to translate by multiple providers to, for example, compare the quality and chose the best one?) (How to display the check box etc in the box)

**Comment by MizukiTemma** [comment]
In my opinion only one provider should be assined for each language and users choose one (and change to another if they want) for each language in the setting. This lets users save translation credits, is easier to use (it will be too much work at some point to compare result translations of multiple providers or to choose one provider every time when machine translation is needed), and avoids much of possible errors and bad user experience.

**Comment by JoeyStk** [comment]
My idea would be to have a list of all languages that are supported by at least one provider. Next to the language I would probably add a dropdown button where region managers can select the MT providers that should be used for each language. For the default values I think we can use some sort of provider hierarchy.
@hauf-toni What do you think about this and do you have some additional insight?

**Comment by dkehne** [comment]
Yeah, I am with @JoeyStk. Dropdown to choose from the provdiers.

**Comment by JoeyStk** [comment]
It probably makes sense to implement this either before or alternatively in parallel with [#1436](https://github.com/digitalfabrik/integreat-cms/issues/1436).

**Comment by osmers** [comment]
Just to add onto what's been said - I think if users want to compare quality they can do that outside the CMS by simply copying and pasting the text to both DeepL and Google and let native speakers check the translations. That way they do not need to use credits at all.

**Comment by hauf-toni** [comment]
from ui/ux side it is a go for @JoeyStk 's idea (dropdown menu). would you like a design for this?

**Comment by osmers** [comment]
I think a design would be useful, if it is not a lot of work @hauf-toni

**Comment by hauf-toni** [comment]
As discussed with @dkehne  @JoeyStk @osmers, we will proceed with johannes' suggestion & revise the design if necessary to optimize space after the gt connection has been completed 🪛
