### ISSUE TITLE
Translations are marked as available but no content Web-App

### ISSUE THREAD

**Issue by clarabracklo** [digitalfabrik/integreat-cms#2590]
I am not sure if this is an app or cms issue, maybe you have to move it. 

I have just visited https://integreat.app/bodenseekreis/de/ukraine-flucht/erste-informationen/hilfe-und-solidaritaet-im-landkreis-bodenseekreis in my browser (Firefox). 
When I am on the German page and hover over the translation options a lot of them are black (seem to be available). However, when I click on them (for example English) no translation is available and I can not get back to the German page. Some translations are available (e.g. Romanian). Can you reproduce this problem and is it known already? 

![grafik](https://github.com/digitalfabrik/integreat-app/assets/26277354/c113e12d-22f3-4964-a039-9591b66c6f7c)
![grafik](https://github.com/digitalfabrik/integreat-app/assets/26277354/d354996e-127e-41ba-bc0e-8c6e5c3ee7d1)

**Comment by osmers** [comment]
As commented in Mattermost - this is not a CMS issue, it's a problem with missing translations of the parent page so a Bedienfehler from Bodenseekreis...we can close the issue

**Comment by ztefanie** [comment]
Wouldn't a check in cms nevertheless make sense for avoiding these errors?

**Comment by osmers** [comment]
Like showing a message that says "this page's parent page is not yet public, so despite translation, users won't be able to see the content"?

Or what exactly do you mean by check? :)

**Comment by timobrembeck** [comment]
I guess we could remove the languages from "available translations" in the API response if the parent is not available in this language, yes. I'm just not sure about performance implications, if we have to do one query per page to get this information, I'd say the the functionality enhancement does not justify significantly longer loading times.
But we will have a look at it and check whether it's feasible.
