### ISSUE TITLE
Offer tempaltes navigation missing in menu in live system

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-cms#2611]
### Describe the Bug
As a developer I want to add and edit offer templates. For that I need a way to navigate to the offer templates. However, in the "Netzverwaltung" in the live CMS I don't see a button "Angebots-Vorlagen". I can still navigate to the url directly, though

### Steps to Reproduce

1. Go to the live cms have the same rights/roles as I have 
2. Go to the netzwerkverwaltung
3. See that the button is missing in the sidebar menu

### Expected Behavior
<img width="280" alt="Bildschirmfoto 2024-01-18 um 12 18 27" src="https://github.com/digitalfabrik/integreat-cms/assets/28013368/5af9421d-644a-476e-a36c-1ecca1ea0976">

### Actual Behavior

<img width="280" alt="Bildschirmfoto 2024-01-18 um 12 17 27" src="https://github.com/digitalfabrik/integreat-cms/assets/28013368/5dc05840-0d82-4d38-a8b9-86c116c04fa3">

**Comment by ulliholtgrave** [comment]
This was already fixed by me in #2589 , but so far we didn't trigger a release :see_no_evil:
