### ISSUE TITLE
Update webauthn to version 2.0.0

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#2614]
### Motivation

Webauthn had a breaking update with version 2.0.0 which will require some minor refactoring in our codebase.

**Comment by nkclemson** [comment]
Hi. I am a Django developer with six years of experience. I would like to start contributing to integreat-cms starting with this issue if there is no problem then. Would it be possible to assign this to me?

**Comment by timobrembeck** [comment]
@nkclemson Awesome, thanks a lot for your interest in our project! :rocket: 
Sure, feel free to work on this and ask any questions if something is unclear.

**Comment by david-venhoff** [comment]
Information how to upgrade: https://github.com/duo-labs/py_webauthn/releases/tag/v2.0.0
