### ISSUE TITLE
Exclude empty pages from the list of outdated pages

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2660]
### Motivation

We currently show all the pages that are not updated more than 1 year in "Outdated pages" section in the dashboard.

However, the date of last modification is not important for empty pages, because they exist to function as "paragraph title".

⚠️ Keep loading time in mind. It might be a problem for regions with a lot of pages.

### Proposed Solution

Exclude empty pags from the list of outdated pages.

### Alternatives

Leave it as it is.

### Additional Context

We want to encourage users to keep the contents actual. (OKR)
We want to increase usability of Integreat System by showing only non empty pages, which really needs updating. (OKR)

**Comment by MizukiTemma** [comment]
This needs to be implemented in an earlier stage of this year so we can count how many pages really must be updated (OKR).

**Comment by JoeyStk** [comment]
Currently it's not possible to exclude empty pages from a search query in the page tree, right? Am I understanding it correctly then that implementing this filter would also be part of this issue? :)

**Comment by timobrembeck** [comment]
@JoeyStk yes I agree, the dashboard section about outdated pages should not only contain the correct number of pages, but should also link to the page tree without the empty pages, and for the link to work, we need this filter.
