### ISSUE TITLE
Adjust title of translation box in content forms

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2690]
### Motivation
Too make the UI cleaner and use as less space as possible we may remove the explanation text from the "Automatic Translation" because it's intuitve after we have made it to one of the key featurese/benefits of Integreat the last month. Also there is some kind of expansion on all languages after clicking the button so it's really clear what the function does.

### Proposed Solution
- ~Remove the explanation text of the "Automatic Translation" checkbox.~
- Adjust also the German title of the block to "Auswirkungen auf Übersetzungen".

See screenshot

<img width="807" alt="adjust-translation-text" src="https://github.com/digitalfabrik/integreat-cms/assets/4182469/b96609f9-0bff-4b40-ac39-87e5b09f404f">

**Comment by osmers** [comment]
after talking to @dkehne we'll leave the description text as it is (so no removing necessay) but can definitely change the title of the box
