### ISSUE TITLE
Add Poi category icons

### ISSUE THREAD

**Issue by f1sh1918** [digitalfabrik/integreat-cms#2698]
### Motivation
For malte and netzwerk obdach we need two new category icons

### Proposed Solution
Please make the new icons available via dropdown and deliver it to the frontend via api:

- mental_health
- shelter

Find new svg icons here:
[integreat_categories_cms.zip](https://nextcloud.tuerantuer.org/index.php/f/3345518)

api should deliver `<icon_name>_<colorHex>`

**Comment by MizukiTemma** [comment]
@f1sh1918 Are the new icons broken? When I open the svg data of a new icon nothing will be shown, while existing icons are correctly shown... 🤔
