### ISSUE TITLE
Use a consistent format for date and time

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2706]
### Motivation
Having a standardized date for last update makes a quick overview easier

### Proposed Solution
Don't show the time and write the date using only numbers - e.g. 04.03.2024 instead of 3. März 2024 - use German date system, not the American one

### Alternatives
Keep it, as it is

### User Story
As a user of the CMS I want to be able to see that last update date clearly without distracting information so that I can get a quick overview of outdated pages

![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/e205a146-55a1-4201-9e2e-82c8d755292a)

**Comment by timobrembeck** [comment]
Hmm, I'd argue that time is actually relevant in many cases?
So maybe `20.02.2024 16:40` or some kind of separator between date and time, e.g. `|`, `–` or `, `?

**Comment by lunars97** [comment]
from User's perspective maybe it could be cleaner and not so clattered with TMI if we could remove time for not so relevant things like pages except for versions like @osmers suggested

**Comment by lunars97** [comment]
If we change `last update`, we also need to change `created` and `last login` as well in order to be consistent with one chosen date format
