### ISSUE TITLE
Adjust maximal amount of characters for push notfications / news 

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2737]
The maximal amount of characters for the push notifcations body should be adjusted to 500 (currently 250).
Beside the technical adjustment of the figure you might need to check how the app is displaying a longer push-notification, e.g. is it automatically using only the first 250 chars ands add "..." behind or do we have to cut it by ourselves?

**Comment by MizukiTemma** [comment]
>Beside the technical adjustment of the figure you might need to check how the app is displaying a longer push-notification, e.g. is it automatically using only the first 250 chars ands add "..." behind or do we have to cut it by ourselves?

@f1sh1918 
Is there anything that should be done in the backend for this point?

**Comment by f1sh1918** [comment]
As far as I can see it should be fine.
Do you see any issues @steffenkleinle ?

**Comment by steffenkleinle** [comment]
I don't think so, no. I proposed a few times already that it might make sense to decouple the notification text (non-html) and the text that is displayed in the detail view in the app (with html text). Still makes sense imo, but thats another issue.
