### ISSUE TITLE
HIX-threshold for translation should use the uprounded value

### ISSUE THREAD

**Issue by dkehne** [digitalfabrik/integreat-cms#2756]
Page: Residents' Registration Office (https://admin.integreat-app.de/dahme-spreewald/pages/de/32725/edit/). Hix value to see 15. color yellow. 
Page: National Visa (D-Visa) (https://admin.integreat-app.de/dahme-spreewald/pages/de/33077/edit/). Hix value to see 15. color green. 

![Screenshot (1489)](https://github.com/digitalfabrik/integreat-cms/assets/4182469/9a12eed3-ea7d-43d2-94a4-94ea0a611097)

If you move the mouse over it:
Where it is yellow, the value is: 14.995. Where it is green, the value is: 15.002.

If the HIX-Value is shown as 15 because it is rounded up from 14.995 it should be marked green and translations should be possible. So maybe we can adjust the logic here that the decision on the HIX-threshold is also done based on the rounded-up-value.

That would be great.

**Comment by dkehne** [comment]
@PeterNerlich @MizukiTemma thanks for the implemenation but i guess the function is now doing sth. completly different now. 
It is now downgrading every hix-value. and also if i have a hix-value of 13.94 it is shown as 13. 

So sth. is not working here, not sure if it comes from this update here or another.

**Comment by dkehne** [comment]
Two things that have changed but were not proposed to change:
- HIX-value is shown as "14" if it is "14.99".
- Detailled mouseover was removed (so it is not possible to see the exact hix value anymore)

See for example: https://admin.integreat-app.de/testumgebung/pages/de/37330/edit/

The only thing we wanted to be changed here is that if the "rounding up"-logic shows e.g. 14 (which is enough to translate) then it should be possible to translate.

**Comment by MizukiTemma** [comment]
@dkehne sorry for the unwanted changes 🥺 

In this example
- HIX value in the hix bar must be 14,99
- Mouseover should show 14,988696629148205

Am I understanding correctly?
