### ISSUE TITLE
Add script to create POIs from CSV

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#2757]
### Motivation

For Malte, we need the possibility to convert Excel files to POI objects.
Since Excel files might be hard to work with, I guess we can assume that it's always possible to export the excel file into CSV and use it that way.

### Proposed Solution

- Think about how to translate POI objects into tables (especially what about opening hours?)
    - If passing the opening hours as columns is too hard, maybe we can use our internal structure and pass them via a serialized json string in one csv cell?
- Write a short script that can be executed inside `integreat-cms-cli shell` or add a management command (preferred if the time suffices) to convert a csv into POI objects.
- At least one translation in the default language has to be created

### User Story

Users want to get POIs from Excel into the CMS

### Design Requirements

No UI necessary

**Comment by osmers** [comment]
What's the progress with this issue? @timobrembeck @PeterNerlich ?
