### ISSUE TITLE
Replace Icon for "Behörde/Amt" in our POI categories

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-cms#2800]
### Motivation

Copying over from https://github.com/digitalfabrik/integreat-app/issues/2657:
The current icon is a hammer which is related negatively.

### Proposed Solution

Replace the poi-category-icon in office.svg with the one here: https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=1136-3404&t=kmn5PQC6Ck7mBcj9-0 (in the second row, fourth from the right, I had a hard time finding it for a while)

### Additional Context

Current icon:
<img width="135" alt="image" src="https://github.com/digitalfabrik/integreat-cms/assets/18513943/791e9cf1-faad-4342-88ff-6c4214b96bb0">

### Design Requirements

Requested icon:
<img width="35" alt="image" src="https://github.com/digitalfabrik/integreat-cms/assets/18513943/addbad3d-6390-4b8d-a77e-281ef44a649e">

**Comment by JoeyStk** [comment]
In the past we got the icon in this dark-grey circle as an svg like [here](https://nextcloud.tuerantuer.org/index.php/f/3345518). @LeandraH Do you know if there already is a svg file for us somewhere? :)

**Comment by LeandraH** [comment]
Uhm, no idea. @hauf-toni, do you happen to have the new icon for Behörde with a dark-grey color? You probably know better than I what the exact specifications are 😅

**Comment by hauf-toni** [comment]
@LeandraH sure, you can find the icon [here](https://www.figma.com/design/cA4F2MwHs2LNGviOWUjfE9/Integreat-Tickets-Frontend?node-id=1136%3A3404&t=r16diwdwoWoQch6I-1)
