### ISSUE TITLE
Translation with status "maschine translated" outdates after date refreshing

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2807]
### Describe the Bug

Translations with status "maschine translated" are "outdated" after refreshing the date of their source translation.

### Steps to Reproduce
1. Set two languages (for example English and Arabic) directly hanging from German (root language) in the language tree of a region.
2. Create a German translation.
3. Create an Arabic translation by MT, and create an English translation manually (not by MT)
4. See in the page tree that the German and English traslations are up-to-date (✅) and the Arabic one maschine-translated (🤖)
5. Open the German translation and click the button "Mark this page as up-to-date"
6. Go back to the page tree, see the German and English translations are up-to-date but the Arabic one is marked as outdated (⚠️)

### Expected Behavior

The Arabic translation should be up-to-date too.

### Actual Behavior

The Arabic translation is outdated.

### Additional Information

👀 The cause seems to be the order in which the translations are refreshed: after this reproduction procedure the German translation (version 2) and the English one (version 1) have time stamp of 16:04:12, where as the Arabic one 16:03:38.

💡It is recommended to implement/review this issue with redis activated.

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by lunars97** [comment]
@MizukiTemma seems like it should be like that because when we update the source language without ticking an automatic translation and updating it, the machine translated stays unchanged and therefore it outdates if the source translation was updated without ticking an automatic translation. Shouldn't it behave like that?

**Comment by osmers** [comment]
No, Mizuki is right bcs we are not talking about the update button in the top right hand corner but about the "mark page as up to date" button (further down in the settings of the page) which presumes that nothing was changed, all information is up to date and only should update the date on all pages that are marked as up to date (with a tick in the translation status).

**Comment by MizukiTemma** [comment]
@osmers Thank you for explaining 👍 

@lunars97 Sorry, I have overlooked your question 😿 Yes, it about the button "Mark this page as up-to-date" in the side box "Actions"
