### ISSUE TITLE
Add link checker to to do board

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2824]
### Motivation
It is important to correct broken links - without the link checker in the to do board this tasks sometimes gets out of sight

### Proposed Solution
Add link checker count to to do board

### Alternatives
none

### User Story
As a CMS user I want to be reminded of the broken links in order to fix them more quickly

**Comment by JoeyStk** [comment]
To the developer who is interested in taking this issue: Functionality is already implemented but commented out, because the loading times were to high. The task would be to come up with something that decreases the loading times. This solution could then probably also be used for #4 .

**Comment by JoeyStk** [comment]
It was agreed to solve this with AJAX
