### ISSUE TITLE
Select all box for machine translations

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2838]
### Motivation
Selecting all languages individually takes time. When creating a new page it would be easier to be able to tick a box that selects all languages automatically

### Proposed Solution
Add a box similar to multi language xliff export: 
![image](https://github.com/digitalfabrik/integreat-cms/assets/64901227/9ce669bc-110f-4b36-bbd4-75c4e740b100)

Possibly make one box per list (existing translations and new translations)?

### Alternatives
Keep it, as it is

### User Story
As a CMS user I want to be able to create translations quickly and not have to select 20 languages individually.

### Design Requirements
We can reuse the design from multi language xliff export.

**Comment by JoeyStk** [comment]
@osmers Do you mean inside the machine translation box on the page form? 
![grafik](https://github.com/digitalfabrik/integreat-cms/assets/72705147/be9ae36c-26b6-40c2-8255-69cce968dc9b)

**Comment by osmers** [comment]
@JoeyStk yes exactly
