### ISSUE TITLE
location_url in event incorrectly links to CMS

### ISSUE THREAD

**Issue by LeandraH** [digitalfabrik/integreat-cms#2852]
### Describe the Bug

The `location_url` in events links to the CMS, not the app.

### Steps to Reproduce

1. Go to 'https://cms.integreat-app.de/testumgebung/de/wp-json/extensions/v3/events/?combine_recurring=True'
2. Check in the event with the id 57026 (currently the second one in the array)
3. See that the `location_url` is 'https://admin.integreat-app.de/testumgebung/de/locations/testort/'.

### Expected Behavior

The `location_url` should be 'https://integreat.app/testumgebung/de/locations/testort', aka the link to the location in the app.

### Actual Behavior

The `location_url` is 'https://admin.integreat-app.de/testumgebung/de/locations/testort/', aka the link to the location in the CMS.

**Comment by steffenkleinle** [comment]
Hmmm.... I am not sure if we should rather just use the slug/path instead of a full URL? That would provide us with more flexibility in the apps while probably less logic is required in the CMS (and it would follow the structure of all other properties/endpoints).

**Comment by LeandraH** [comment]
True, but then it's not really a bug ticket anymore :D

**Comment by MizukiTemma** [comment]
@steffenkleinle @LeandraH 
Is this change but still needed as enhancement?

**Comment by LeandraH** [comment]
That would be cool. I guess at that point it shouldn't be called `location_url` anymore but `location_path`?

**Comment by MizukiTemma** [comment]
@LeandraH @steffenkleinle 

> That would be cool. I guess at that point it shouldn't be called `location_url` anymore but `location_path`?

And should the outpup be "/testumgebung/de/locations/testort"?

**Comment by steffenkleinle** [comment]
> @LeandraH @steffenkleinle
> 
> > That would be cool. I guess at that point it shouldn't be called `location_url` anymore but `location_path`?
> 
> And should the outpup be "/testumgebung/de/locations/testort"?

Yes, but probably including a trailing slash.

**Comment by MizukiTemma** [comment]
Sorry, one more question: can `location_url` be removed without problem or is it being used somewhere in the app?

**Comment by steffenkleinle** [comment]
> @LeandraH @steffenkleinle 
> Sorry, one more question: can `location_url` be removed without problem or is it being used somewhere in the app? 

It is not yet used so it can easily be removed.

**Comment by LeandraH** [comment]
Awesome, thank you for the quick fix!
