### ISSUE TITLE
Error when creating a new page

### ISSUE THREAD

**Issue by charludo** [digitalfabrik/integreat-cms#2872]
### Describe the Bug

When creating a new page, django throws an error `ValueError: 'Page' instance needs to have a primary key value before this relationship can be used`. This is not critical, as page creation is still possible. Rather, this is a bug within the `get_repr` method of the `Page` model, where `self.best_translation` is accessed before that relation exists.

### Steps to Reproduce

1. Visit `http://localhost:8000/augsburg/pages/de/new/`
2. See error in django console

### Expected Behavior

No error

### Actual Behavior

Error, but does not prevent page creation

### Additional Information

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by JoeyStk** [comment]
@charludo is this a duplicate of https://github.com/digitalfabrik/integreat-cms/issues/2806 or is it something different? :thinking:

**Comment by charludo** [comment]
> @charludo is this a duplicate of #2806 or is it something different? 🤔

Oops, sorry about that - did not see this!
