### ISSUE TITLE
Refactor calculation of pages with low HIX value on dashboard & analytics

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#2903]
### Steps to Reproduce

1. Go on the test server to Testumgebung. See on the dashboard it says there are 52 pages with an HIX value of < 15.
2. Click on translation report, see there it says 59 out of 110 pages are ready for translation (which means 51 pages have a HIX value > treshhold)

### Expected Behavior

Numbers should be the same

### Actual Behavior

Numbers are diverging, 52 != 51

### Additional Information

None

**Comment by MizukiTemma** [comment]
@PeterNerlich @JoeyStk 
It seems pages with hix core = 0.0 are causing this difference.

**Comment by JoeyStk** [comment]
Yes, thank you very much! We found out the same thing. We will refactoring the calculation for HIX a little bit & then use this refactored function as a util function both in the analytics section and the dashboard
