### ISSUE TITLE
News have stringified id

### ISSUE THREAD

**Issue by steffenkleinle** [digitalfabrik/integreat-cms#2927]
### Describe the Bug

The ids of news are returned as strings instead of numbers.

### Steps to Reproduce

1. Go to https://cms-test.integreat-app.de/api/v3/testumgebung/de/fcm/
2. See stringified id

### Expected Behavior

The id to be of type number.

### Actual Behavior

The id is a string.

### Additional Information

This is also in contrast to all other endpoints using numbers. Also the ids in the available languages are numbers (#2811).

**Comment by MizukiTemma** [comment]
@steffenkleinle 
Is the id currently being used and do we need compatibility?

**Comment by steffenkleinle** [comment]
> @steffenkleinle Is the id currently being used and do we need compatibility?

The id is currently used, yes. However, I think we do not need compatibility (as we were already expecting a numeric id/using typecasts so far).

**Comment by MizukiTemma** [comment]
> > @steffenkleinle Is the id currently being used and do we need compatibility?
> 
> The id is currently used, yes. However, I think we do not need compatibility (as we were already expecting a numeric id/using typecasts so far).

@steffenkleinle Ok, thank you 😸

**Comment by steffenkleinle** [comment]
Was this released? It looks like this problem still persists @lunars97

**Comment by lunars97** [comment]
> Was this released? It looks like this problem still persists [@lunars97](https://github.com/lunars97) Definitely not a (big) problem though.

yes, it was released... 🤔

**Comment by steffenkleinle** [comment]
Hmmm, this is the response I get, the `news_id` is sadly still stringified...
``` json
{"collapseKey": "app.integreat.test", "data": {"city_code": "testumgebung", "group": "news", "language_code": "de", "news_id": "11199"}, "from": "/topics/testumgebung-de-news", "messageId": "0:1738311964351661%159da996159da996", "notification": {"android": {}, "body": "Test", "title": "Test"}, "sentTime": 1738311963411, "ttl": 86400}

```

**Comment by lunars97** [comment]
> Hmmm, this is the response I get, the `news_id` is sadly still stringified...
> 
> {"collapseKey": "app.integreat.test", "data": {"city_code": "testumgebung", "group": "news", "language_code": "de", "news_id": "11199"}, "from": "/topics/testumgebung-de-news", "messageId": "0:1738311964351661%159da996159da996", "notification": {"android": {}, "body": "Test", "title": "Test"}, "sentTime": 1738311963411, "ttl": 86400}

I merged the fix 👍

**Comment by PeterNerlich** [comment]
> @steffenkleinle 
> Hmmm, this is the response I get, the `news_id` is sadly still stringified...
> 
> {"collapseKey": "app.integreat.test", "data": {"city_code": "testumgebung", "group": "news", "language_code": "de", "news_id": "11199"}, "from": "/topics/testumgebung-de-news", "messageId": "0:1738311964351661%159da996159da996", "notification": {"android": {}, "body": "Test", "title": "Test"}, "sentTime": 1738311963411, "ttl": 86400}

Where do you get this from, from our API or the notification received from the Google FCM services? Because the latter [only allows specifying `data` as key-value pairs that are strictly strings](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message.FIELDS.data)

**Comment by steffenkleinle** [comment]
> > @steffenkleinle 
> > Hmmm, this is the response I get, the `news_id` is sadly still stringified...
> > 
> > {"collapseKey": "app.integreat.test", "data": {"city_code": "testumgebung", "group": "news", "language_code": "de", "news_id": "11199"}, "from": "/topics/testumgebung-de-news", "messageId": "0:1738311964351661%159da996159da996", "notification": {"android": {}, "body": "Test", "title": "Test"}, "sentTime": 1738311963411, "ttl": 86400}
> 
> Where do you get this from, from our API or the notification received from the Google FCM services? Because the latter [only allows specifying `data` as key-value pairs that are strictly strings](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message.FIELDS.data)

The latter, that explains it then. Thank you :) Then we'll just keep parsing the string :)
