### ISSUE TITLE
Add archive option to organizations

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2949]
### Motivation

Currently organizations can only be created, saved (changed) or deleted. Now it must be possible to archive them too.

This helps munincipalities by giving them a way to sort organizations that are currently not used out of the list by archiving.

### Proposed Solution

- Add a new boolean field "archived" to the model organization with default value false.
- Create a migration.
- Add a function to change the value of the field
- Add a button that calls the function 

### Alternatives

Leave it as it is

**Comment by MizukiTemma** [comment]
@osmers 
Should we protect organizations from archiving/deleting when it has a page or a location (or members)?

**Comment by osmers** [comment]
Hmmmm - good question. That would be in line with how we handle it in other case. Alternatively I could imagine that it would be helpful to be able to archive (maybe after receiving a warning that the organisation is still assigned to a page/POI or has members). That way, if you want to archive an organisation, you don't have to remove it from all the pages/POIs first. That could happen automatically...

**Comment by MizukiTemma** [comment]
@osmers Thank you for reply 😸 Then we'll show an warning before archiving/deleting.

**Comment by osmers** [comment]
@MizukiTemma maybe ask UI/UX what an intuitive workflow for users would be...
