### ISSUE TITLE
[2024-11-07] Add contact as choice for "insert" in TinyMCE

### ISSUE THREAD

**Issue by MizukiTemma** [digitalfabrik/integreat-cms#2959]
### Motivation

Contact information referred in contents are changed and updated centrally. This is why we implement a new model "contact". Let's give it a place where it shines.

### Proposed Solution

- Add an "contact" to the option "Insert" in TinyMCE, like Media Library and Link. 
- Where each contact is embedded, must be calculatable and handed over in `contact_form.view` (search for `# to implement later, how do we collect such pages?`).

### Additional Context

Wait for #2952

**Comment by david-venhoff** [comment]
One idea how we could do it:
Represent contacts as urls and add a new url endpoint to the cms that returns contacts. When a user inserts a contact in tinymce we would just insert the url to it (plus maybe some parameters that specify which fields of the contact should be shown).
Advantage: 
- We won't have to update any pages when a contact changes
- We easily figure out in which pages contacts are used using linkcheck and prevent users from deleting contacts if they are still used
- We don't include any styling in the html and leave that up to the app

Disadvantage
- The App team would have to write some custom code to correctly render these urls as contacts in the app

**Comment by PeterNerlich** [comment]
We can make non-editable elements in TinyMCE by adding the HTML attribute `contenteditable="false"`. I would propose to put the div with all that should be displayed for the content inline this way.
