### ISSUE TITLE
Every second language label is hidden in translation report

### ISSUE THREAD

**Issue by deen13** [digitalfabrik/integreat-cms#2969]
### Describe the Bug
In the translation coverage analytics of the Integreat CMS, certain language labels such as Arabic, Kurmanji, and Oromo are not displayed on the chart despite there being sufficient space for them. This affects the usability and accessibility of the chart.

### Steps to Reproduce

1. Go to [Integreat CMS Translation Coverage](https://cms.integreat-app.de/testumgebung/analytics/translation-coverage/)
2. Observe that labels for languages like Arabic, Kurmanji, and Oromo are hidden even though there is enough space for them.

### Expected Behavior

I expect all labels to be visible without the need to hover over the chart. This is especially important for people with disabilities who may not use a mouse or may have difficulty with precise cursor movements, such as those with hand tremors.

### Actual Behavior

Every second label is hidden and only visible on hover.

### Additional Information
![Screenshot 2024-08-06 at 09 04 11](https://github.com/user-attachments/assets/ecc9525b-732d-4913-9337-7bc0b0f0bbad)

**Comment by osmers** [comment]
I can see the labels: 
![image](https://github.com/user-attachments/assets/b42a3607-9c08-4ae6-9996-d072446cfa47)

**Comment by deen13** [comment]
What resolution are you using @osmers? I'm experiencing the issue at 2000x1251px.

**Comment by deen13** [comment]
This demonstration shows how the feature would appear and function for someone with a hand tremor.

https://github.com/user-attachments/assets/5df98810-6d65-4761-acca-fbcc9c4041c8

**Comment by osmers** [comment]
1920x1080 - a higher resolution is not possible on my laptop.

**Comment by deen13** [comment]
I can confirm that the issue occurs between these resolutions. I can reproduce it by adjusting the width of my browser window. 👍
