### ISSUE TITLE
Weekly and monthly recurring events are always off by one day

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2988]
### Describe the Bug
Any event set to recur weekly or monthly shows the date off by one day in the app

### Steps to Reproduce

1. Go to https://admin.integreat-app.de/testumgebung/events/de/6252/edit/
2. See that the date is set to thursday Aug 15th
3. Go to https://integreat.app/testumgebung/de/events/jeden-donnerstag
4. See dates set to be 16th and then every week

### Expected Behavior
Date in the app should be date set in the cms

### Actual Behavior
Date in the app is always +1

### Additional Information
Not sure if maybe this is an app issue?

**Comment by osmers** [comment]
The problem seems to occur with events that have their first start date on April 1st or later - anything before then has the right dates...

**Comment by david-venhoff** [comment]
This is the recurrence rule the cms produces for `Jeden Donnerstag`: `DTSTART:20240331T230000RRULE:FREQ=WEEKLY;BYDAY=TH`, which looks correct to me. So this is probably an app issue

> The problem seems to occur with events that have their first start date on April 1st or later - anything before then has the right dates...

One thing of note is that this recurrence rule starts on another day in utc-time (01.04.2024 1am - 2 hours offset => 31.03.2024 11pm). However, if the event starts before summer time (begin on the last sunday of march)  then the utc offset is only 1 hour, which means that the event still is on the same day in utc time...
