### ISSUE TITLE
Exclude languages from being copied during region creation process

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2990]
### Motivation
When creating a new region, all the content gets copied. This includes the full language tree and all translations. After creating the region, we (Service Team) delete the language nodes in the language tree bcs we do not need them in the beginning and often regions use different languages to the ones from the copied region. The region creation process often leads to a timeout and incompletely copied regions and deleting the language nodes also often leads to a timeout. 

### Proposed Solution
We don't copy language nodes and translations during creation. We only copy content in the main language.

### Alternatives
Keep it as it is.

### User Story
<!-- A clear description of the User Stories that should be achieved by the new feature. The User Stories should follow this pattern:
As a Service Team member I only need the content in the main language and prefer to only copy that in order to avoid time outs during creation and additional work after creating a region.

**Comment by david-venhoff** [comment]
Closed in favor of #2991
