### ISSUE TITLE
Add checkbox in region creation form that allows to not copy languages and translations of the source region

### ISSUE THREAD

**Issue by osmers** [digitalfabrik/integreat-cms#2991]
### Motivation
Add a checkbox that allows to not copy the language nodes and translations upon region creation using the copy functionality, because they are often not needed.

### Proposed Solution
Add a default-checked checkbox that upon unchecking prevents the languages nodes and translations of the source region to be copied to the new region.

### Alternatives
None

### User Story
As a Service Team memeber I need the translations of copied regions in the Malte App in order to fulfill the requirements of the Malteser, but I don't want that functionality always.

**Comment by david-venhoff** [comment]
This would also be a workaround of #3048

**Comment by juliankehne** [comment]
@charludo While testing the checkbox I had one case where not all pages were copied.

I tried to reproduce it, but wasn't able to:
- New checkbox was checked (to include translations)
- Region that pages were copied from: Testumgebung
https://cms-test.integreat-app.de/regions/2991-1/edit/
https://cms-test.integreat-app.de/2991-1/pages/de/

Is that the known issue of the process timing out when copying pages with translations or something else?

**Comment by osmers** [comment]
I assume it's the same problem we've been having with the old process - it simply times out while trying to copy everything. For Integreat generally we will need the checkbox unchecked so that no translations get copied. Nevertheless, for Malte we do need the translations, so if the problem persists, especially within Malte, that content only gets partially copied, we need to investigate further :)
