### ISSUE TITLE
Refactor migrations that modifiy roles

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#2996]
### Motivation

Each time a migration modifies the roles, it runs a copy-pasted chunk of code.

### Proposed Solution

Create a common function for this code, and consider running it only once if that is possible

### Alternatives

Do nothing

### Additional Context

Affected migrations:
- 0025
- 0035
- 0039
- 0043
- 0044
- 0053
- 0056
- 0058

And also the migration of #2895 after it has been merged

**Comment by david-venhoff** [comment]
This came up at https://github.com/digitalfabrik/integreat-cms/pull/2895#discussion_r1699729143

**Comment by timobrembeck** [comment]
I would suggest to implement #1857 instead of refactoring the migration functions.

**Comment by david-venhoff** [comment]
Closed in favor of #1857
