### ISSUE TITLE
 Missing translation for Bildung/Education when selecting Arabic

### ISSUE THREAD

**Issue by bahaaTuffaha** [digitalfabrik/integreat-cms#3008]
### Describe the Bug

Missing translation for Bildung/Education in categories at (münchen - Landeshauptstadt) when selecting the Arabic language.

### Steps to Reproduce

You can check : [2875](https://github.com/digitalfabrik/integreat-app/issues/2875)

### Expected Behavior
It should show the Arabic word : (التعليم)

### Actual Behavior

It shows currently (Bildung).

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by JoeyStk** [comment]
@bahaaTuffaha Thank you a lot for reporting this issue. As far as I can tell this is an issue for the content, so I'm going to ping @osmers here :)

**Comment by osmers** [comment]
Yeah, we can just add the translations of POI categories in the network management of the CMS. Some are missing unfortunately though I think Bildung is the only one missing in Arabic. Thanks for contributing the word :)

**Comment by osmers** [comment]
Translation was added :)
