### ISSUE TITLE
Data export for traffic light system gets `504 Gateway Timeout` error

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#3053]
### Describe the Bug

This issue lays groundwork for #3012.
Add export functionality that is only available to the service team, which allows creating csv files that contain all relevant data used for the traffic light system.

That includes:
* Number of outdated pages per region
* Number of broken links per region
* Number of pages per region with hix below 15
* Number of total pages per region
* Number of missing / outdated pages per region
* Whether the extra 1 mio packages has been booked
* Number of languages besides German

**Comment by david-venhoff** [comment]
@osmers 
I have two questions:
- Regarding `Number of total pages per region`: Is this about pages or page translations?
- Regarding `Number of missing / outdated pages per region`: Is this the total number of missing/outdated page translations or the total number of pages which have a missing / outdated page translation?

**Comment by osmers** [comment]
Actually, if you can provide me with the information how many german pages have at least one translation missing and or outdated, we could eliminate at least two data points:

Number of total pages per region
Number of missing / outdated pages per region

Possibly even this one, even though it's interesting:
Number of languages besides German

Bcs the OKR I wanted to check with this is this one: 
Am Stichtag 31.12.2024 sind durchschnittlich die Übersetzungen von max. 50 Seiten pro Kommune nicht aktuell.

Also, can we adjust the HIX value to 14 - so the data should show how many pages below 14 exist within a region.

**Comment by david-venhoff** [comment]
> Also, can we adjust the HIX value to 14 

Is 14 the current minimum required for using machine translations? Because I am currently just using that value (Since we already calculate it in the cms)
Or do you prefer to use an actually fixed value?

**Comment by osmers** [comment]
At the conference we decided to keep the minimum for machine translations at 14 - so even after 01.01.2025 that value will be the relevant one - and yes, then it makes sense to just stick to the minimum value for machine translations :) no need for a fixed value, I think

**Comment by JoeyStk** [comment]
Trying to use this feature on our test CMS leads to a `504 Gateway Timeout error`. I fear that this issue is not resolved yet :/

**Comment by david-venhoff** [comment]
Then I think we should merge #3120 and see if that fixes the problem

**Comment by david-venhoff** [comment]
Actually, I think it is fixed now (@svenseeberg  increased the timeout to 30 minutes)

The export took almost 25 minutes though :see_no_evil: 
So we should definitely try to improve the performance

**Comment by JoeyStk** [comment]
You're right! Now it works :)

**Comment by osmers** [comment]
@david-venhoff I just used this for the first time and it works rather quickly :) nicely done. 
One thing I noticed and yes, that is my mistake :D I actually do need the total number of pages per region - otherwise I cannot calculate the percentage of outdated pages or pages with a low HIX-value. 
If I remember correctly you have a second issue to implement a graphic view in the CMS, right? Maybe we can add it there? Or should I open a new issue if it's something that can be easily added to the export?

**Comment by david-venhoff** [comment]
@osmers I think opening a separate issue is okay, and it should be a quick fix :)

**Comment by osmers** [comment]
@david-venhoff can you open the issue? :)
And thanks for understanding and the quick fix.

**Comment by osmers** [comment]
As a separate column pls :)
