### ISSUE TITLE
search and replace links is not working with only invalid links selected

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#3058]
### Describe the Bug

No links are getting replaced when only the `invalid links` checkbox is selected on the links search and replace view.

### Steps to Reproduce
1. Go to Broken Links view
2. Click on Search & Replace
3. Select `Invalid Links` and make sure that no other checkboxes are selected
4. Enter something into search and replace such that an invalid links should get changed
5. Notice that nothing happened after link replacement

### Expected Behavior

Invalid links matching the search should get replaced

### Actual Behavior

They don't get replaced

### Additional Information

This bug happens, because we compare the wanted link types (In this case ['invalid']) against the types of the urls. However, the type of an url only stores, if it is internal, or external, or a phone or email link. Technically, the type can be `invalid`, however that is only the case when the linkcheck library cannot determine what kind of link it is and has nothing to do whether it can be reached over the internet.

Instead, we would have to manually check if a link is invalid.

**Comment by MizukiTemma** [comment]
Should we continue to filter links simply by `OR` condition?

Internal, external, E-mail and phone number are disjoint sets but "invalid" is not, and users maybe want to replace internal AND invalid links (or they may interpret in that way). 

If we allow `AND` operation, UI must be adjusted and some explanation for `AND` and `ÒR` will be needed too.
