### ISSUE TITLE
[2024-11-07] Imported all-day event shows wrong date 

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3109]
### Describe the Bug

When importing an all-day event it shows the wrong end date. The end time is set to 1:00 the following date.

### Steps to Reproduce

1. Go to Nextcloud calendar and create event "Integrationskonferenz" from September 17th to 20th. 
2. Double check that Nextcloud displays it correctly.
3. Import the Nextcloud calendar using the iCal subscription.
4. See in imported events that the events ends on the 21st, not the 20th.

### Expected Behavior

Event is correctly imported

### Actual Behavior

The event is not correctly imported. It shows the wrong end date and time.

### Additional Information

None

**Comment by juliankehne** [comment]
Tested successfully!
