### ISSUE TITLE
Deactivate translation of specific language

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#312]
**This issue is just for future reference, ~at the moment~ we will not fix this.**

In some cases, cities do not want to translate specific pages into all languages. In this case, the xliff files for this translation should not be generated, event if all pages are selected. We have to come up with an idea how to integrate this into our page model, e.g. add a new field `do_not_translate`, which maps to an array of not translated languages. These languages could also be hidden in the tab view.

**Comment by svenseeberg** [comment]
Not to be confused with the translate="no" attribute.

**Comment by timoludwig** [comment]
Since we concluded that this will not be fixed, I'll close this issue now. If it becomes relevant in the future again, we can reopen it.
