### ISSUE TITLE
[2024-12-18] Add language selection box to statistics

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3133]
### Motivation

For the new statistics page we want an universal language selection box for both sections. 

### Proposed Solution

Therefore add a box for language selection and bind it to the already existing language selection provided by chart.js.

### Alternatives

None

### User Story

As a user of the CMS/user of the statistics I want to have an universal language selection so that I don't get confused between the two sections

### Additional Context

This is part of our meta issue #1097

### Design Requirements

Design proposal (v3):
https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?node-id=1179-830

**Comment by nikolahoff** [comment]
@juliankehne @osmers 
1. I agree
2. a deselect all button would be great (will add in the design)
3. I think the user only wants to see the languages that were selected, so I would prefer to export only the selected languages
4. I asked Toni for the reason why the colours get grey. I'm not sure, as she did the Design.

**Comment by juliankehne** [comment]
@nikolahoff @osmers Created issues for 1, 2 & 3 (#3277 #3278 ##3279). Feel free to change them if needed

@nikolahoff As for the 4th point you can create an issue if its supposed to change or comment here if it doesn't matter.

**Comment by nikolahoff** [comment]
@hauf-toni can you please check the 4th point see above?

**Comment by hauf-toni** [comment]
I recommend displaying the colors regardless of whether a language is selected or not. I'm fairly certain that the grey colors are meant as placeholders and were not intended to indicate a disabled status. Sorry if that caused any confusion, and thanks for asking @juliankehne
