### ISSUE TITLE
[2024-11-07] Fix issues with contact form & list view

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3141]
### Describe the Bug

This is a list of a few issues that we had when testing the contact form & list view

- [x] Put location of contact in contact list view in the first column 
- [x] Adjust translation for location
- [x] Fix typo "ihr" to "Ihr"
- [x] Fix help text shouldn't be bold
- [x] Fix help text disappears when saving contact
- [x] Make a few changes to str function for it to be a bit more speaking
- [x] Rename title to point_of_contact_for 

### Additional Information

This issues came up in the first round of testing the contact feature

**Comment by juliankehne** [comment]
@JoeyStk

**Comment by JoeyStk** [comment]
@juliankehne 

> Adjust translation for location

The row which links to location was called "Name des Veranstaltungsortes", which is untrue. Therefore the name should be changed to "Name des verlinkten Ortes". 

> Fix help text shouldn't be bold

If you create a new contact, you get an informational text saying "Wählen Sie einen Ort aus, der für Ihren Kontakt verwendet werden soll oder erstellen Sie einen neuen Ort. Nur veröffentlichte Orte können verwendet werden. " This used to be bold. Now it should be regular font weight :)

> Fix help text disappears when saving contact

The text "Wählen Sie einen Ort aus, der für Ihren Kontakt verwendet werden soll oder erstellen Sie einen neuen Ort. Nur veröffentlichte Orte können verwendet werden. " used to disappear, once you clicked on "Save". This should not be the case anymore. The text itself changes, but there should be some kind of information afterwards :)

> Make a few changes to str function for it to be a bit more speaking

We changed the logic of the display of Contact. When you save a contact now it should say "Kontakt für "Name of location" mit ...". What's followed after the "mit" is decided as followed: If the field "Ansprechperson für" is filled out, it should say "mit Ansprechperson für: Integration". If this field is not filled out, it should fall back on the name, if that's not filled out it should go to the email, then the telephone number and lastly to the website URL. 

Thank you a lot for testing! If anything else comes up, please don't hesitate to ask :)

**Comment by juliankehne** [comment]
@JoeyStk Thanks, all 7 changes tested succesfully now!
