### ISSUE TITLE
Contact form: Copying a Contact with a title that is too long results in Internal Server Error

### ISSUE THREAD

**Issue by juliankehne** [digitalfabrik/integreat-cms#3145]
### Describe the Bug
When copying an existing contact via the Copy Button the system tries to add " (copy)" without "" to the end of the contact title.
However if the title of the contact is too long the (copy) cannot be added and it returns a Internal Server Error, the contact is not copied.

### Steps to Reproduce

1. Go to 'Contacts'
2. Click on 'Create contact'
3. Set the title to the maximum amount of allowed characters
4. Click 'Create'
5. Go back to 'Contacts'
6. Click the Copy button to copy the created Contact
7. See Error

### Expected Behavior
The contact is copied and " (copy)" should be added behind the title. No Internal Server Error.

### Actual Behavior
Internal Server Error when trying to copy a contact with a title that is too long

### Additional Information
Copying Events handles this by just adding the (copy) behind the event name that is too long.
However: #3146

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by PeterNerlich** [comment]
We need to take care that unicode characters might take up more than one "space", and that an implementation that truncates the original title does not split unicode characters in half

**Comment by juliankehne** [comment]
Tested successfully!
