### ISSUE TITLE
Region condition: Add total number of pages column

### ISSUE THREAD

**Issue by david-venhoff** [digitalfabrik/integreat-cms#3174]
### Motivation

To be able to calculate percentages, the region condition data export needs an additional column: `total number of pages` 

### Proposed Solution

Add this column

### Alternatives

None

### User Story

As a service team member I need the total number of pages to calculate percentages in the data export

### Additional Context

Original request by @osmers: https://github.com/digitalfabrik/integreat-cms/issues/3053#issuecomment-2454062136

**Comment by JoeyStk** [comment]
This issue is not resolved yet, as it leads to a server timeout

**Comment by david-venhoff** [comment]
Superseded by #3189

**Comment by juliankehne** [comment]
Tested successfully on cms-test!
