### ISSUE TITLE
Add "edit" icon to contacts 

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3187]
### Describe the Bug

For pages, events and POIs we have an additional icon for editing. For contacts we don't have that yet. After UI/UX testing it was wished for sake of consistency to add the icon to contacts too

### Steps to Reproduce

1. Go to 'pages
2. See icon "edit"
3. Go to 'contact'
4. See it's not there

### Expected Behavior

Consistency between the content types

### Actual Behavior

Icon missing for contacts

### Additional Information

None

**Comment by MizukiTemma** [comment]
@JoeyStk 
Do you mean the pensil icon in the column "Options" in the page/POI/event/contact list? It exists only in the page tree if nothing is missing in my environment. Do we introduce it in all the list views?

**Comment by JoeyStk** [comment]
Yes, I mean the pencil. I assume that we would introduce it to all list views, but this is probably a question for @nikolahoff
