### ISSUE TITLE
Region condition breaks with new column "pages"

### ISSUE THREAD

**Issue by JoeyStk** [digitalfabrik/integreat-cms#3189]
### Describe the Bug

While testing we noticed that the region conditions breaks on the test cms. This is due to the large amount of data.

### Steps to Reproduce

1. Go to network management on the test server
2. Click on 'Region condition'
3. See that loads forever and finally doesn't return anything

### Expected Behavior

A CSV file should be downloaded

### Actual Behavior

Nothing, infinite loading

### Additional Information

This is probably due to the way I have implemented this. It might make sense to try it via a Database Query instead

**Comment by JoeyStk** [comment]
We did a little bit of testing and have an informed guess, that this will not be a problem on our productive system

**Comment by juliankehne** [comment]
Tested successfully on cms-test. Export completed in ~5:30 minutes.
