### ISSUE TITLE
Add Python type hints

### ISSUE THREAD

**Issue by Thomas125** [digitalfabrik/integreat-cms#319]
Enforce type-annotation, see:
- https://docs.python.org/3/library/typing.html
- https://typing.readthedocs.io/en/latest/

**Comment by timobrembeck** [comment]
To check the type hints, we can use mypy: https://mypy-lang.org/

Does anybody know a good tool to convert our current type hints from the docstrings into the real type hint syntax?
Essentially, this was what https://github.com/tox-dev/sphinx-autodoc-typehints is doing, but sphinx only uses this to write the documentation, not to update the source code itself. Maybe we could still use this somehow?

Another possibility is to create stub files with [stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) and read them into the source code with [retype](https://pypi.org/project/retype/), but this still requires a lot of manual work to fix all inconsistencies and incomplete types.

I started working on this on the [`typing`](https://github.com/digitalfabrik/integreat-cms/tree/typing) branch, but there is still much work to do.
