### ISSUE TITLE
Refactor translation models

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#320]
In the meanwhile, it turned out that translation models have more in common than previously expected.
Thus, we can think about abstract `content` and `contentTranslation` classes, which contain all information which the different classes have in common. Plus, we can add some helper functions here.

**Comment by svenseeberg** [comment]
I think you're referring to the `PageTranslation`, `EventTranslation`, `PushNotificationTranslation` and `PoiTranslation` models?

**Comment by timoludwig** [comment]
`PushNotificationTranslation`s are a bit different because they don't have revisions or a reviewing-process, but the others I think are similar enough so we can generalize them in a single content model.

**Comment by timoludwig** [comment]
Also, when we're thinking about refactoring our models, we could also discuss whether it makes sense to add a new layer of e.g. `PageTranslationRevision` models (since all revisions have the fields `page`, `language` and `creator` in common...)

**Comment by svenseeberg** [comment]
We need to decide if we want this `PageTranslationRevision` model or not. I think I'm against introducing this additional model, as the redundant fields are only foreign keys. That means the actual database overhead is limited, while the code complexity may actually increase with an additional model. We could get some better readability in some cases. But I'm not convinced that its worth the effort at the moment.

**Comment by Thomas125** [comment]
Left to do:
- [x] reduce permalink functions
- [ ] docstings
- [ ] inherit content attribute
