### ISSUE TITLE
Event creation not working when 'no physical location' checkbox is selected

### ISSUE THREAD

**Issue by juliankehne** [digitalfabrik/integreat-cms#3223]
### Describe the Bug

When creating a new event an choosing the 'Event does not have a physical location' option and then publishing event it does not create the event, shows and error message and changes the button from 'Publish' to 'Update'.

Afterwards clicking the 'Update' button creates the event without an error message.

### Steps to Reproduce

1. Go to 'Events'
2. Click on 'Create event'
3. Add mandatory information (name, date, etc.)
4. Check the 'Event does not have physical location' checkbox
5. Click 'Publish' button
6. See error message and wrong behaviour

### Expected Behavior

Event is created without error message.

### Actual Behavior

- An error message is shown 'Location: Either disable the event location or provide a valid location '
- No event is created
- The 'Publish' button changed to 'Update' button

### Additional Information

When choosing a physical location the creation works as expected.

<details>
  <summary>Traceback</summary>

  ```
  ```

</details>

**Comment by MizukiTemma** [comment]
It seems to be the problem that "-1" is handed over as `location`.

Furthermore, you cannot remove the event location by clickling " Event does not have a physical location" once the event gets an POI assigned.
