### ISSUE TITLE
Translation: connect automatic translation API

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#36]
Enable connecting automatic translation APIs, for example Google, Linguee, or Bing.

**Comment by svenseeberg** [comment]
I'll create a Python module that we can use in Django for managing all translation stuff.

**Comment by Schedulaar** [comment]
Are we sure, wether this should be part of Proof of Feasability? I think there are already enough (and possibly more important) issues in this milestone.

**Comment by YuelinYang** [comment]
Finished the UI design of automatic translation on the side by side edit view. 
https://github.com/YuelinYang/cms-django/commit/d70e988091e5d013de0a6277d71c4dcada77894d
Due to the missing of language translation API keys, the work is parked.
