### ISSUE TITLE
Centralized version definitions

### ISSUE THREAD

**Issue by thimmy687** [digitalfabrik/integreat-cms#376]
Since we need some version information in several places we should place used versions on an easy accessible place.

python version:
(Readme, Conf.py(sphinx))
django version:
(Readme, Conf.py(sphinx), some docstrings)

**Comment by timoludwig** [comment]
How can we include a centralized version in readme and docstrings? Do we need some kind of pre-processor or replacement-script for this?

**Comment by thimmy687** [comment]
maybe we just create some kind of bump script which contains the version and replace defined places automatically to avoid that we accidentally forgot something?

**Comment by timoludwig** [comment]
Can we use [bump2version](https://pypi.org/project/bump2version/) for this? It can definitively bump the versions o  config files, but I'm not sure if it's also capable of string replacements inside the Readme file...

**Comment by svenseeberg** [comment]
We currently have the `Pipfile.lock` and `package.json` that collect all versions. Do we need anything beyond those two? I think not.

**Comment by timoludwig** [comment]
This is about the version of the cms, not its dependencies.

**Comment by ulliholtgrave** [comment]
This has been solved in @timoludwig versioning for Pypi.
