### ISSUE TITLE
Support slugs for regions in FCM channels

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#385]
> Each blog by default has a `/topics/[BLOG_ID]-[LANG_CODE]-news`. Other topics can be added by Admins in the Page Push Notifications -> Settings. The convention is `/topics/[BLOG_ID]-[LANG_CODE]-[TOPIC]`.

Instead of blog_id, the region slug should be used.

**Comment by timoludwig** [comment]
We already use the region's slug in the FCM topic:
https://github.com/digitalfabrik/integreat-cms/blob/753538ad2c33c02aa56d54a5e9a380b9e9a24634/integreat_cms/cms/views/push_notifications/push_notification_sender.py#L96
So is this issue resolved?

**Comment by svenseeberg** [comment]
Yes, I think so :)
