### ISSUE TITLE
Add sqlite database back end

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#457]
### Motivation
Currently, a PostgreSQL server is needed to run the CMS during development. PostgreSQL can either be installed on the host system or via docker container. It would be much easier to support sqlite as a (default) alternative. That would enable developers to just install a virtual environment (pipenv) and get going.

### Proposed Solution
Add a file `src/backend/sqlite_settings.py` and add a sqlite database back end as default. The `dev-tools` need adjustments, as they check for open local ports and running docker containers.

**Comment by svenseeberg** [comment]
Mael, Emmanuel and I looked into using SQlite as an alternative to PostgreSQL while developing. Currently, we are using PostgreSQL specific model properties, which cannot simply be translated to SQLite. Should we close this issue or change our models? Currently, the problem is `from django.contrib.postgres.fields import ArrayField`.

**Comment by timoludwig** [comment]
Hmm, I think this depends on how you prioritise this issue. For me personally, I think we already have an easy way to get started by installing docker. Sure, SQLite would be even simpler, but I don't think it's necessary if it requires much effort (You would not only need to come up with a new data type for arrays in the models, but also adjust the form handling and saving process).

I'd suggest leaving the issue open for now but as it is with low priority and milestone "additional features". If at some point somebody wants to implement it, why not...

**Comment by timoludwig** [comment]
- `JSONField` isn't an issue anymore after Django 3.1 (see #723)
- Suggestion for `ArrayField`:
    - Convert `Region.push_notification_channels` (Array of strings) to a normal ForeignKey to the `PushNotificationChannel` model
    - Convert `RecurrenceRule.weekdays_for_weekly` (Array of ints) to a `JSONField`

**Comment by JoeyStk** [comment]
> I'd vote for closing this ticket as wontfix 😉

Agreed

**Comment by JoeyStk** [comment]
In a popular vote within the team it was decided that there is no need to implement this any time soon.
