### ISSUE TITLE
API: package site/page resources

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#46]
Endpoint which packages (tar) all resources required for a page or site. This includes linked PDFs and sourced images.

Included should be all resources hosted on the CMS. External resources should not be bundled.

For this, the content of https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#pageseventslocationsdisclaimer needs to be analyzed and then all resources bundled.

**Comment by ulliholtgrave** [comment]
No longer needed
