### ISSUE TITLE
Warn users about insecure browsers

### ISSUE THREAD

**Issue by timobrembeck** [digitalfabrik/integreat-cms#571]
### Motivation

In WordPress, there is a warning if users use the system with an insecure browser:
![bam](https://user-images.githubusercontent.com/16021269/98116931-520fb700-1ea9-11eb-9a53-c66de35787fb.PNG)
Especially in our userbase (public authorities) this still seems to be a common problem. 

### Proposed Solution

Add a similar warning on the dashboard.

**Comment by svenseeberg** [comment]
I remember the discussion about this. But maybe we should consider this to be a part of OS functionality? I vote for closing this. If someone objects, please reopen :)
