### ISSUE TITLE
Compatibility API

### ISSUE THREAD

**Issue by sascha11110** [digitalfabrik/integreat-cms#61]
The current API has some weaknesses, so an ideal new API for this rebuild would look different. Is it possibly easier to build this new API directly and then prevent adjustments in the consuming applications (native, web aoo) by building an additional layer (compatibility API) in between that maps the new API to the old standard?

**Comment by svenseeberg** [comment]
Can you specify the weaknesses?

**Comment by sascha11110** [comment]
@maxammann I think you know best about this.

**Comment by maxammann** [comment]
I'll create a list of problems with the current API.

**Comment by maxammann** [comment]
to be discussed in gdoc

**Comment by ulliholtgrave** [comment]
No longer needed
