### ISSUE TITLE
Timezone aware events

### ISSUE THREAD

**Issue by Thomas125** [digitalfabrik/integreat-cms#663]
### Motivation
Currently, the date- and time-information of events is naive (i.e. has no timezone information). It should be aware.
This is independent of #662 since events should be stored with timezone-information even in a single-timezone-situation (regarding migration, change of timezone etc.)

### Proposed Solution
Store date and time of events in a datetime-attribute in the models, instead of one date- and one time-attribute.

### Alternatives
None (I think)

### Additional Context
#652 contains information about how timezone-issues are resolved in django.

**Comment by timoludwig** [comment]
Regarding the problem on all-day-events:

I think, the best option might be to extend the event model with an additional `CharField` which contains the timezone of the event. For now, the default value of this field should be read from the following setting: https://github.com/Integreat/integreat-cms/blob/0d623d97bfd2bc91765fbc3e93c4f37a7f15b0dc/src/backend/settings.py#L571
In the future, we might make this configurable in the form or derive it from the creator's local time.
Then, in the event form's `clean()` method, we could convert the UTC date to the local time of the `timezone` field and check whether the local time is `datetime.time.min` resp. `datetime.time.max`...

@Thomas125 What do you think about this? If you think this isn't a good solution, I'm also fine with adding a boolean field `all_day` to the event model.

**Comment by timoludwig** [comment]
This was solved in #1642 :tada:
