### ISSUE TITLE
Improve page filter

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#686]
### Motivation

Add new fields to the page filter form

### Proposed Solution

Those filter functionatiries should be implemented. A check mark means the functionarity is implemented.
- [x]  Filter by status of the latest revision (public, draft, review) #1918 
- [x]  Filter by last updated date #1918 
- [ ]  Filter by total number of words in one translation
- [ ]  Filter to exclude whole chapters (parent page + all children)

**Comment by ulliholtgrave** [comment]
In addition, the Pages filter should be refactored to match the filter for the feedback elements (see Screenshot).
![grafik](https://user-images.githubusercontent.com/15608678/114268937-397d6d00-9a04-11eb-8b5f-92f6ca807408.png)

**Comment by ulliholtgrave** [comment]
The service team requested a filter to exclude whole chapters with all subpages. I updated the tickets accordingly.

**Comment by timoludwig** [comment]
> The service team requested a filter to exclude whole chapters with all subpages. I updated the tickets accordingly.

Did they specify how exactly this should work?
E.g. a drop down select input of root pages? Or would we need to also exclude second level chapters and/or multiple chapters at once?

**Comment by ulliholtgrave** [comment]
We need an option to exclude specific parent pages and it doesn't matter on which level they are. Regarding the implementation itself I would give that to the UI/UX team.

**Comment by svenseeberg** [comment]
It could potentially be interesting to expand the full page tree and with colors highlight those pages that fit the filter. We can also remove the check boxes for those pages that do not fulfill the filter criteria. When using the "Select all" function, only the pages that are withing the filter criteria would be selected.

**Comment by osmers** [comment]
I think that is an interesting approach to the whole exclude pages/chapter issue - if it is only for us (Integreat Teams) that would be cool - if it should also be available for the Kommunen, maybe some UI/UX input would be good

**Comment by dkehne** [comment]
We have discussed this internally @JoeyStk @ulliholtgrave @svenseeberg . Good news: We can close that. The current two implemented filters are fitting very well. the exclusion of specific chapters is nice, but just a fringe cases which only helps our service team in specific scenarios. with deepl-process we might already have less of theses cases...
