### ISSUE TITLE
Extend `POI` model

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#726]
### Motivation
The map feature requires to have additional fields for our POI model. 

### Proposed Solution
The following (optional) attributes are necessary:
* Website address (URL)
* Contact e-mail address
* Contact phone number
* (Opening hours) TBD
* Icon (Original)
* Icon (Thumbnail_150x150)

This issue is deeply connected to #951 and could be solved together with it.

**Comment by timoludwig** [comment]
When implementing this, the POI-model parts of #695 and #522 could be included as well:
- Add boolean field `show_location_on_map`
- Add text field `meta_description`
