### ISSUE TITLE
Refactor Pages Overview

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#844]
### Motivation
The users seem to have a problem with the current implementation with the page tree. The expansion function and the UI seem to be too different then the tree view in Wordpress.

### Proposed Solution
After consultation with the municipalities team, the following aspects are to be adapted to the view:

- Restructure Page Fields to: hierarchy -> Title -> Tags -> Languages -> Status
- Provide default format for "Last edited" field (e.g. padding with zeroes and month with 3 letters)
- Provide different background colors for the different hierarchy levels
- Rename Pages to "Page Tree"
- Hint pop up on first page load with "never show again" check box.

UI/UX-Recommendations (in german) for download

![CMS UX Analyse 02](https://user-images.githubusercontent.com/15608678/144991967-9b2b451e-4934-48a0-ae6c-f7eea35e15cd.png)

**Comment by svenseeberg** [comment]
Ideas for improving the usability:
- Change cursor on mouse over to crossed arrows.
- Hint pop up on first page load with "never show again" check box.

**Comment by ulliholtgrave** [comment]
As discussed with the cities team, I updated the proposed solution for the issue.

**Comment by ulliholtgrave** [comment]
I updated the description with the UI/UX recommendations.
