### ISSUE TITLE
Provide information for improved search (or API)

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/integreat-cms#86]
Currently the client is not able to implement a search based on fuzzy-matching and keywords.

Fuzzy matching would probably be possible on the client for the titles/keywords, but not for the content.

An NLP approach is probably not required.

**Comment by steffenkleinle** [comment]
Out of scope atm and partially already implement in the client side using minisearch (see #https://github.com/digitalfabrik/integreat-app/issues/1127).
