### ISSUE TITLE
Refactoring of the page hierachy

### ISSUE THREAD

**Issue by ulliholtgrave** [digitalfabrik/integreat-cms#945]
### Motivation
To provide a more performant approach for the hierarchy generation, we want to refactor our current behavior. To do so, we want to generate the tree via the translations instead of the page items.

### Proposed Solution

Since `page.translations` is a more complex sql operation than `translation.page`, it might be faster to get all public page translations first and then gather the hierarchy from their page foreign keys instead of having the hierarchy first and then having to query the current translation for each page.

However, This is just a thought and while it requires complex changes, it's not so clear how much the improvement would be. Thus, we should implement the approaches #942, #943 and #944 first before tackling this issue.

**Comment by svenseeberg** [comment]
If we do this, we could do #320 at the same time.

**Comment by timoludwig** [comment]
After the performance refactoring introduced in #1088, this will no longer be necessary.
