### ISSUE TITLE
Categories for POIs

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#951]
If many locations/POIs are displayed on the map within the app, we want to add a category field to our POIs that can later be used by the apps for filtering etc. The categories should be dynamic and not be hardcoded.

Example categories are: 
Beratungsstelle - Advice center
Behörde/Amt - Authority/Office
Treffpunkt - Hangout
Freizeit - Recreation
Einkaufen - Shopping
Dienstleistung - Service
Mobilität - Mobility
Gesundheit - Health
Kultur - Culture
Gastronomie - Gastronomy

**Comment by timoludwig** [comment]
Probably it makes sense to create a new model `POICategory` or similar where we can create new entries in the network area which can then be selected in a choice field in the `POI` model, right?

**Comment by dkehne** [comment]
I would suggest to use the same categories as we use in social pass and volunteering card + additionally Behörde/Amt

Behörde/Amt - Authority/Office
Einrichtung - Institution
Treffpunkt - Hangout
Freizeit - Recreation
Einkaufen - Shopping
Dienstleistung - Service
Mobilität - Mobility
Gesundheit - Health
Kultur - Culture
Gastronomie - Gastronomy
Multimedia - Multimedia
Sonstiges - Others

**Comment by timoludwig** [comment]
@dkehne The categories are only stored in the database and can be managed in the CMS without having to change the source code.
