### ISSUE TITLE
Meta: Implement legacy API

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-cms#97]
This is an meta issue with links to all API issues:
* [x] #1099
* [x] #19 
* [x] #79
* [x] #17 
* [x] #80
* [x] #46 
* [x] #28 
* [x] #27
* [x] #350
* [x] #26
* [x] #349
* [x] #25
* [x] #24
* [x] #23 
* [x] #22 
* [x] #20 
* [x] #18
* [x] #16
* [x] #15 
* [x] #14 
* [x] #114 
* [x]  #793 
* [x] #794

**Comment by timoludwig** [comment]
idea: use [swagger.io](swagger.io) to design the API and generate the docu and django code from it.

**Comment by svenseeberg** [comment]
During the team call yesterday we decided, that we're going to use Swagger (or a similar service) with APIv4. Implementing it in version 3 is not useful, because we do not have strong typing and clear definitions yet. Also, the API is already implemented in the apps and the app teams would have to rewrite the API part to make use of a Swagger-like service.
