### ISSUE TITLE
Make it easier to set exact pixel sizes for images

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-cms#995]
### Motivation

At the moment, the UI for setting the exact pixel sizes for images is very hard to find:

1. One has to right-click on the image:
    <img src="https://user-images.githubusercontent.com/16021269/139214575-df748b1a-f497-45ed-8a8a-de41380978e9.png" width="400" />

2. left-click somewhere else in the browser (but not on the page) to hide the browser's inbuilt context menu while tinymce's context menu is still visible:
    <img src="https://user-images.githubusercontent.com/16021269/139214609-4e27b1f7-730c-4d88-9c66-9993fe5eeec4.png" width="400" />

3. Then open the option "Image..." in the tinymce context menu and only then, this window appears:
    <img src="https://user-images.githubusercontent.com/16021269/139212769-2fecf019-b4f4-4973-96d1-2f9f3098e518.png" width="400" />

### Proposed Solution

Come up with a good solution to make this window more accessible - maybe add a hover effect on the image with a small "edit" button or similar

**Comment by melegiul** [comment]
Unfortunately I can not reproduce this behavior.
I am on a debian 10 and tested setting the pixel size in:
chrome 95.0.4638.69
firefox 78.15.0esr
in both cases only the tinymce menu shows up

**Comment by timoludwig** [comment]
Ok, I only experience the overlaying context-menu on my Firefox 94.0.2 (64-Bit) on arch linux. Then it's probably a weird browser issue which none of our users have.

Still, the way of right-clicking on the image to change the size is different than in wordpress and might lead to problems with our user base (e.g. the testing team from the municipality team was unable to change the pixel-size for images because they just didn't think of right-clicking on the image and then selecing "image..."). Instead, in wordpress, the following UI pops up when left-clicking on the image:
![wordpress-screenshot](https://user-images.githubusercontent.com/16021269/142742707-f17a2aae-eb9b-46b7-8600-a51fafda3407.png)
So even if this is a bit different, maybe it's enough to change the behaviour in a way that our context menu appears when the user left-clicks on the image instead of right-clicking? but this needs further clarification with UI/UX in my opinion.
Probably, this isn't as concerning anymore and can be moved to the Version 1.1/1.2 milestone.

**Comment by ulliholtgrave** [comment]
I guess that the new pixel-sizing can be introduced in a new tutorial for the page editor, but we should introduce some new images sizes that we can deliver images that fit the selected pixel sizes. This means that we need to introduce another image class if we upload a image and add another HTML-Check if we save a page.

**Comment by timoludwig** [comment]
I noticed this was a configuration problem on my side - I somehow had `dom.event.contextmenu.enabled` set to `false` in my firefox config.
